### ISSUE TITLE
NPE when try create a Column Named Value

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1005]
1. Create a new Table.
2. Add Column named: **Value**.
It return a NPE...
![issue65](https://cloud.githubusercontent.com/assets/2333092/25363701/8997319e-292a-11e7-96b9-aff74cc9c174.png)
<pre>
-----------> MColumn.save: beforeSave - MColumn[0-Value] [14]
java.lang.NullPointerException
	at org.compiere.model.MColumn.lambda$0(MColumn.java:318)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.compiere.model.MColumn.beforeSave(MColumn.java:314)
	at org.compiere.model.PO.save(PO.java:2102)
	at org.compiere.model.GridTable.dataSavePO(GridTable.java:2139)
	at org.compiere.model.GridTable.dataSave(GridTable.java:1474)
	at org.compiere.model.GridTab.dataSave(GridTab.java:987)
	at org.compiere.apps.APanel.cmd_save(APanel.java:2036)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1744)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)

-----------> GridTable.saveWarning: Error -  [14]
<pre>

**Comment by yamelsenih** [comment]
I try make it with **Central ID** flag enabled

**Comment by yamelsenih** [comment]
It was resolved on #917
