### ISSUE TITLE
Error trying to add masive data fro Import_Budget

### ISSUE THREAD

**Issue by sbouissa** [adempiere/adempiere#1010]
[Error ImportBudget.txt](https://github.com/adempiere/adempiere/files/965593/Error.ImportBudget.txt)

**Comment by e-Evolution** [comment]
-------------------------------
===========> ImportBudget.process: java.lang.NullPointerException [179]
java.lang.NullPointerException
	at org.compiere.process.ImportBudget.doIt(ImportBudget.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:577)
	at org.adempiere.webui.apps.ProcessModalDialog.runProcess(ProcessModalDialog.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

-------------------------------
===========> ImportBudget.process: java.lang.NullPointerException [63]
java.lang.NullPointerException
	at org.compiere.process.ImportBudget.doIt(ImportBudget.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:577)
	at org.adempiere.webui.apps.ProcessModalDialog.runProcess(ProcessModalDialog.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

**Comment by sbouissa** [comment]
Ok
