### ISSUE TITLE
User3 and User4 cause errors generating invoice from shipment: introduced in #665

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1050]
It is introduced on #665 
![arbol_20](https://cloud.githubusercontent.com/assets/2333092/26359109/8ec2771c-3fa2-11e7-869a-0b98d35b847a.png)

<pre>
===========> Query.firstOnly: SELECT QtyBatchSize,Planner_ID,CopyFrom,QtyBatchs,Processed,DateConfirm,DateDelivered,DateFinish,DateFinishSchedule,DateOrdered,DatePromised,DateStart,DateStartSchedule,Description,QtyReserved,IsApproved,Lot,M_AttributeSetInstance_ID,OrderType,QtyEntered,AD_OrgTrx_ID,User1_ID,User2_ID,IsPrinted,IsQtyPercentage,IsSOTrx,IsSelected,Line,M_Warehouse_ID,FloatBefored,QtyOrdered,QtyReject,DocAction,DocStatus,FloatAfter,QtyScrap,ScheduleType,SerNo,QtyDelivered,DocumentNo,S_Resource_ID,PP_Order_ID,Posted,PriorityRule,AD_Workflow_ID,PP_Product_BOM_ID,Assay,C_Activity_ID,C_Campaign_ID,C_DocTypeTarget_ID,C_DocType_ID,C_OrderLine_ID,C_Project_ID,C_UOM_ID,M_Product_ID,Yield,ProcessedOn,C_ProjectPhase_ID,C_ProjectTask_ID,M_Shipper_ID,DeliveryRule,DeliveryViaRule,FreightCostRule,M_FreightCategory_ID,TrackingNo,User3_ID,User4_ID,Created,Processing,CreatedBy,AD_Org_ID,AD_Client_ID,Updated,UpdatedBy,IsActive FROM PP_Order WHERE ( C_OrderLine_ID = ?  AND DocStatus IN  (?,?) AND EXISTS (SELECT 1 FROM  PP_Order_BOM  WHERE PP_Order_BOM.PP_Order_ID=PP_Order.PP_Order_ID AND PP_Order_BOM.BOMType =? )) [295]
org.postgresql.util.PSQLException: ERROR: column "user3_id" does not exist
  Position: 807; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.Query.createResultSet(Query.java:758)
	at org.compiere.model.Query.firstOnly(Query.java:339)
	at org.eevolution.model.LiberoValidator.updateMPPOrder(LiberoValidator.java:388)
	at org.eevolution.model.LiberoValidator.docValidate(LiberoValidator.java:251)
	at org.compiere.model.ModelValidationEngine.lambda$11(ModelValidationEngine.java:510)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
</pre>

**Comment by yamelsenih** [comment]
It must be resolved on #665
