### ISSUE TITLE
Error when a process button deletes a record from the window

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#1059]
Example process button: Reset Allocation Direct in View Allocation window. 
![image](https://cloud.githubusercontent.com/assets/9552217/26511786/8e3d2de6-4231-11e7-8de5-d902ac1a79ed.png)
```
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.compiere.model.GridTable.getWhereClause(GridTable.java:2250)
>>	at org.compiere.model.GridTable.dataRefresh(GridTable.java:2771)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:963)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:943)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.updateUI(AbstractADWindowPanel.java:2389)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.unlockUI(AbstractADWindowPanel.java:2357)
>>... [24]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException
>>	at org.compiere.model.GridTable.getWhereClause(GridTable.java:2250)
>>	at org.compiere.model.GridTable.dataRefresh(GridTable.java:2771)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:963)
>>	at org.compiere.model.GridTab.dataRefresh(GridTab.java:943)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.updateUI(AbstractADWindowPanel.java:2389)
>>	at org.adempiere.webui.panel.AbstractADWindowPanel.unlockUI(AbstractADWindowPanel.java:2357)
>>... [24]
```

**Comment by yamelsenih** [comment]
I test it and the NPE is gone.

Thank you @Raul-mz
