### ISSUE TITLE
Class Not Found on SB for Generate Invoice from Order Line 

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1070]
When i try generate a invoice from Order line with SB **Menu** -> **Quote-to-Invoice** -> **Sales Invoices** -> **Generate Invoice From OrderLine**. It return a class not found

![arbol_52](https://cloud.githubusercontent.com/assets/2333092/26748027/3a838b18-47c8-11e7-824b-864e16baad42.png)

<pre>
-----------> ProcessUtil.startJavaProcess: org.shw.process.SB_InvoiceGenerateFromOrderLine [13]
java.lang.ClassNotFoundException: org.shw.process.SB_InvoiceGenerateFromOrderLine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at org.eevolution.form.VBrowser.cmd_Process(VBrowser.java:514)
	at org.eevolution.form.VBrowser.actionPerformed(VBrowser.java:723)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
</pre>

**Comment by yamelsenih** [comment]
It is fixed, also is added as parameter:
- **Organization Trx**: For set Org on Invoice.
- **Add Invoice Reference Line**: It allow choice if is added a line on invoice with information about delivered or not.
- **Document Type**: For set a document Type on Invoice to will be generated.
![arbol_53](https://cloud.githubusercontent.com/assets/2333092/26748907/a403ee4a-47d0-11e7-8b53-3a06d21c1671.png)
