### ISSUE TITLE
Synchronize Column is unnecessary when it is not apply for DB

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1072]
When i try apply a XML, it is failed:

- I try change a value for selection column on a column.
- Apply XML
- It is failed.

It should be synchronize column when it have changes like:

- DB name.
- Reference
- Length
- Mandatory
- Key Column
- Parent Link

![arbol_55](https://cloud.githubusercontent.com/assets/2333092/26759093/6e2168ba-48c1-11e7-8461-dd028df3cb39.png)
![arbol_56](https://cloud.githubusercontent.com/assets/2333092/26759094/6e33c758-48c1-11e7-8b14-9fc1b1fff36d.png)
<pre>
-----------> MMigrationStep.bailout: Migration 2680 - System Config reversal invoice DocNo #887 - 3.9.0 (D) ; Step: 90; Type: AD.  Application failed: org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view [149]
===========> MigrationStepApply.process: Migration 2680 - System Config reversal invoice DocNo #887 - 3.9.0 (D) ; Step: 90; Type: AD. Application failed: org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view [149]
org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view
	at org.compiere.util.DB.executeUpdateEx(DB.java:1129)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1180)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1171)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:813)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:588)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
caused by: org.postgresql.util.PSQLException: ERROR: Failed to recreate dependent view; State=P0001; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1120)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1180)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1171)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:813)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:588)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
</pre>

**Comment by yamelsenih** [comment]
Is necessary create a update for all fields

**Comment by yamelsenih** [comment]
Hi @e-Evolution please apply

**Comment by yamelsenih** [comment]
Resolved
