### ISSUE TITLE
Duplicate key when try reverse a Journal Batch

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1073]
Trying to reverse a Journal Batch it return a error with duplicate key for **GL_JournalBatch_ID**

![arbol_57](https://cloud.githubusercontent.com/assets/2333092/26760080/d08ee68c-48dd-11e7-8210-a52d37582013.png)

<pre>
===========> DB.saveError: DBExecuteError - ERROR: duplicate key value violates unique constraint "gl_journalbatch_pkey"
  Detail: Key (gl_journalbatch_id)=(50000) already exists. [142]
-----------> MJournalBatch.saveNew: [WFP_ced1a374-2e90-430b-9666-bb717d3f04b4]Not inserted - GL_JournalBatch [142]
-----------> MWFActivity.run: MWFNode[208-(DocAuto),Action=DocumentAction=--] [142]
org.adempiere.exceptions.AdempiereException: ERROR: duplicate key value violates unique constraint "gl_journalbatch_pkey"
  Detail: Key (gl_journalbatch_id)=(50000) already exists.
	at org.compiere.model.PO.saveEx(PO.java:2254)
	at org.compiere.model.MJournalBatch.reverseCorrectIt(MJournalBatch.java:653)
	at org.compiere.process.DocumentEngine.reverseCorrectIt(DocumentEngine.java:563)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:342)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:260)
	at org.compiere.model.MJournalBatch.processIt(MJournalBatch.java:281)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:897)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:789)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:370)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:280)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:278)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:806)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:502)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:727)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:796)
</pre>

**Comment by yamelsenih** [comment]
It is caused by the follow method:

<pre>
public MJournalBatch (MJournalBatch original)
{
		this (original.getCtx(), 0, original.get_TrxName());
		setClientOrg(original);
		setGL_JournalBatch_ID(original.getGL_JournalBatch_ID());
		//
	//	setC_AcctSchema_ID(original.getC_AcctSchema_ID());
	//	setGL_Budget_ID(original.getGL_Budget_ID());
		setGL_Category_ID(original.getGL_Category_ID());
		setPostingType(original.getPostingType());
		setDescription(original.getDescription());
		setC_DocType_ID(original.getC_DocType_ID());
		setControlAmt(original.getControlAmt());
		//
		setC_Currency_ID(original.getC_Currency_ID());
	//	setC_ConversionType_ID(original.getC_ConversionType_ID());
	//	setCurrencyRate(original.getCurrencyRate());
		
	//	setDateDoc(original.getDateDoc());
	//	setDateAcct(original.getDateAcct());
	//	setC_Period_ID(original.getC_Period_ID());
}	//	MJournal
</pre>
