### ISSUE TITLE
01130_922_936_IsAllowCopyColumn.xml In ORACLE XE FAILS

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1138]
01130_922_936_IsAllowCopyColumn.xmlplication failed  java.sql.SQLSyntaxErrorException ORA-00911: invalid charactec

**Comment by yamelsenih** [comment]
Hi @lbetanzo please can you provide more information about it bug?

Step number or complete log?

Best Regard.

**Comment by yamelsenih** [comment]
i find it error, see the log:
<pre>
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
; State=22019; ErrorCode=911
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:64)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:359)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
</pre>

**Comment by yamelsenih** [comment]
Hi @lbetanzo it error is solved, please test it and write us

**Comment by yamelsenih** [comment]
Note:
- The primary key for T_Report is not good.
- Is nice if not exist a column NOT NULL (It make more delay on INSERT)
- Is nice if not exist a column with CONSTRAINT (It make more delay on INSERT or DELETE a parent table)

**Comment by testiranje1234** [comment]
T_REPORT have 4 pk
CREATE TABLE  "T_REPORT" 
   (	"AD_PINSTANCE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"PA_REPORTLINE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RECORD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FACT_ACCT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SEQNO" NUMBER, 
	"LEVELNO" NUMBER(10,0) DEFAULT 0, 
	"NAME" NVARCHAR2(60), 
	"DESCRIPTION" NVARCHAR2(255), 
	"COL_0" NUMBER DEFAULT NULL, 
	"COL_2" NUMBER DEFAULT NULL, 
	"COL_1" NUMBER DEFAULT NULL, 
	"COL_3" NUMBER DEFAULT NULL, 
	"COL_4" NUMBER DEFAULT NULL, 
	"COL_5" NUMBER DEFAULT NULL, 
	"COL_6" NUMBER DEFAULT NULL, 
	"COL_7" NUMBER DEFAULT NULL, 
	"COL_8" NUMBER DEFAULT NULL, 
	"COL_9" NUMBER DEFAULT NULL, 
	"COL_10" NUMBER DEFAULT NULL, 
	"COL_11" NUMBER DEFAULT NULL, 
	"COL_12" NUMBER DEFAULT NULL, 
	"COL_13" NUMBER DEFAULT NULL, 
	"COL_14" NUMBER DEFAULT NULL, 
	"COL_15" NUMBER DEFAULT NULL, 
	"COL_16" NUMBER DEFAULT NULL, 
	"COL_17" NUMBER DEFAULT NULL, 
	"COL_18" NUMBER DEFAULT NULL, 
	"COL_19" NUMBER DEFAULT NULL, 
	"COL_20" NUMBER DEFAULT NULL, 
	"TABLEVEL" NUMBER(10,0), 
	"REPORTLINESTYLE" CHAR(1), 
	"FIXEDPERCENTAGE" NUMBER(10,0), 
	"ACCOUNTTYPE" CHAR(1), 
	"AX_CASE" CHAR(1), 
	"C_VALIDCOMBINATION_ID" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "T_REPORT_KEY" PRIMARY KEY ("AD_PINSTANCE_ID", "PA_REPORTLINE_ID", "RECORD_ID", "FACT_ACCT_ID") ENABLE, 
	 CONSTRAINT "PAREPORTLINE_TREPORT" FOREIGN KEY ("PA_REPORTLINE_ID")
	  REFERENCES  "PA_REPORTLINE" ("PA_REPORTLINE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "ADPINSTANCE_TREPORT" FOREIGN KEY ("AD_PINSTANCE_ID")
	  REFERENCES  "AD_PINSTANCE" ("AD_PINSTANCE_ID") ON DELETE CASCADE ENABLE
   )
/

**Comment by yamelsenih** [comment]
Hi @testirange1234 I am using it issue for it: #1151 please see it and write us

**Comment by testiranje1234** [comment]
ok, but first need download and re-build all code, its half an hour on existing virtual box machines every-weekly-uprgade process (simple its most efficiency way, with more xml migration every RUN_MigrationXML give confusion on oracles schemas)
![adempiere_release_22062017_1520](https://user-images.githubusercontent.com/26572325/27436164-ac82ab18-575e-11e7-9295-388e8bc585ce.png)

**Comment by yamelsenih** [comment]
I rewrite the XML, please just rebuild it from last changes and test.

**Comment by testiranje1234** [comment]
ok, at that moment I was just re-install and re-build all code, and now I running run_migrationxml.sh
(2 cpu with 90% -not half hour, its 45 minutes :) )

**Comment by yamelsenih** [comment]
Hahahaha, tell me when you test it...

**Comment by testiranje1234** [comment]
databases changes from 16062017 untill now, I m run 
select * from adempiere390_22062017.ad_field_vt minus select * from adempiere390_16062017.ad_field_vt give me changes in dates,  alter tables ad_column with add new column -IsAllowCopy
all works good, full installation before one hour.

![ad_22062017](https://user-images.githubusercontent.com/26572325/27443055-446275c2-5772-11e7-8a1f-e8a7dc71acd2.png)

**Comment by yamelsenih** [comment]
Thank you @testiranje1234 i will close it
