### ISSUE TITLE
You CANOT LOGIN IN ADEMPIERE 

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#1141]
You CANOT LOGIN IN ADEMPIERE not in the client and not in the web or movile and still very slow in setup.bat

**Comment by yamelsenih** [comment]
Hi @lbetanzo please can you provide more information about it bug?
Please put here a terminal log.

Best Regard.

**Comment by yamelsenih** [comment]
Hi @lbetanzo it is because a XML is failed, the XML is 02370_Add_IsLoginUser_Feature.xml it throw a error:

<pre>
org.adempiere.exceptions.AdempiereException: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3570; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$2(ProcessBuilder.java:205)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
</pre>

**Comment by yamelsenih** [comment]
Hi @lbetanzo it was solved on https://github.com/adempiere/adempiere/commit/642ecfc1034d15875ada58c24ab7df50fc806055

Please test it for close

**Comment by yamelsenih** [comment]
Hi @testiranje1234 can you review it?

Best Regard

**Comment by yamelsenih** [comment]
I test it when apply all XML for seed and is ok
