### ISSUE TITLE
0136_900_FinReportLines.xml throw error

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1151]
Whe i runnin the XML it throw a error with oracle compatibility, see:

<pre>
java.sql.BatchUpdateException: error occurred during batching: ORA-00907: missing right parenthesis
; State=null; ErrorCode=17081
	at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4615)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeBatch(NewProxyStatement.java:743)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:356)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)
</pre>

Also:

The primary key for T_Report is not good.
Is nice if not exist a column NOT NULL (It make more delay on INSERT)
Is nice if not exist a column with CONSTRAINT (It make more delay on INSERT or DELETE a parent table)

**Comment by yamelsenih** [comment]
It is ready for testing

**Comment by yamelsenih** [comment]
Hi @testiranje1234 can you review it?

Best Regard

**Comment by testiranje1234** [comment]
I m back from pause, :)
ok, I m looking at /base/src/org/compiere/model/MigrationStep
(X_AD_MigrationStep)
svnprocess,processutil,procesctl



2017-06-22 18:01 GMT+02:00 Yamel Senih <notifications@github.com>:

**Comment by testiranje1234** [comment]
at the end of log files, before 4 hours, need to found/watch...


2017-06-22 22:19 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by yamelsenih** [comment]
Hi @testiranje1234, i test it and is ok, are you testing it?
