### ISSUE TITLE
Remove last ; character for migration Step

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1164]
I try apply a SQL Statement frolm Migration window:
- The SQL Statement ended with ";" character.
- The Parse Statement is flagged as **false**.

When it is apply on PostgreSQL the working is Ok. But if i try apply it on Oracle DB is returned a error with a bad character ";".

**Comment by yamelsenih** [comment]
Hi, is is solved and waiting and testing.

**Comment by yamelsenih** [comment]
Hi @testiranje1234 can you review it?

Best Regard

**Comment by yamelsenih** [comment]
I test it when apply all XML for seed and is ok

**Comment by testiranje1234** [comment]
I have last  unapply 1800 here is log file (log.tar.gz)  
![ad_22062017aa](https://user-images.githubusercontent.com/26572325/27456417-3cd42434-57a1-11e7-9090-96902502a3c6.png)
[2017-06-22_1.log.tar.gz](https://github.com/adempiere/adempiere/files/1096213/2017-06-22_1.log.tar.gz)

**Comment by yamelsenih** [comment]
@testiranje1234 have you the clean seed? i am aply all XML and it are in 2330 and it worked, see the pic
![prueba de actividad6](https://user-images.githubusercontent.com/2333092/27457059-398fc254-5771-11e7-971e-5d9a1a46c6de.png)

**Comment by testiranje1234** [comment]
No. How can clean seed?

**Comment by yamelsenih** [comment]
i restore the DB loceted on ADEMPIERE_HOME/data/seed for oracle and apply all XML for it and is ok

**Comment by testiranje1234** [comment]
ok, I will do.
I have this error at the end of log wiles after RUN_MigrationXML is completed
11:16:53.523   MMigrationStep.fromXmlNode: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) : Step 10 loaded [1]
11:16:53.525   GridField.loadLookup: (ReportType) [1]
11:16:53.562   MMigration.updateStatus: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D)  ---> Unapplied (U) [1]
11:16:53.608   MMigrationStep.apply: Applying migration step: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  [1]
11:16:53.863   MIssue.create: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-01917: user or role 'ADEMPIERE' does not exist
 [1]
11:16:53.864   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-01917: user or role 'ADEMPIERE' does not exist
 [1]
-----------> MMigration.apply: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-01917: user or role 'ADEMPIERE' does not exist
 [1]
11:16:54.072   MMigrationStep.apply: Applying migration step: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  [1]
11:16:54.081   MIssue.create: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
11:16:54.081   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
-----------> MMigration.apply: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
11:16:54.113   MMigration.updateStatus: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D)  ---> Unapplied (U) [1]
11:16:54.121   MMigration.updateStatus: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D)  ---> Unapplied (U) [1]
11:16:54.122 MigrationApply.addLog: 0 - null - null - Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
11:16:54.133   MIssue.create: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
11:16:54.134   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
 [1]
org.adempiere.exceptions.AdempiereException: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist

	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:391)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist
; State=null; ErrorCode=17081
	at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4615)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeBatch(NewProxyStatement.java:743)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:356)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

11:16:54.190 Trx.rollback: **** TrxRun_114305a5-8cb9-47f7-8269-c981a43712c4 [1]
11:16:54.195   MIssue.create: Loading Migration from XML failed. [1]
11:16:54.196   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /home/nadrog/Adempiere/migration/380lts-release/01800_739_UpdateViewWithNewUserDimension.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 1800 - Update Account View with new user dimension - 3.9.0 (D) ; Step: 10; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: error occurred during batching: ORA-00942: table or view does not exist

	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:294)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)


*** 2017-06-22 11:16:54.246 Adempiere Log (CLogFile) ***

**Comment by yamelsenih** [comment]
I am apply all XML and is OK, please test newsly and tell me

**Comment by testiranje1234** [comment]
ok, I will

**Comment by yamelsenih** [comment]
I add a minor change
