### ISSUE TITLE
Error Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1174]
The problem is that : 
CREATE INDEX AD_User_Value ON AD_User USING BTREE(AD_Client_ID, Value)
 
Bug introducing #403

This sentence launch an error because not can create unique value.

01:38:36.512   MMigrationStep.apply: Applying migration step: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:37.070   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:37.070   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:37.070   GridField.loadLookup: (SystemStatus) [1]
01:38:37.070   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
-----------> MMigration.apply: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
-----------> MMigration.apply: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:43.543   MMigrationStep.apply: Applying migration step: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  [1]
01:38:43.543   MMigrationStep.apply: Applying migration step: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:43.676   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:43.676   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:43.676   GridField.loadLookup: (SystemStatus) [1]
01:38:43.676   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
-----------> MMigration.apply: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
-----------> MMigration.apply: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:48.721   MMigration.updateStatus: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D)  ---> Partially Applied (P) [1]
01:38:48.721   MMigration.updateStatus: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D)  ---> Partially Applied (P) [1]
01:38:48.728   MMigration.updateStatus: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D)  ---> Partially Applied (P) [1]
01:38:48.728   MMigration.updateStatus: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D)  ---> Partially Applied (P) [1]
01:38:48.728 MigrationApply.addLog: 0 - null - null - Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:48.728 MigrationApply.addLog: 0 - null - null - Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
===========> MigrationApply.process: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
org.adempiere.exceptions.AdempiereException: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found

	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:391)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
; State=72000; ErrorCode=1452
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:64)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:359)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

01:38:48.729   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:48.729   MIssue.create: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
01:38:48.729   GridField.loadLookup: (SystemStatus) [1]
01:38:48.729   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found
 [1]
org.adempiere.exceptions.AdempiereException: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 2370 - The User don't have a Unique Account Name - 3.8.0 (D) ; Step: 3600; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-01452: cannot CREATE UNIQUE INDEX; duplicate keys found

**Comment by yamelsenih** [comment]
I am testing it with a seed from beginning data
