### ISSUE TITLE
NPE when try save a value into Panel

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1252]
Error introducing in #884 

14:30:09.597 APanel.dataStatusChanged:  1/1 [17]
14:30:09.597 APanel.dataStatusChanged:  1/1 [17]
14:30:09.598 APanel.dataStatusChanged:  1/1 [17]
===========> APanel.actionPerformed: Save [17]
java.lang.NullPointerException
	at org.compiere.apps.APanel.addToRecentItems(APanel.java:1307)
	at org.compiere.apps.APanel.cmd_save(APanel.java:2061)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1747)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)

14:30:14.705 ADialog.error: Error - java.lang.NullPointerException [17]

**Comment by sramazzina** [comment]
We tried to test this issue but the description is absolutely useless for someone that is not involved directly in development of the issue's resolution but is interested in helping to test that solution works. I proposed @marcalwestf that I will find out a set of guidelines with minimum requirements in terms of rules to adhere for anyone interested in opening an issue here. In the meanwhile, please, can someone give a more detailed description of this issue so that we can proceed in testing it?

**Comment by marcalwestf** [comment]
I think it is correct to adhere to best practices, so I agree with you on this matter.

That said,is there somewhere a document where there is a description of the rules?

**Comment by e-Evolution** [comment]
@sramazzina  @marcalwestf I think that  error was catch to fly and is clear , is NPE that nos should exist , if you can see the trace log the error is launch for org.compiere.apps.APanel.addToRecentItems(APanel.java:1307)

This is for Recent Items functionality introducing from @marcalwestf  and Adaxa

**Comment by e-Evolution** [comment]
The problem was detected where and is cause for mainWindow is null , I validated that mainWindow not should be null to execute the logic.

/**
     * Add to recent items
     */
    private void addToRecentItems() {
		//	Add Recent Items
    	if (currentTab.getRecord_ID() > 0) {
        	if (currentTabIndex == 0) {
        		MRecentItem.addWindowChange(ctx, currentTab.getAD_Table_ID(),
        					currentTab.getRecord_ID(), currentTab.getAD_Window_ID(),
        					currentTab.getAD_Tab_ID());
        	} else if (mainWindow != null){
        		//	when a detail record is modified add header to recent items
        		GridTab mainTab = mainWindow.getTab(0);
        		if (mainTab != null) {
        			MRecentItem.addWindowChange(ctx, mainTab.getAD_Table_ID(),
        					mainTab.getRecord_ID(), mainTab.getAD_Window_ID(),
        					mainTab.getAD_Tab_ID());
        		}
        	}
        }
	}
