### ISSUE TITLE
Forecast simulation result - error starting search

### ISSUE THREAD

**Issue by liosc** [adempiere/adempiere#1269]
After having filled all the required fields, when you click on the "Start search" button the error message below appears:

![image](https://user-images.githubusercontent.com/23416398/28524394-97637fec-7080-11e7-9ff4-8f04335c2d44.png)

**Comment by e-Evolution** [comment]
The functionality are working from Swing , now I am try replicate in ZK

**Comment by e-Evolution** [comment]
The ZK UI laude this error 

11:33:49.713     PgConnection.setAutoCommit:   setAutoCommit = {0} (true) [632]
11:33:49.713           Trx.close: POSave_55ee25e5-426c-469d-b780-5c1ce7625cfb [632]
===========> zkoss.handleError:1130: >>java.lang.IllegalArgumentException: ColumnName=Name, AD_Language=es_MX, ID.length=1, ID=0
>>	at org.compiere.model.PO.get_Translation(PO.java:1995)
>>	at org.compiere.model.PO.get_Translation(PO.java:2033)
>>	at org.eevolution.grid.WBrowserTable.prepareTable(WBrowserTable.java:449)
>>	at org.eevolution.grid.Browser.prepareTable(Browser.java:883)
>>	at org.eevolution.grid.Browser.initBrowserTable(Browser.java:870)
>>	at org.eevolution.form.WBrowser.initBrowser(WBrowser.java:256)
>>... [632]

**Comment by sramazzina** [comment]
Victor you have the same error in SWING too

**Comment by e-Evolution** [comment]
the first error cause second error
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
12:09:09.275 VBrowser.actionPerformed: VBrowser - actionPerformed: Refresh [17]
	at java.lang.StringBuffer.<init>(StringBuffer.java:139)
12:09:09.275       Env.setContext: Context(0) currWindowNo==5 [17]
	at org.eevolution.grid.Browser.getCount(Browser.java:416)
12:09:09.275   VBrowserSearch.validateFields:  [17]
	at org.eevolution.grid.Browser.testCount(Browser.java:399)
12:09:09.275       Env.setContext: Context(0) currWindowNo==5 [17]
	at org.eevolution.form.VBrowser.executeQuery(VBrowser.java:278)
	at org.eevolution.form.VBrowser.cmd_Search(VBrowser.java:566)
	at org.eevolution.form.VBrowser.actionPerformed(VBrowser.java:719)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by sramazzina** [comment]
I really know this exception I tried to look into that problem today

**Comment by yamelsenih** [comment]
Hi, it can be caused by a column flagged as IsTranslated

I can review it after lunch

**Comment by e-Evolution** [comment]
Hi liosc, thank a lot to report , now are working.


![captura de pantalla 2017-07-24 a la s 16 47 01](https://user-images.githubusercontent.com/786968/28546304-d616de6e-708f-11e7-8a40-9466275e039d.png)

**Comment by liosc** [comment]
Thanks e-Evolution.

**Comment by sramazzina** [comment]
Wonderful Victor you are the Master & Commander 😄, thank you!
