### ISSUE TITLE
Error  CleanUpGW Update Garden World example data

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1280]
10:32:08.480 RoleAccessUpdate.addLog: 0 - null - null - Web Service Execution: - [1]
10:32:08.536   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
10:32:08.536   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
10:32:08.539   GridField.loadLookup: (ReportType) [1]
10:32:08.539   GridField.loadLookup: (ReportType) [1]
===========> CleanUpGW.setPeriods: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
 [1]
10:32:09.460   MIssue.create: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
 [1]
10:32:09.460   MIssue.create: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
 [1]
10:32:09.460   GridField.loadLookup: (SystemStatus) [1]
10:32:09.460   GridField.loadLookup: (SystemStatus) [1]
===========> CleanUpGW.setPeriods: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
 [1]
===========> CleanUpGW.process: Problem in updating periods according to new accounting values. [1]
java.sql.SQLException: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
; State=72000; ErrorCode=1407
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.process.CleanUpGW.setPeriods(CleanUpGW.java:273)
	at org.compiere.process.CleanUpGW.updatePeriods(CleanUpGW.java:167)
	at org.compiere.process.CleanUpGW.doIt(CleanUpGW.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

10:32:09.489   MIssue.create: Problem in updating periods according to new accounting values. [1]
10:32:09.489   MIssue.create: Problem in updating periods according to new accounting values. [1]
10:32:09.490   GridField.loadLookup: (SystemStatus) [1]
10:32:09.490   GridField.loadLookup: (SystemStatus) [1]
===========> CleanUpGW.process: Problem in updating periods according to new accounting values. [1]
java.sql.SQLException: ORA-01407: cannot update ("ADEMPIERE"."GL_JOURNAL"."C_PERIOD_ID") to NULL
; State=72000; ErrorCode=1407
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.process.CleanUpGW.setPeriods(CleanUpGW.java:273)
	at org.compiere.process.CleanUpGW.updatePeriods(CleanUpGW.java:167)
	at org.compiere.process.CleanUpGW.doIt(CleanUpGW.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

10:32:09.528 Trx.rollback: **** TrxRun_21df5562-0fb5-4aa4-9b68-7967bd6b26f5 [1]
10:32:09.528 Trx.rollback: **** TrxRun_21df5562-0fb5-4aa4-9b68-7967bd6b26f5 [1]
org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Problem in updating periods according to new accounting values.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:269)
	at org.eevolution.service.dsl.ProcessBuilder.executeUsingSystemRole(ProcessBuilder.java:252)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:93)

*** 2017-07-31 10:32:09.538 Adempiere Log (CLogConsole) ***

**Comment by e-Evolution** [comment]
03:27:50.817 RoleAccessUpdate.addLog: 0 - null - null - Web Service Execution: - [1]
03:27:50.968   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
03:27:50.968   MigrationLoader.main: Process=Role Access Update Error=false Summary= [1]
03:27:50.970   GridField.loadLookup: (ReportType) [1]
03:27:50.970   GridField.loadLookup: (ReportType) [1]
===========> CleanUpGW.setPeriods: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null). [1]
03:27:51.531   MIssue.create: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null). [1]
03:27:51.531   MIssue.create: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null). [1]
03:27:51.531   GridField.loadLookup: (SystemStatus) [1]
03:27:51.531   GridField.loadLookup: (SystemStatus) [1]
===========> CleanUpGW.setPeriods: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null). [1]
===========> CleanUpGW.process: Problem in updating periods according to new accounting values. [1]
org.postgresql.util.PSQLException: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null).; State=23502; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.process.CleanUpGW.setPeriods(CleanUpGW.java:273)
	at org.compiere.process.CleanUpGW.updatePeriods(CleanUpGW.java:167)
	at org.compiere.process.CleanUpGW.doIt(CleanUpGW.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

03:27:56.642   MIssue.create: Problem in updating periods according to new accounting values. [1]
03:27:56.642   MIssue.create: Problem in updating periods according to new accounting values. [1]
03:27:56.642   GridField.loadLookup: (SystemStatus) [1]
03:27:56.642   GridField.loadLookup: (SystemStatus) [1]
===========> CleanUpGW.process: Problem in updating periods according to new accounting values. [1]
org.postgresql.util.PSQLException: ERROR: null value in column "c_period_id" violates not-null constraint
  Detail: Failing row contains (50000, 11, 50001, Y, 2017-03-31 16:59:11, 100, 2017-03-31 16:59:11, 100, 101, 115, 1003, DR, CO, Y, N, trst, A, null, 108, 2017-07-31 03:27:50.981373, 2017-07-31 03:27:50.981373, null, 100, 1, 50000, 0, 0, 0, N, N, N, 114, null, null).; State=23502; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.process.CleanUpGW.setPeriods(CleanUpGW.java:273)
	at org.compiere.process.CleanUpGW.updatePeriods(CleanUpGW.java:167)
	at org.compiere.process.CleanUpGW.doIt(CleanUpGW.java:110)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

03:28:01.713 Trx.rollback: **** TrxRun_4b0a528c-2bde-48bb-bb86-986ee990c1ab [1]
03:28:01.713 Trx.rollback: **** TrxRun_4b0a528c-2bde-48bb-bb86-986ee990c1ab [1]
org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Problem in updating periods according to new accounting values.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:269)
	at org.eevolution.service.dsl.ProcessBuilder.executeUsingSystemRole(ProcessBuilder.java:252)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:93)

*** 2017-07-31 03:28:01.716 Adempiere Log (CLogConsole) ***

**Comment by yamelsenih** [comment]
Hi @e-Evolution it was caused by a select with date and time in C_Period instead a trunc for get only date without time
