### ISSUE TITLE
Financial Report throw a error when is launched

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1298]
When a financial report is launched from Garden World it return a constraint error

<pre>
===========> DB.executeUpdate: UPDATE T_Report SET Name=C_ElementValue.Value,Description=C_ElementValue.Name FROM C_ElementValue WHERE C_ElementValue.C_ElementValue_ID=T_Report.Record_ID AND T_Report.Record_ID <> 0 AND T_Report.AD_PInstance_ID=1000568 AND T_Report.PA_ReportLine_ID=119 AND T_Report.Fact_Acct_ID=0 [SvrProcess_9496c24e-f991-49f6-8928-35572daa0ec8] [172]
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block; State=25P02; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.report.FinReport.insertLineSource(FinReport.java:989)
	at org.compiere.report.FinReport.insertLineDetail(FinReport.java:804)
	at org.compiere.report.FinReport.doIt(FinReport.java:250)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.postgresql.util.PSQLException: ERROR: new row for relation "t_report" violates check constraint "t_report_accounttype_check"
  Detail: Failing row contains (1000568, A, 0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Cash, 0, 0, 11, 101, 0, 20, null, B, null, null, null).; State=23514; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.report.FinReport.lambda$0(FinReport.java:346)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.compiere.report.FinReport.insertLine(FinReport.java:324)
	at org.compiere.report.FinReport.doIt(FinReport.java:247)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
</pre>

The table definition have the follow
<pre>
CREATE TABLE adempiere.t_report
(
    ad_pinstance_id numeric(10) DEFAULT NULL::numeric,
    accounttype character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    c_validcombination_id numeric(10) DEFAULT 0,
    col_0 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_1 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_10 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_11 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_12 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_13 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_14 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_15 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_16 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_17 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_18 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_19 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_2 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_20 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_3 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_4 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_5 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_6 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_7 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_8 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    col_9 character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    description character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    fact_acct_id numeric(10),
    levelno numeric(10) DEFAULT NULL::numeric,
    name character varying(60) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    pa_reportline_id numeric(10),
    record_id numeric(10),
    seqno numeric(10) DEFAULT NULL::numeric,
    tablevel numeric(10) DEFAULT NULL::numeric,
    ax_case character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    fixedpercentage numeric,
    reportlinestyle character(1) COLLATE pg_catalog."default" DEFAULT NULL::bpchar,
    uuid character varying(36) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    CONSTRAINT t_report_reportlinestyle_check CHECK (reportlinestyle = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT t_report_ax_case_check CHECK (ax_case = ANY (ARRAY['Y'::bpchar, 'N'::bpchar])),
    CONSTRAINT t_report_accounttype_check CHECK (accounttype = ANY (ARRAY['Y'::bpchar, 'N'::bpchar]))
)
</pre>

It is a bug because the account type have a contraint **t_report_accounttype_check**

**Comment by yamelsenih** [comment]
Now it is worked:
![screenshot_20170819_123357](https://user-images.githubusercontent.com/2333092/29488538-3fd0eb92-84db-11e7-9578-95e7b47333f1.png)
