### ISSUE TITLE
Financial Report have a error with report cube

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1301]
When a financial report is launched, with cube parameter and a line is flagged as List Transaction, it return many error trying inserting in **T_Report** table, see the parameters:
![screenshot_20170819_140300](https://user-images.githubusercontent.com/2333092/29489118-2329e60e-84e7-11e7-8c8e-10aaf5309094.png)

The log is:

<pre>
===========> DB.executeUpdate: INSERT INTO T_Report (AD_PInstance_ID, PA_ReportLine_ID, Record_ID,Fact_Acct_ID,LevelNo ,Col_0,Col_1,Col_2,Col_3,Col_4,Col_5) SELECT 1000541,118,Account_ID,Fact_Acct_ID, 2 ,(SELECT SUM(acctBalance(Account_ID,AmtAcctDr,AmtAcctCr)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) <= TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ), (SELECT SUM(acctBalance(Account_ID,AmtAcctDr,AmtAcctCr)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) BETWEEN TO_TIMESTAMP('2017-01-01','YYYY-MM-DD') AND TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ), (SELECT SUM(acctBalance(Account_ID,AmtAcctDr,AmtAcctCr)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) BETWEEN TO_TIMESTAMP('2017-07-01','YYYY-MM-DD') AND TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ), (SELECT SUM(acctBalance(Account_ID,Qty,0)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) BETWEEN TO_TIMESTAMP('2017-07-01','YYYY-MM-DD') AND TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ), (SELECT SUM(acctBalance(Account_ID,AmtAcctDr,AmtAcctCr)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) BETWEEN TO_TIMESTAMP('2017-01-01','YYYY-MM-DD') AND TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ), (SELECT SUM(acctBalance(Account_ID,AmtAcctDr,AmtAcctCr)) FROM Fact_Acct_Summary fb WHERE TRUNC(DateAcct) <= TO_TIMESTAMP('2017-07-31','YYYY-MM-DD') AND PostingType='A' AND ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 AND fb.Account_ID=x.Account_ID AND fb.Fact_Acct_ID=x.Fact_Acct_ID ) FROM Fact_Acct x WHERE ( Account_ID=626 OR Account_ID=627 OR Account_ID=756 OR Account_ID=628 ) AND C_AcctSchema_ID=101 AND Account_ID IS NOT NULL AND PA_ReportCube_ID=1000000 [SvrProcess_6c36faa2-f86a-4a09-8ea4-733137ff161e] [92]
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block; State=25P02; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.report.FinReport.insertLineTrx(FinReport.java:1046)
	at org.compiere.report.FinReport.insertLineSource(FinReport.java:990)
	at org.compiere.report.FinReport.insertLineDetail(FinReport.java:797)
	at org.compiere.report.FinReport.doIt(FinReport.java:243)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.postgresql.util.PSQLException: ERROR: column fb.fact_acct_id does not exist
  Hint: Perhaps you meant to reference the column "x.fact_acct_id".
  Position: 822; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.report.FinReport.insertLineTrx(FinReport.java:1046)
	at org.compiere.report.FinReport.insertLineSource(FinReport.java:990)
	at org.compiere.report.FinReport.insertLineDetail(FinReport.java:797)
	at org.compiere.report.FinReport.doIt(FinReport.java:243)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
</pre>

The problem is that the SELECT statement make reference with **Fact_Acct_Summary.Fact_Acct_ID** instead **Fact_Acct.Fact_Acct_ID** and it not exist

**Comment by yamelsenih** [comment]
Now it is worked
