### ISSUE TITLE
ClassCastException in java2d (Bug-ID 7172749)

### ISSUE THREAD

**Issue by sramazzina** [adempiere/adempiere#1312]
While running the latest ADempiere 3.9.0 Swing client on my linux box I'm getting the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
	at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:148)
	at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:356)
	at sun.java2d.SurfaceDataProxy.updateSurfaceData(SurfaceDataProxy.java:498)
	at sun.java2d.SurfaceDataProxy.replaceData(SurfaceDataProxy.java:455)
	at sun.java2d.SurfaceData.getSourceSurfaceData(SurfaceData.java:233)
 
This prevented the SWING client to start.

My environment is as follow:
Ubuntu Desktop 16.04 LTS (kernel version 4.10.0-33)
OpenJDK 1.8.0_131

**Comment by sramazzina** [comment]
According to the following article:

https://stackoverflow.com/questions/34188495/how-can-i-work-around-the-classcastexception-in-java2d-bug-id-7172749

it seems there's a bug in Java 1.8.0 that seems to happen only to the unluckies like me. THis is because it seems to happen only with certain versions of linux operating system. In any case to solve my issue I applied the workaround suggested by opening the _RUN_Adempiere.sh_ and changing the last line from 

``
$JAVA -Xms1024m -Xmx4096m -DADEMPIERE_HOME=$ADEMPIERE_HOME $PROP $SECURE -classpath $CLASSPATH org.compiere.Adempiere
``

to 

``
$JAVA -Dsun.java2d.xrender=false -Xms1024m -Xmx4096m -DADEMPIERE_HOME=$ADEMPIERE_HOME $PROP $SECURE -classpath $CLASSPATH org.compiere.Adempiere
``

by adding a new parameter _-Dsun.java2d.xrender=false_ to the java command line.
