### ISSUE TITLE
Error trying to import employees, get an error when importing

### ISSUE THREAD

**Issue by joseramosramos** [adempiere/adempiere#1343]
I get an error when importing
DB.executeUpdate: INSERT INTO I_HR_Employee(I_HR_Employee_ID,AD_Client_ID,AD_Org_ID,Created,CreatedBy,Updated,UpdatedBy,IsActive) VALUES (1000199,1000000,0,CURRENT_TIMESTAMP,1000003,CURRENT_TIMESTAMP,1000003,'Y') [null] [46]
org.postgresql.util.PSQLException: ERROR: null value in column "startdate" violates not-null constraint
  Detail: Failing row contains (1000000, 0, null, null, null, null, null, null, null, null, 2017-09-26 19:40:29.980915, 1000003, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1000199, null, null, null, Y, N, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, N, N, null, null, null, null, null, null, null, 2017-09-26 19:40:29.980915, 1000003, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).; State=23502; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.impexp.ImpFormat.updateDB(ImpFormat.java:606)
	at org.adempiere.webui.apps.form.WFileImport.cmd_process(WFileImport.java:543)
	at org.adempiere.webui.apps.form.WFileImport.onEvent(WFileImport.java:301)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)

**Comment by erprafaelrodriguez** [comment]
Hi @joseramosramos Make sure the field datestart (fecha inicio) contain data because is mandatory in the table I_HR_Employee and the format be ddMMyyyy.

Regards
