### ISSUE TITLE
Exception in swing-client Sales Rep Dashbord

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1361]
when starting "Sales Rep Dashbord" 

![grafik](https://user-images.githubusercontent.com/3493126/31310350-230d4f54-ab97-11e7-82e7-15782079d580.png)

you will get this execption

```
===========> GridTable.open: Count SQL=SELECT COUNT(*) FROM RV_C_SalesDashboard WHERE (C_SalesDashboard.AD_User_ID=100) AND RV_C_SalesDashboard.AD_Client_ID IN(0,11) AND RV_C_SalesDashboard.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [36]
org.postgresql.util.PSQLException: FEHLER: fehlender Eintrag in FROM-Klausel für Tabelle »c_salesdashboard«
  Position: 49; State=42P01; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.model.GridTable$Loader.open(GridTable.java:3333)
	at org.compiere.model.GridTable.open(GridTable.java:605)
	at org.compiere.model.GridTab.query(GridTab.java:734)
	at org.compiere.grid.GridController.query(GridController.java:727)
	at org.compiere.apps.APanel.stateChanged(APanel.java:1528)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)


```

**Comment by homebeaver** [comment]
the reason is a missing prefix **RV_**

![grafik](https://user-images.githubusercontent.com/3493126/31310420-2daa6f36-ab98-11e7-8b87-988514c1ea13.png)
