### ISSUE TITLE
Parse Error with Context from ID

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1429]
When a SB is launched from window and exist a SQL clause with ID of current table, it throw a error parsing SQL:

<pre>
===========> VBrowser.setContextWhere: Cannot parse context= NOT EXISTS(SELECT 1 FROM AD_Process_Para pp WHERE pp.AD_Process_ID = @AD_Process_ID@ AND pp.ColumnName = Parameter.ColumnName) [14]
===========> VBrowser.getCount: SELECT COUNT(*) FROM  RV_CopyProcess_Para Parameter  WHERE  AND Parameter.CopyFromProcess=?  AND Parameter.AD_ReportView_ID=?  AND Parameter.AD_Client_ID=0 AND Parameter.AD_Org_ID=0 [14]
org.postgresql.util.PSQLException: ERROR: syntax error at or near "AND"
  Position: 58; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.grid.Browser.getCount(Browser.java:434)
	at org.eevolution.grid.Browser.testCount(Browser.java:399)
	at org.eevolution.form.VBrowser.executeQuery(VBrowser.java:278)
	at org.eevolution.form.VBrowser.init(VBrowser.java:202)
	at org.eevolution.form.VBrowser.<init>(VBrowser.java:150)
	at org.compiere.apps.APanel.actionButton(APanel.java:2684)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1723)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

===========> VBrowser.run: SELECT DISTINCT Parameter.AD_Element_ID AS PARAMETER_AD_Element_ID, Parameter.AD_Column_ID AS PARAMETER_AD_Column_ID, Parameter.ColumnName AS PARAMETER_ColumnName, Parameter.IsMandatory AS PARAMETER_IsMandatory, Parameter.AD_Reference_ID AS PARAMETER_AD_Reference_ID, Parameter.IsRange AS PARAMETER_IsRange, Parameter.DefaultValue AS PARAMETER_DefaultValue, Parameter.DefaultValue2 AS PARAMETER_DefaultValue2, Parameter.AD_ReportView_ID AS PARAMETER_AD_ReportView_ID, Parameter.AD_Process_Para_ID AS PARAMETER_AD_Process_Para_ID FROM  RV_CopyProcess_Para Parameter  WHERE  AND Parameter.CopyFromProcess=?  AND Parameter.AD_ReportView_ID=?  AND Parameter.AD_Client_ID=0 AND Parameter.AD_Org_ID=0 [52]
org.postgresql.util.PSQLException: ERROR: syntax error at or near "AND"
  Position: 571; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:616)
</pre>

**Comment by yamelsenih** [comment]
It is for process create from Parameters in Process
