### ISSUE TITLE
Smart Browse for Deposit from cash

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1446]
When a cash is for collect or payment, exist a process for make deposit from cash to bank.
Also is nice make transfer from bank to cash

**Comment by yamelsenih** [comment]
![screenshot_20171106_000729](https://user-images.githubusercontent.com/2333092/32425018-8424f9d0-c286-11e7-9245-be76d8bca6e3.png)

**Comment by yamelsenih** [comment]
Also is added some search parameter for **C_Payment** table
![screenshot_20171106_000846](https://user-images.githubusercontent.com/2333092/32425050-b91c3f54-c286-11e7-8a92-d8eaf72fc125.png)

**Comment by e-Evolution** [comment]
I got this error when try apply script

13:32:51.182   MMigrationStep.rollback: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7140; Type: AD. successfully rolled back [1]
13:32:51.182   MMigrationStep.rollback: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7140; Type: AD. successfully rolled back [1]
13:32:51.443   MMigrationStep.rollback: Rolling back migration step: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD.  [1]
13:32:51.443   MMigrationStep.rollback: Rolling back migration step: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD.  [1]
13:32:51.455   MMigrationStep.rollbackPO: Synchronizing column: MColumn[5398-C_BPartner_ID] in table: MTable[335-C_Payment] [1]
13:32:51.455   MMigrationStep.rollbackPO: Synchronizing column: MColumn[5398-C_BPartner_ID] in table: MTable[335-C_Payment] [1]
-----------> MMigrationStep.bailout: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
-----------> MMigrationStep.bailout: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
-----------> MMigration.apply: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
-----------> MMigration.apply: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
13:32:51.529   MMigration.updateStatus: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D)  ---> Partially Applied (P) [1]
13:32:51.529   MMigration.updateStatus: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D)  ---> Partially Applied (P) [1]
13:32:51.582   MMigration.updateStatus: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D)  ---> Partially Applied (P) [1]
13:32:51.582   MMigration.updateStatus: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D)  ---> Partially Applied (P) [1]
13:32:51.582 MigrationApply.addLog: 0 - null - null - Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
13:32:51.582 MigrationApply.addLog: 0 - null - null - Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
===========> MigrationApply.process: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE [1]
org.adempiere.exceptions.AdempiereException: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:289)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:286)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
caused by: org.adempiere.exceptions.AdempiereException: Migration 3310 - Smart Browse for Deposit from cash #1446 - 3.9.1 (D) ; Step: 7130; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:272)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:739)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:297)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:204)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: column "c_bpartner_id" contains null values
  Where: SQL statement "alter table c_payment alter column c_bpartner_id set not null"
PL/pgSQL function altercolumn(name,name,name,character varying,character varying) line 94 at EXECUTE
	at org.com

**Comment by yamelsenih** [comment]
Hi @e-Evolution it has not a error. The bug is from Migration appy, i will fix it in #1072

**Comment by yamelsenih** [comment]
Hi @e-Evolution please apply it for fix bug: https://github.com/adempiere/adempiere/blob/ae058e2def4bc4710ac843dd2a5ba7e4afec3f1b/migration/390lts-391/03005_1072_Fixed_Bad_FieldLength_ForColumn.xml
