### ISSUE TITLE
Commission: Partial Payments are missed when "CompletePaid" is defined and Payments are spread over different periods

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1464]
This bug applies when 
1.- a  commission is defined with  "CompletePaid" ==true , meaning that the commission is due only when the invoice has been paid wholly. 
2.- The payment was paid completely in the actual period, but the payments embraced also periods before.

In this case, the Commission Run process doesn't catch partial payments which occur in periods before the actual. As a consequence, no commission is paid for these partial payments.

Solution: enhance the Commission Run process in a way that for  commissions defined with  "CompletePaid" ==true partial payments of earlier periods are considered.

**Comment by e-Evolution** [comment]
I revert because exists more 3 observations 

1.-The incorrect dealing with line endings
https://help.github.com/articles/dealing-with-line-endings/
2.-The commit have not the urls issue in comments 
3.-The migration script fail.

**Comment by e-Evolution** [comment]
17:12:19.523   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:19.523   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:19.854   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
17:12:19.854   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.871   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.871   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.882   GridField.loadLookup: (SystemStatus) [1]
17:12:19.882   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.405   MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:12:20.405   MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:12:20.722   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
17:12:20.722   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.725   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.725   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.726   GridField.loadLookup: (SystemStatus) [1]
17:12:20.726   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.801   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.801   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.855   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.855   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.856 MigrationApply.addLog: 0 - null - null - Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.856 MigrationApply.addLog: 0 - null - null - Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
===========> MigrationApply.process: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:289)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:286)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
caused by: org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:391)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$; State=42601; ErrorCode=0
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1132)
	at org.postgresql.core.Parser.parseSql(Parser.java:1021)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:973)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:304)
	at org.postgresql.core.QueryExecutorBase.createQuery(QueryExecutorBase.java:315)
	at org.postgresql.jdbc.PgConnection.createQuery(PgConnection.java:160)
	at org.postgresql.jdbc.PgStatement.addBatch(PgStatement.java:664)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.addBatch(NewProxyStatement.java:691)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:354)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:12:20.858   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.858   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.859   GridField.loadLookup: (SystemStatus) [1]
17:12:20.859   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:289)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:286)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
caused by: org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:391)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$; State=42601; ErrorCode=0
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1132)
	at org.postgresql.core.Parser.parseSql(Parser.java:1021)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:973)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:304)
	at org.postgresql.core.QueryExecutorBase.createQuery(QueryExecutorBase.java:315)
	at org.postgresql.jdbc.PgConnection.createQuery(PgConnection.java:160)
	at org.postgresql.jdbc.PgStatement.addBatch(PgStatement.java:664)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.addBatch(NewProxyStatement.java:691)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:354)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:12:20.895 Trx.rollback: **** TrxRun_a28fb822-cd9d-4382-98cd-cc98b6bc19c0 [1]
17:12:20.895 Trx.rollback: **** TrxRun_a28fb822-cd9d-4382-98cd-cc98b6bc19c0 [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /opt/Adempiere/migration/390lts-391/03360_1465_Commission_SQLFunctionLineNetAmt.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

17:12:20.896   MIssue.create: Loading Migration from XML failed. [1]
17:12:20.896   MIssue.create: Loading Migration from XML failed. [1]
17:12:20.897   GridField.loadLookup: (SystemStatus) [1]
17:12:20.897   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /opt/Adempiere/migration/390lts-391/03360_1465_Commission_SQLFunctionLineNetAmt.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:297)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Loading Migration from XML failed.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:269)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:63)

**Comment by e-Evolution** [comment]
@SusanneCalderon , please testing the migration script before to commit,

Exist an error any function not should be set with   OWNER TO adempiere; the reason is that you can use any other user to create schema for example customer name
