### ISSUE TITLE
Commission: wrong Commission Amount calculated when Price includes Tax

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1465]
In Orders or Invoices, if the price includes the tax, the linenetamt includes the tax also.

When calculating the commission, linenetamt is taken. This is OK for orders and invoices which do not include taxes, but it is wrong in cases where tax is included in the price.

Solution: still use linenetamt, but test if price includes tax. If this is the case, subtract the tax from linenetamt to get the Commission Amount.

**Comment by yamelsenih** [comment]
Hi @marcalwestf @SusanneCalderon it return a error with is imported, see:
![screenshot_20171128_080412](https://user-images.githubusercontent.com/2333092/33318927-ebc8a936-d412-11e7-8306-d2531e2c823e.png)

<pre>
===========> MigrationFromXML.process: For input string: "3440_1465" [30]
java.lang.NumberFormatException: For input string: "3440_1465"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.compiere.model.MMigration.fromXmlNode(MMigration.java:309)
	at org.compiere.process.MigrationFromXML.lambda$0(MigrationFromXML.java:145)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
</pre>

**Comment by sbouissa** [comment]
We had the same problem so we create the 1500 issue. https://github.com/adempiere/adempiere/issues/1500

**Comment by marcalwestf** [comment]
thanks @yamelsenih  and @sbouissa I will see to it....

**Comment by marcalwestf** [comment]
@e-Evolution also suggested to get rid of 
```
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION linenetamtrealorderline(numeric)
  OWNER TO adempiere;
```
The owner should not be defined _a priori_.

**Comment by e-Evolution** [comment]
@marcalwestf other user report error with this scrip in https://github.com/adempiere/adempiere/issues/1522

Can please help to solve?
