### ISSUE TITLE
 Error On Completing The Document 

### ISSUE THREAD

**Issue by ElPrience** [adempiere/adempiere#1501]
i get this  error when completing the document 

 [81]
===========> MSequence.nextID: java.sql.SQLTimeoutException: ORA-03111: break received on communication channel
 [81]
-----------> MWFActivity.run: MWFNode[198-(DocComplete),Action=DocumentAction=CO] [81]
org.adempiere.exceptions.DBException: No DocumentNo
	at org.compiere.util.DB.getDocumentNo(DB.java:1831)
	at org.compiere.model.PO.saveNew(PO.java:2653)
	at org.compiere.model.PO.save(PO.java:2132)
	at org.compiere.model.MCash.completeIt(MCash.java:703)
	at org.compiere.process.DocumentEngine.completeIt(DocumentEngine.java:475)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:292)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:256)
	at org.compiere.model.MCash.processIt(MCash.java:432)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:890)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:778)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:370)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:280)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:280)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:795)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:370)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:280)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:280)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:795)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:502)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:696)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:726)

**Comment by yamelsenih** [comment]
Hi @AHussein12 have you many info for it?
