### ISSUE TITLE
False error when i try apply a XML

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1510]
When i try apply a step with a column that have a element referenced that not exist, it return a error:

<pre>
-----------> MColumn.load: NO Data found for AD_Column_ID=85683 [170]
-----------> M_Element.load: NO Data found for AD_Element_ID=59660 [170]
-----------> M_Element.load: NO Data found for AD_Element_ID=59660 [170]
-----------> MColumn.save: beforeSave - MColumn[85683-PercentageCompleted] [170]
java.lang.IllegalArgumentException: ColumnName is mandatory.
	at org.compiere.model.PO.set_Value(PO.java:791)
	at org.compiere.model.PO.set_Value(PO.java:740)
	at org.compiere.model.X_AD_Column.setColumnName(X_AD_Column.java:338)
	at org.compiere.model.MColumn.beforeSave(MColumn.java:366)
	at org.compiere.model.PO.save(PO.java:2134)
	at org.compiere.model.PO.saveEx(PO.java:2279)
	at org.compiere.model.PO.saveEx(PO.java:2409)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:602)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
</pre>

**Comment by yamelsenih** [comment]
But the error is that element not found
