### ISSUE TITLE
Migration script 3700 not applied 3.90lts-3.91

### ISSUE THREAD

**Issue by elmoyses** [adempiere/adempiere#1572]
https://github.com/adempiere/adempiere/blob/develop/migration/390lts-391/03700_1558_Add_PayrollReportTemplate.xml

 #1558

The migration script can not be applied. It shows the following errors:
3700

Step 710 Application failed: org.adempiere.exceptions.AdempiereException: SaveError

Step 730 Application failed: org.adempiere.exceptions.AdempiereException: Migration 3700 - Add Payroll Process Report Template #1558 - 3.9.1 (D) ; Step: 730; Type: AD. Step 730, Record 56254 was not found in table Process Parameter (285)

Step 770 Application failed: org.adempiere.exceptions.AdempiereException: Migration 3700 - Add Payroll Process Report Template #1558 - 3.9.1 (D) ; Step: 770; Type: AD. Step 770, Record 56254 was not found in table Process Parameter (285).

**Comment by yamelsenih** [comment]
Hi @e-Evolution @elmoyses i test it now and result is ok, you can see image with a DB seed 3.9:

![screenshot_20180214_012806](https://user-images.githubusercontent.com/2333092/36189035-539e027c-1126-11e8-88ac-03a13e4ac05c.png)

The error is caused by it:

<pre>
[Fatal Error] 03740_1560_Commission_from_past_months.xml:20:59: The content of elements must consist of well-formed character data or markup.
org.xml.sax.SAXParseException; systemId: file:/opt/Development/workspace/adempiere_380/migration/390lts-391/03740_1560_Commission_from_past_months.xml; lineNumber: 20; columnNumber: 59; The content of elements must consist of well-formed character data or markup.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:133)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)
</pre>

And is other issue: 03740_1560_Commission_from_past_months.xml

Best regard.
