### ISSUE TITLE
Provide an actual jar-lib for PDF decoding - jpedal.jar does not work for newer pdfs

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1577]
while working on pull req #1576 I noticed that we use a 10 years old jpedal.jar version = "3.00b21STD" from 30.01.2007! which is not able to decode newer PDF Versions, like pdf Version 1.7 and newer

So I suggest to change this with a newer one, for example this:
`icepdf-core-6.1.2.jar + icepdf-viewer-6.1.2.jar`

I have not testet it yet. But if we have an archive or attachment in pdf Version 1.7, the PDFViewerBean will fail.
Now I have some test results:

-  pdf Version 1.6 : exception , but attachment loaded and displayed
-  pdf Version 1.7 [see here](https://github.com/adempiere/adempiere/issues/1577#issuecomment-367654882) : exception , attachment cannot load and cannot be displayed, adempiere client task does not respond and has to be stopped
- pdf Version 2.0 : similar to 1.7

regards

**Comment by homebeaver** [comment]
Test with pdf Version 1.6

the scenario:

- we (GardenAdmin) have a vendor Acme , a Purchase Order and an AP Invoice
- Acme send us a Invoice in pdf Version 1.6
- we attach the pdf to the AP Invoice 
![grafik](https://user-images.githubusercontent.com/3493126/36534612-60acf3cc-17c7-11e8-9ebc-2d6774fb4cc0.png)

- while attaching we'll get exceptions from jpedal:

```
11:41:41.411 APanel.actionPerformed: Attachment - 16 [13]
11:41:41.411 APanel.cmd_attachment: Record_ID=1000023 [13]
11:41:47.880 Attachment.loadFile:  [13]
java.lang.ArrayIndexOutOfBoundsException: 32626
        at org.jpedal.fonts.tt.FontFile2.getNextUint16(Unknown Source)
        at org.jpedal.fonts.tt.TTGlyph.readSimpleGlyph(Unknown Source)
        at org.jpedal.fonts.tt.TTGlyph.readGlyph(Unknown Source)
        at org.jpedal.fonts.tt.TTGlyph.<init>(Unknown Source)
        at org.jpedal.fonts.tt.TTGlyphs.getTTGlyph(Unknown Source)
        at org.jpedal.fonts.tt.TTGlyphs.getEmbeddedGlyph(Unknown Source)
        at org.jpedal.parser.PdfStreamDecoder.processTextArray(Unknown Source)
        at org.jpedal.parser.PdfStreamDecoder.TJ(Unknown Source)
        at org.jpedal.parser.PdfStreamDecoder.processToken(Unknown Source)
        at org.jpedal.parser.PdfStreamDecoder.decodeStreamIntoObjects(Unknown Source)
        at org.jpedal.parser.PdfStreamDecoder.decodePageContent(Unknown Source)
        at org.jpedal.PdfDecoder.decodePage(Unknown Source)
        at org.adempiere.pdf.viewer.PDFViewerBean.setCurrentPage(PDFViewerBean.java:281)
        at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:467)
        at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:605)
        at org.compiere.apps.Attachment.displayData(Attachment.java:292)
        at org.compiere.apps.Attachment.actionPerformed(Attachment.java:403)
        at javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at javax.swing.JComboBox.contentsChanged(Unknown Source)
        at org.compiere.swing.CComboBox$ReducibleModel.fireContentsChanged(CComboBox.java:669)
        at org.compiere.swing.CComboBox$ReducibleModel.updateModel(CComboBox.java:918)
        at org.compiere.swing.CComboBox$ReducibleModel.contentsChanged(CComboBox.java:650)
        at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
        at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
        at javax.swing.DefaultComboBoxModel.addElement(Unknown Source)
        at org.compiere.swing.CComboBox$ReducibleModel.addElement(CComboBox.java:619)
        at javax.swing.JComboBox.addItem(Unknown Source)
        at org.compiere.apps.Attachment.loadFile(Attachment.java:458)
        at org.compiere.apps.Attachment.actionPerformed(Attachment.java:406)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at org.compiere.apps.AEnv.showWindow(AEnv.java:89)
        at org.compiere.apps.AEnv.showCenterWindow(AEnv.java:231)
        at org.compiere.apps.Attachment.<init>(Attachment.java:105)
        at org.compiere.apps.APanel.cmd_attachment(APanel.java:2277)
        at org.compiere.apps.APanel.actionPerformed(APanel.java:1764)
        at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```
- the pdf is shown in the viewer

**Comment by homebeaver** [comment]
Test with pdf Version 1.7

I take the pdf [A3xxx.pdf from here](https://github.com/adempiere/adempiere/issues/1567#issuecomment-363425564) and attach it to the customer invoice 200002

![grafik](https://user-images.githubusercontent.com/3493126/36536312-cbac9cd6-17cc-11e8-8552-be1bfaa75709.png)

- the attach fails (this **pdf Version 1.7 cannot be attached**), the exception stack:

```
12:23:26.429 APanel.cmd_attachment: Record_ID=103 [13]
12:23:28.648 Attachment.loadFile:  [13]
java.lang.NumberFormatException: For input string: ".1.1"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.jpedal.io.PdfReader.readLegacyReferenceTable(Unknown Source)
        at org.jpedal.io.PdfReader.readReferenceTable(Unknown Source)
        at org.jpedal.PdfDecoder.openPdfFile(Unknown Source)
        at org.jpedal.PdfDecoder.openPdfFile(Unknown Source)
        at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:465)
        at org.adempiere.pdf.viewer.PDFViewerBean.loadPDF(PDFViewerBean.java:605)
        at org.compiere.apps.Attachment.displayData(Attachment.java:292)
        at org.compiere.apps.Attachment.actionPerformed(Attachment.java:403)
        at javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at javax.swing.JComboBox.contentsChanged(Unknown Source)
        at org.compiere.swing.CComboBox$ReducibleModel.fireContentsChanged(CComboBox.java:669)
        at org.compiere.swing.CComboBox$ReducibleModel.updateModel(CComboBox.java:918)
        at org.compiere.swing.CComboBox$ReducibleModel.contentsChanged(CComboBox.java:650)
        at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
        at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
        at javax.swing.DefaultComboBoxModel.addElement(Unknown Source)
        at org.compiere.swing.CComboBox$ReducibleModel.addElement(CComboBox.java:619)
        at javax.swing.JComboBox.addItem(Unknown Source)
        at org.compiere.apps.Attachment.loadFile(Attachment.java:458)
        at org.compiere.apps.Attachment.actionPerformed(Attachment.java:406)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at org.compiere.apps.AEnv.showWindow(AEnv.java:89)
        at org.compiere.apps.AEnv.showCenterWindow(AEnv.java:231)
        at org.compiere.apps.Attachment.<init>(Attachment.java:105)
        at org.compiere.apps.APanel.cmd_attachment(APanel.java:2277)
        at org.compiere.apps.APanel.actionPerformed(APanel.java:1764)
        at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by homebeaver** [comment]
Test with pdf Version 2.0

You can find files to test in https://github.com/pdf-association/pdf20examples

- pdf Version 2.0 files cannot be attached , I do not attach exception logs

**Comment by homebeaver** [comment]
Tkx for merging.
