### ISSUE TITLE
Bug when trying launch search from the report viewer

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1714]
This error is caused by IsInheritFiltertoReports was introducing in 5c51177330781fcf0868f9fe5db47b47c441b1d2

00:51:01.496 MChangeLog.fillChangeLog: #77 [17]
===========> Viewer.cmd_find: SELECT Name, TableName, IsInheritFiltertoReports FROM AD_Tab_v WHERE AD_Tab_ID=?  [17]
org.postgresql.util.PSQLException: ERROR: column "isinheritfiltertoreports" does not exist
  Position: 25; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.print.Viewer.cmd_find(Viewer.java:1373)
	at org.compiere.print.Viewer.actionPerformed(Viewer.java:872)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)

**Comment by marcalwestf** [comment]
The bug was introduced in 
![20180605_viewer](https://user-images.githubusercontent.com/1789408/40974778-e139ab70-6885-11e8-843d-cda0493e2128.png)

It is solved by removing the non-existent column _IsInheritFiltertoReports_ from the select clause.
To be done soon.

@adaxa-steven thanks for the hint. As there were so many useful functional changes, this one must have been missed.
