### ISSUE TITLE
NPE when trying to display search window

### ISSUE THREAD

**Issue by Raul-mz** [adempiere/adempiere#1837]
When the view is changed to grid mode, the next record is selected and it is changed to mono view, it is not possible to search from the toolbar because of an NPE:

`CWindowToolbar.doOnClick: Could not invoke Toolbar listener method: onFind() [59]
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:393)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:357)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
caused by: java.lang.NullPointerException
	at org.adempiere.webui.component.GridTabRowRenderer.validCondition(Unknown Source)
	at org.adempiere.webui.component.GridPanel.updateCellStyle(Unknown Source)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onSave(Unknown Source)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onFind(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)`

**Comment by yamelsenih** [comment]
Resolved
