### ISSUE TITLE
cannot RUN_MigrateXML.sh : 390lts-391 - A circular Problem.

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1852]
on 13 Dec 2017  there was a [commit](https://github.com/adempiere/adempiere/commit/a510d03185c8c172155525d820bed648ba4d0b15) which changes the mandatory parameter name
from oldValue="FileName" to FilePathOrName in the migration process

Now I have a bootstrap problem ( headless setup ). I get
```
*** 2018-07-31 16:11:19.481 Adempiere Log (CLogFile) ***
16:11:19.481 Adempiere.startup: ADempiere(r) Release 3.9.0_2017-08-01 -Smart Suite ERP,CRM and SCM- (c) 1999-2017 ADempiere(r); Implementation: ${ADEMPIERE_VERSION} 20180731-0956 - ${ADEMPIERE_VENDOR} [1]
16:11:19.482 Ini.loadProperties: /home/eugen/adempiere-develop-1567/adempiere/Adempiere/Adempiere.properties #29 [1]
16:11:20.034   CLogMgt.setLevel: CONFIG [1]
16:11:20.079   GridField.loadLookup: (ReportType) [1]
16:11:20.254   MWorkflow.getDocValue: #1 [1]
16:11:20.386 Msg.initMsg: Records=1462 - en_US [1]
16:11:20.396   MIssue.create: Fill mandatory fields: File Name [1]
16:11:20.404   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Fill mandatory fields: File Name [1]
org.adempiere.exceptions.AdempiereException: Fill mandatory fields: File Name
        at org.compiere.process.SvrProcess.validateParameter(SvrProcess.java:241)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:172)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
        at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
        at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
        at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
        at org.eevolution.service.dsl.ProcessBuilder.lambda$execute$0(ProcessBuilder.java:263)
        at org.compiere.util.Trx.run(Trx.java:527)
        at org.compiere.util.Trx.run(Trx.java:495)
        at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:261)
        at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:79)
```
when I start RUN_MigrateXML.sh because the migration not applied yet and the old para-name is used.
And to apply `03560_1521_FileNameFilePathOrName.xml` which changes the para name I have to run RUN_MigrateXML !

A circular Problem.

**Comment by homebeaver** [comment]
the work aroud for me was to change the param name in the db manually

**Comment by yamelsenih** [comment]
Hi @e-Evolution please review it, it is with a change that not have old compatibility
