### ISSUE TITLE
Authenticate from LDAP fail

### ISSUE THREAD

**Issue by taherelhossin** [adempiere/adempiere#189]
When configuring Adempiere to Authenticate from LDAP everything go ok until we try to login, it always fail, the reason is the system try to get the hash for the password even if it succeeded when authenticating from LDAP, My proposed solution is as below:

```
   //Validate  password hash
     if ( passwordHash != null && passwordHash.length > 0)
     {
         AD_User_ID = new Integer (passwordHash[0].getValue());
         hash = isEncrypted ? SecureEngine.decrypt(passwordHash[0].getName()) :                    passwordHash[0].getName();
         salt = DB.getSQLValueString(null, "SELECT Salt FROM AD_User WHERE AD_User_ID=?", AD_User_ID);
     }

    if ( hash == null )
        hash = "0000000000000000";
    if ( salt == null )
        salt = "0000000000000000";  
    // if authenticated thats mean it had been authenticated from LDAP no need for further authentication
    // and to prevent null pointer exception because app_pwd in that case is null 
    if ( authenticated || MUser.authenticateHash(app_pwd, hash , salt) )
    {
        authenticated = true;
        app_pwd = null;
```

**Comment by yamelsenih** [comment]
Hi @taherelhossin i make a changes on it, you can see it on #403 
Please test it and tell me

**Comment by yamelsenih** [comment]
I close it, the change is done. If exist a bug please tell us about it.

Best Regard

**Comment by naalaka** [comment]
Hi, I used the followings to setup the adempiere
Java 1.7 + Adempiere 3.8 + Postgresql 9.3 (With existing DB).
Configuration is done & can be connected to the adempiere through the web port (8080). 

When entering an existing username & a password its showing the below message.
>>The program assumes Database version 2015-03-01, but Database has Version 2011-09-01.
>>This is likely to cause hard to fix errors.
>>Please stop and migrate the database immediately.
>>      at org.adempiere.webui.panel.LoginPanel.validateLogin(LoginPanel.java:456)
>>... [62]
13:35:08,096 ERROR [STDERR] ===========> zkoss.handleError:1130: >>org.adempiere.webui.exception.ApplicationException: Database Version Error
>>
>>The program assumes Database version 2015-03-01, but Database has Version 2011-09-01.
>>This is likely to cause hard to fix errors.
>>Please stop and migrate the database immediately.
>>      at org.adempiere.webui.panel.LoginPanel.validateLogin(LoginPanel.java:456)
>>... [62]
13:35:08,424 ERROR [STDERR] ===========> Doc_MatchInv.post: Resubmit - Cannot lock M_MatchInv_ID=1081798, Force=false,RePost=false [43]
13:35:09,346 ERROR [STDERR] ===========> Doc_MatchInv.post: Resubmit - Cannot lock M_MatchInv_ID=1081798, Force=false,RePost=false [43]
13:35:11,111 ERROR [STDERR] ===========> Doc_InOut.post: Resubmit - Cannot lock M_InOut_ID=1357897, Force=false,RePost=false [43]
13:35:12,064 ERROR [STDERR] ===========> Doc_InOut.post: Resubmit - Cannot lock M_InOut_ID=1357897, Force=false,RePost=false [43]
13:35:14,127 ERROR [STDERR] ===========> Doc_Invoice.post: Resubmit - Cannot lock C_Invoice_ID=1856490, Force=false,RePost=false [43]
13:35:15,002 ERROR [STDERR] ===========> Doc_Invoice.post: Resubmit - Cannot lock C_Invoice_ID=1856490, Force=false,RePost=false [43]
13:35:16,502 ERROR [STDERR] ===========> Doc_Invoice.post: Resubmit - Cannot lock C_Invoice_ID=1858118, Force=false,RePost=false [43]
13:35:17,408 ERROR [STDERR] ===========> Doc_Invoice.post: Resubmit - Cannot lock C_Invoice_ID=1858118, Force=false,RePost=false [43]
13:35:18,502 ERROR [STDERR] ===========> DB.getSQLValueString: SELECT Salt FROM AD_User WHERE AD_User_ID=? [63]
org.postgresql.util.PSQLException: ERROR: column "salt" does not exist
  Position: 8; State=42703; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy68.executeQuery(Unknown Source)
        at org.compiere.util.DB.getSQLValueStringEx(DB.java:1356)
        at org.compiere.util.DB.getSQLValueString(DB.java:1399)
        at org.compiere.util.DB.getSQLValueString(DB.java:2129)
        at org.compiere.util.Login.getRoles(Login.java:290)
        at org.compiere.util.Login.getRoles(Login.java:221)
        at org.adempiere.webui.panel.RolePanel.updateClientList(RolePanel.java:320)
        at org.adempiere.webui.panel.RolePanel.onEvent(RolePanel.java:389)
        at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
        at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
13:35:19,814 ERROR [STDERR] ===========> DB.getSQLValueString: SELECT Salt FROM AD_User WHERE AD_User_ID=? [63]
org.postgresql.util.PSQLException: ERROR: column "salt" does not exist
  Position: 8; State=42703; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy68.executeQuery(Unknown Source)
        at org.compiere.util.DB.getSQLValueStringEx(DB.java:1356)
        at org.compiere.util.DB.getSQLValueString(DB.java:1399)
        at org.compiere.util.DB.getSQLValueString(DB.java:2129)
        at org.compiere.util.Login.getRoles(Login.java:290)
        at org.compiere.util.Login.getRoles(Login.java:221)
        at org.adempiere.webui.panel.RolePanel.updateClientList(RolePanel.java:320)
        at org.adempiere.webui.panel.RolePanel.onEvent(RolePanel.java:389)
        at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
        at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
13:35:20,314 ERROR [STDERR] ===========> Doc_InOut.post: Resubmit - Cannot lock M_InOut_ID=1360795, Force=false,RePost=false [43]

Please help ....
