### ISSUE TITLE
Migration 3605 Step 890 fails but shows applied.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#1925]
Develop branch.  Ref #1532.  Migration 3605 step 890 fails (trace below) but the step status shows "Applied".  Clicking the record ID button open the Table/Column window with a null record.

The record adds a translation for "RequestProcessor" with AD_Column_ID=86204.  Likely the column was deleted but the translation wasn't.

A couple of questions I haven't taken the time to look at
- I though translations weren't included/captured in migration scripts?
- If a migration steps fails, shouldn't the step fail and the migration process stop?

Quick solution - delete the step.

08:00:41.142   MMigrationStep.apply: Applying migration step: Migration 3605 - Project Processor Window #1532 - 3.9.1 (D) ; Step: 890; Type: AD.  [1]
08:00:41.636 MTable.getPO: Using GenericPO for AD_Column_Trl [1]
-----------> GenericPO.set_ValueNoCheck: AD_Language - Class invalid: class java.lang.Integer, Should be class java.lang.String: 0 [1]
08:00:41.762   MIssue.create: POSave_4bc3afb4-706b-463a-8f8f-acd76d14b61a [1]
08:00:41.919   GridField.loadLookup: (SystemStatus) [1]
===========> Trx.commit: POSave_4bc3afb4-706b-463a-8f8f-acd76d14b61a [1]
org.postgresql.util.PSQLException: ERROR: insert or update on table "ad_column_trl" violates foreign key constraint "adcolumn_adcolumntrl"
  Detail: Key (ad_column_id)=(86204) is not present in table "ad_column".; State=23503; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:739)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:760)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:803)
	at org.compiere.util.Trx.commit(Trx.java:336)
	at org.compiere.util.Trx.commit(Trx.java:364)
	at org.compiere.model.PO.save(PO.java:2199)
	at org.compiere.model.PO.save(PO.java:2391)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:600)

**Comment by marcalwestf** [comment]
hi @mckayERP 

> I thought translations weren't included/captured in migration scripts?

They have been always included.

If for example you log in with your language, select a window to show, but a field translation is missing, the window display may fail altogether and you may end up having no clue why.

**Comment by yamelsenih** [comment]
Resolved
