### ISSUE TITLE
Default role for the System account should be System Administrator

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#1935]
The default role is "Role Template" - or at least that is what appears in the Role combo box on login.  This is confusing for new users.  The Role Template is a special case and the user needs some expertise to use it.

**Comment by mckayERP** [comment]
User roles in the login combo are sorted by name with the selected role being the role of the last login (if that was the same user: this is saved in the properties file).  If the user did not log in previously (or a different user was logged in) the role displayed is the first in the list.

I've added a IsDefault field to the AD_User_Roles table and use it during login to sort the roles so that the default will be first and the rest of the list will be sorted by name.  The displayed role will still be determined by the property file if a role exists there.

**Comment by marekmosiewicz** [comment]
It would be better to add sequence to AD_Org to sort as you wish not only default

**Comment by yamelsenih** [comment]
When a client try login, it throw a error:

<pre>
===========> Login.getRoles: SELECT u.AD_User_ID, r.AD_Role_ID,r.Name, u.ConnectionProfile FROM AD_User u INNER JOIN AD_User_Roles ur ON (u.AD_User_ID=ur.AD_User_ID AND ur.IsActive='Y') INNER JOIN AD_Role r ON (ur.AD_Role_ID=r.AD_Role_ID AND r.IsActive='Y') WHERE u.AD_User_ID = ? AND u.IsActive='Y' AND EXISTS (SELECT 1 FROM AD_Client c WHERE u.AD_Client_ID=c.AD_Client_ID AND c.IsActive='Y') ORDER BY COALESCE(ur.IsDefault,'N') Desc, r.Name [15]
org.postgresql.util.PSQLException: ERROR: column ur.isdefault does not exist
  Position: 385; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.compiere.util.Login.getRoles(Login.java:362)
	at org.compiere.util.Login.getRoles(Login.java:225)
	at org.compiere.apps.ALogin.tryConnection(ALogin.java:650)
	at org.compiere.apps.ALogin.connectionOK(ALogin.java:521)
	at org.compiere.apps.ALogin.actionPerformed(ALogin.java:468)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)

===========> Login.saveError: DBLogin - ERROR: column ur.isdefault does not exist
  Position: 385 [15]
</pre>

I think that this problem can be resolved with some like this: https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/util/Login.java#L263
<pre>
		boolean loginWithValue = M_Element.get(Env.getCtx(), I_AD_User.COLUMNNAME_IsLoginUser) != null;
		String userLogin = "Name";
		if(loginWithValue) {
			userLogin = "Value";
		}
</pre>

Is nice if you can allows back compatibility

**Comment by mckayERP** [comment]
That error shows that the IsDefault column hasn't been added to the AD_UserRoles table in the database.  

Its referenced here: https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/util/Login.java#L354 and needs to exist in the database.

Check that the migration scripts were applied successfully.  Specifically 04020_1935_AddDefaultFlagtoAD_User_Roles.xml and 04021_1935_AddDefaultFlagtoAD_User_Roles.xml

It is working in the client for me.  Please check and let me know.

**Comment by yamelsenih** [comment]
Hi @mckayERP i understant it. The problem is that if you want to make login for apply XML is impossible, i will to write a patch for it
