### ISSUE TITLE
IndexOutOfBoundsException in CTabbedPane

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#1955]
when starting with a fresh DB, I get sometimes this exception:
```
java.lang.IndexOutOfBoundsException: Index: 1, Tab count: 1
	at javax.swing.JTabbedPane.checkIndex(JTabbedPane.java:1768)
	at javax.swing.JTabbedPane.setMnemonicAt(JTabbedPane.java:1663)
	at org.compiere.swing.CTabbedPane.insertTab(CTabbedPane.java:217)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:767)
	at org.compiere.grid.VTabbedPane.addTab(VTabbedPane.java:96)
	at org.compiere.apps.APanel.initPanel(APanel.java:879)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:134)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:120)
	at org.compiere.apps.AMenuStartItem.startWindow(AMenuStartItem.java:242)
	at org.compiere.apps.AMenuStartItem.startOption(AMenuStartItem.java:183)
	at org.compiere.apps.AMenuStartItem.run(AMenuStartItem.java:141)
```
It's not easy to reproduce.

**Comment by marekmosiewicz** [comment]
I'm trying to reproduce your error and I found other bug as follows:
Setting Display logic in Business Partner window/Business parnter tab to @DUNS@='A' gives following error:
java.lang.NullPointerException
	at org.compiere.apps.APanel.initPanel(APanel.java:905)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:129)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:115)
	at org.compiere.apps.AMenuStartItem.startWindow(AMenuStartItem.java:237)
	at org.compiere.apps.AMenuStartItem.startOption(AMenuStartItem.java:178)
	at org.compiere.apps.AMenuStartItem.run(AMenuStartItem.java:138)

**Comment by homebeaver** [comment]
Hi @marekmosiewicz - tkx for reproducing. I think the error is here (217):

```java
setMnemonicAt(index, '1'+index);
//should be
setMnemonicAt(index, Integer.valueOf(1+index).toString());
// and two lines below change to
setMnemonicAt(index, "0");
```
Explanation: the local method is `public boolean setMnemonicAt (int index, String text)`
but there is `public void setMnemonicAt(int tabIndex, int mnemonic) ` in javax.swing.JTabbedPane
which is called in (217) because of `'1'+index`

**Comment by marcalwestf** [comment]
Hi Eugen,
I understand your explanations and they seem reasonable.
On the other hand, the class CTabbedPane hasn't been changed for 9 years!
See image
![20181001_ctabbedpane_01](https://user-images.githubusercontent.com/1789408/46320026-a133e100-c599-11e8-9458-426e1098b8a8.png)

This can also mean, the error has been that long unrecognized.

I logged in/out, tested several windows, and info forms. All went through **CTabbedPane.setMnemonicAt (int index, String text)** and worked well.

So from my part it would be OK.
But I'd rather like that other people have a closer look at it, mostly because possible, undesired side-effects which I haven't tested and may pop up when unexpected.

I wonder if you would recommend a deterministic way of testing in order to accept this PR?

**Comment by yamelsenih** [comment]
Here a simple for with test data:

<pre>
System.out.println("Previous");
		for(int index = 0; index <= 9; index++) {
			System.out.println('1' + (index < 9? index: 0));
			
		}
		System.out.println("New Method");
		for(int index = 0; index <= 9; index++) {
			System.out.println(Integer.valueOf(1+(index < 9? index: 0)).toString());
		}
</pre>

**Result**
<pre>
Previous
49
50
51
52
53
54
55
56
57
49
New Method
1
2
3
4
5
6
7
8
9
1
</pre>
