### ISSUE TITLE
Export migration to XML not work

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1998]
Currently with the last version, i want to export to XML a migration, but it is not possible because **FilePath** parameter not exist. Also a error is showed:

<pre>
===========> MigrationToXML.process: java.lang.NullPointerException [181]
java.lang.NullPointerException
	at java.io.FileOutputStream.<init>(FileOutputStream.java:203)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at org.compiere.process.MigrationToXML.doIt(MigrationToXML.java:73)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)

</pre>

**Comment by mckayERP** [comment]
Hi Yamel,

Which branch, version are you using?  There was a previous change to the filename parameter that caused an error.  To get around it, you had to manually change the parameter name in the database to match the software.  This was fixed as part of #1926. 

The stack track shows the filewriter invoked at line 73 of MigrationToXML.java.  This was changed in pull-request #1940 which incorporated #1926 into the develop branch.   This make me suspect your using a different branch.  Can you confirm?

Mike

**Comment by yamelsenih** [comment]
Hi @mckayERP let me verify version

**Comment by e-Evolution** [comment]
@mckayERP the error that your report was solve in #1852 include into develop in commit 06b81dcd7f63130f616f13e19c5ecbcf7242a9d1
