### ISSUE TITLE
Clicking Export in WBrowser (eg. Payment Selection) causes ClassNotFoundException

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2002]
In ZK, GardenWorld, open Generate Payment Selection browser, click search.  Then click on export button.  Error appears and trace shows:

===========> zkoss.handleError:1130: >>java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
>>java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
>>	at org.eevolution.grid.Browser.exportXLS(Browser.java:1502)
>>	at org.eevolution.form.WBrowser.cmd_Export(WBrowser.java:758)
>>	at org.eevolution.form.WBrowser.access$3(WBrowser.java:754)
>>	at org.eevolution.form.WBrowser$4.onEvent(WBrowser.java:479)

**Comment by mckayERP** [comment]
Seems the problem is related to the setup of Eclipse and the Web Deployment Assembly in the project properties.  A number of libraries in tools/lib need to be added to the web deployment assembly list. Then the export button functions as expected.

The required additions to .settings/org.eclipse.wst.common.component are

        <dependent-module archiveName="poi-3.17.jar" deploy-path="/WEB-INF/lib" handle="module:/classpath/lib/adempiere/tools/lib/poi-3.17.jar">
            <dependency-type>uses</dependency-type>
        </dependent-module>
        <dependent-module archiveName="poi-ooxml-3.17.jar" deploy-path="/WEB-INF/lib" handle="module:/classpath/lib/adempiere/tools/lib/poi-ooxml-3.17.jar">
            <dependency-type>uses</dependency-type>
        </dependent-module>
        <dependent-module archiveName="commons-collections4-4.1.jar" deploy-path="/WEB-INF/lib" handle="module:/classpath/lib/adempiere/tools/lib/commons-collections4-4.1.jar">
            <dependency-type>uses</dependency-type>
        </dependent-module>

**Comment by yamelsenih** [comment]
Hi @mckayERP are resolved this issue?
