### ISSUE TITLE
ZoomAcross for BP produces invalid sql

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#2153]
hi, 
I get this exception when pushing ZoomAcross button

```
09:13:52.999 APanel.cmd_zoomAcross: ID=4003 [16]
09:13:53.015   AZoomAcross.<init>: PO=MBPartner[ID=4003,Value=10002,Name=MSA Technologies and Enterprise Services GmbH,Open=146.370], WindowID=291 [16]
09:13:53.015   ZoomInfoFactory.retrieveZoomInfos: PO=MBPartner[ID=4003,Value=10002,Name=MSA Technologies and Enterprise Services GmbH,Open=146.370] - AD_Window_ID=291 [16]
09:13:53.234 MRelationType.retrieveTypes: There are 2 matching types for MBPartner[ID=4003,Value=10002,Name=MSA Technologies and Enterprise Services GmbH,Open=146.370] [16]
09:13:54.577   MIssue.create: SELECT COUNT(*) FROM M_Production WHERE (C_BPartner_ID=4003) [16]
09:13:54.597   GridField.loadLookup: (SystemStatus) [16]
09:13:54.987 MChangeLog.fillChangeLog: #75 [16]
===========> DB.getSQLValue: SELECT COUNT(*) FROM M_Production WHERE (C_BPartner_ID=4003) [16]
org.postgresql.util.PSQLException: FEHLER: Spalte »c_bpartner_id« existiert nicht
  Position: 42; State=42703; ErrorCode=0
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
    at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
    at org.compiere.util.DB.getSQLValueEx(DB.java:1295)
    at org.compiere.util.DB.getSQLValue(DB.java:1338)
    at org.compiere.util.DB.getSQLValue(DB.java:2179)
    at org.adempiere.model.GenericZoomProvider.evaluateQuery(GenericZoomProvider.java:122)
    at org.adempiere.model.GenericZoomProvider.retrieveZoomInfos(GenericZoomProvider.java:85)
    at org.adempiere.model.ZoomInfoFactory.retrieveZoomInfos(ZoomInfoFactory.java:105)
    at org.compiere.apps.AZoomAcross.mkZoomTargets(AZoomAcross.java:96)
    at org.compiere.apps.AZoomAcross.<init>(AZoomAcross.java:65)
    at org.compiere.apps.AZoomAcross.<init>(AZoomAcross.java:58)
    at org.compiere.apps.APanel.cmd_zoomAcross(APanel.java:2178)
    at org.compiere.apps.APanel.actionPerformed(APanel.java:1831)
    at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
```

an AD_Issue entry is created for the invalid sql 

`SELECT COUNT(*) FROM M_Production WHERE (C_BPartner_ID=<any>)`

and the user gets the info that the are -1 Produktion records for the BP which doesn't make sense:

![grafik](https://user-images.githubusercontent.com/3493126/49079752-c3687900-f241-11e8-8681-5b9f2ef29b74.png)

Found in Release 3.9 swing - same in web-UI
regards

**Comment by homebeaver** [comment]
A first glimpse to the code founds a HardCoded SQL-stmt. 

```java
public class GenericZoomProvider implements IZoomProvider {

    private static final CLogger logger = CLogger
            .getCLogger(GenericZoomProvider.class);

    public List<ZoomInfoFactory.ZoomInfo> retrieveZoomInfos(PO po) {

        String sql = "SELECT DISTINCT ws.AD_Window_ID, ws.Name, wp.AD_Window_ID, wp.Name, t.TableName, tts.AD_Tab_ID, ttp.AD_Tab_ID " 
                + "FROM AD_Table t ";
        boolean baseLanguage = Env.isBaseLanguage(Env.getCtx(), "AD_Window");
        if (baseLanguage)
            sql += "INNER JOIN AD_Window ws ON (t.AD_Window_ID=ws.AD_Window_ID)" 
                    + " LEFT OUTER JOIN AD_Window wp ON (t.PO_Window_ID=wp.AD_Window_ID) ";
        else
            sql += "INNER JOIN AD_Window_Trl ws ON (t.AD_Window_ID=ws.AD_Window_ID AND ws.AD_Language=?)" 
                    + " LEFT OUTER JOIN AD_Window_Trl wp ON (t.PO_Window_ID=wp.AD_Window_ID AND wp.AD_Language=?) ";
        // WARNING - HardCoded: first tab must have SeqNo = 10
        sql += "JOIN AD_Tab tts ON (tts.AD_Window_ID=ws.AD_Window_ID AND tts.AD_Table_ID=t.AD_Table_ID AND tts.SeqNo=10)" // first tab so
                +" LEFT OUTER JOIN AD_Tab ttp ON (ttp.AD_Window_ID=wp.AD_Window_ID AND ttp.AD_Table_ID=t.AD_Table_ID AND ttp.SeqNo=10)" // first tab po
                +" WHERE t.TableName NOT LIKE 'I%'" // No Import
                + " AND t.AD_Table_ID IN " 
                + "(SELECT AD_Table_ID FROM AD_Column " 
                + "WHERE ColumnName=? AND IsKey='N' AND IsParent='N') " // #x
                + "ORDER BY 2";
```

The result of this leads to the semantic wrong `count(*)` select

**Comment by yamelsenih** [comment]
Hi @homebeaver this bug is because exists a column named **C_BPartner_ID** inside **M_Production** table as Column SQL
![screenshot_20181127_111637](https://user-images.githubusercontent.com/2333092/49091442-44217800-f236-11e8-8a20-c027187e0b4d.png)

**Comment by yamelsenih** [comment]
I add a pull request for it: https://github.com/adempiere/adempiere/pull/2157

Thanks @homebeaver
