### ISSUE TITLE
Bug fix error the cost generate SQL syntax's 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#219]

**Comment by e-Evolution** [comment]
===========> Query.first: SELECT AD_Client_ID,AD_Org_ID,C_AcctSchema_ID,(SELECT COALESCE(CostingMethod, 'x') FROM M_CostType ct WHERE M_Cost.M_CostType_ID=ct.M_CostType_ID) AS CostingMethod,Created,CreatedBy,CumulatedAmt,CumulatedAmtLL,CumulatedQty,CurrentCostPrice,CurrentCostPriceLL,CurrentQty,Description,FutureCostPrice,FutureCostPriceLL,IsActive,IsCostFrozen,M_AttributeSetInstance_ID,M_CostElement_ID,M_CostType_ID,M_Product_ID,M_Warehouse_ID,Percent,'N' AS Processed,Updated,UpdatedBy FROM M_Cost WHERE (C_AcctSchema_ID=? AND M_Product_ID=? AND M_CostType_ID=? AND M_CostElement_ID=?  AND (AD_Org_ID=?  AND M_Warehouse_ID=? ) AND AD_Client_ID=? [380]
org.postgresql.util.PSQLException: ERROR: error de sintaxis al final de la entrada
  Position: 631; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
