### ISSUE TITLE
Problem open window to show unprocessed items

### ISSUE THREAD

**Issue by jdaison** [adempiere/adempiere#2251]
![image](https://user-images.githubusercontent.com/6097506/51076169-fedccc80-1662-11e9-8b57-0d315bd28ed1.png)
See this code
![image](https://user-images.githubusercontent.com/6097506/51076216-80ccf580-1663-11e9-923b-b23acf8cb677.png)

**Comment by yamelsenih** [comment]
Hi @jdaison have you a Step by Step for replicate it? What is the window?

**Comment by jdaison** [comment]
Hi @yamelsenih this happens when I open any window like invoice customer, and you can see the message of other errors y trace logs of ADempiere server monitor in the URL HTTP://{adempiere_host_ip}/admin/adempiereMonitor
I am using PostgreSQL 9.5.4 
If you need anything else let me know.
Thanks!

**Comment by yamelsenih** [comment]
I look the same bug with dashboard:

<pre>
===========> DB.getSQLValueBD: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [49]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Where: PL/pgSQL function paymenttermduedate(numeric,timestamp with time zone) line 41 at assignment; State=42883; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
	at org.compiere.util.DB.getSQLValueBDEx(DB.java:1457)
	at org.compiere.util.DB.getSQLValueBD(DB.java:1501)
	at org.compiere.model.MMeasure.updateCalculatedGoals(MMeasure.java:473)
	at org.compiere.model.MMeasure.updateGoals(MMeasure.java:360)
	at org.compiere.model.MGoal.updateGoal(MGoal.java:379)
	at org.compiere.model.MGoal.getUserGoals(MGoal.java:84)
	at org.adempiere.webui.apps.graph.WPAPanel.get(WPAPanel.java:28)
	at org.adempiere.webui.dashboard.DPPerformance.<init>(DPPerformance.java:34)

===========> DB.getSQLValueBD: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [49]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Where: PL/pgSQL function paymenttermduedate(numeric,timestamp with time zone) line 41 at assignment; State=42883; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
	at org.compiere.util.DB.getSQLValueBDEx(DB.java:1457)
	at org.compiere.util.DB.getSQLValueBD(DB.java:1501)
	at org.compiere.model.MMeasure.updateCalculatedGoals(MMeasure.java:473)
	at org.compiere.model.MMeasure.updateGoals(MMeasure.java:360)
	at org.compiere.model.MGoal.updateGoal(MGoal.java:379)
	at org.compiere.model.MGoal.getUserGoals(MGoal.java:84)
	at org.adempiere.webui.apps.graph.WPAPanel.get(WPAPanel.java:28)
	at org.adempiere.webui.dashboard.DPPerformance.<init>(DPPerformance.java:34)
</prer>

**Comment by jdaison** [comment]
@yamelsenih we had to see that after the migration process operations between date and integer like
dateinvoiced + netdays is trowing this error, I don't understand why. The unique difference to the old database is that we execute this command CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; 

if you change the operation like this:
dateinvoiced + interval '1' day * netdays

The operation is useful

**Comment by e-Evolution** [comment]
Hi @jdaison 
The problem is that in some moment the seed for ADempiere 391 remove the operators

To solve this issue apply this script https://github.com/adempiere/adempiere/blob/develop/db/ddlutils/postgresql/operators.sql

> --DROP OPERATOR + (timestamptz, NUMERIC);
> CREATE OPERATOR + ( PROCEDURE = adddays,
> LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
> COMMUTATOR = +);

> --DROP OPERATOR - (timestamptz, NUMERIC);
> CREATE OPERATOR - ( PROCEDURE = subtractdays,
> LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
> COMMUTATOR = -);

**Comment by jdaison** [comment]
thanks, Victor I tested and now is working perfectly!!
