### ISSUE TITLE
bug PSQLException when adding missing translations (lang maintain)

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#2270]
I add a new system language `de_DE` and start add missing translations:

![grafik](https://user-images.githubusercontent.com/3493126/51554580-e4ca9780-1e75-11e9-9ffe-ee560935d53f.png)

this results in a PSQLException: 

```
10:04:17.772   MIssue.create: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(60) [34]
10:04:17.776   GridField.loadLookup: (SystemStatus) [34]
===========> LanguageMaintenance.process: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(60) [34]
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(60); State=22001; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1120)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1093)
	at org.compiere.model.MLanguage.addTable(MLanguage.java:450)
	at org.compiere.model.MLanguage.maintain(MLanguage.java:356)
	at org.compiere.install.LanguageMaintenance.doIt(LanguageMaintenance.java:97)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)

```

**Comment by homebeaver** [comment]
the errornous stmt is

```
10:04:17.755   MLanguage.addTable: 
INSERT INTO AD_Browse_Trl(AD_Language,IsTranslated, AD_Client_ID,AD_Org_ID, Created,Updated
        , Createdby,UpdatedBy, AD_Browse_ID,Description,Help,Name) 
SELECT 'de_DE','N', AD_Client_ID,AD_Org_ID, SYSDATE, SYSDATE ,100,100, AD_Browse_ID,Description,Help,Name 
  FROM AD_Browse 
 WHERE AD_Browse_ID NOT IN (SELECT AD_Browse_ID FROM AD_Browse_Trl WHERE AD_Language='de_DE')
 [34]
```
`AD_Browse_Trl.Name` has length 60
and 
`AD_Browse.Name` has length 120
**This leads to PSQLException!**

regards
