### ISSUE TITLE
Error in postgreSQL function after migrating to 391

### ISSUE THREAD

**Issue by nsarlabos** [adempiere/adempiere#2306]
It is observed that after migrating to 391 there are problems when executing certain reports or functionalities of the system.

This is due to an error when executing the function 'paymenttermduedate (numeric, timestamp with time zone)', which throws the following Postgres message:

**"ERROR: the operator does not exist: timestamp with time zone + numeric
LINE 1: SELECT TRUNC (DocDate) + p.NetDays
                                ^
TIP: No operator matches the given name and argument types. You might need to add explicit type casts.
INQUIRY: SELECT TRUNC (DocDate) + p.NetDays
CONTEXT: PL / pgSQL function paymenttermduedate (numeric, timestamp with time zone) on line 41 in assignment "**

Our solution would be to modify the aforementioned function, in the ELSE part, as follows:

**"DueDate: = (TRUNC (DocDate) + (p.NetDays || 'days') :: interval) :: timestamp without time zone;"**

**Comment by yamelsenih** [comment]
Hi everyone, this issue is related to #2251

**Comment by yamelsenih** [comment]
I look the same bug with dashboard:

<pre>
===========> DB.getSQLValueBD: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [49]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Where: PL/pgSQL function paymenttermduedate(numeric,timestamp with time zone) line 41 at assignment; State=42883; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
	at org.compiere.util.DB.getSQLValueBDEx(DB.java:1457)
	at org.compiere.util.DB.getSQLValueBD(DB.java:1501)
	at org.compiere.model.MMeasure.updateCalculatedGoals(MMeasure.java:473)
	at org.compiere.model.MMeasure.updateGoals(MMeasure.java:360)
	at org.compiere.model.MGoal.updateGoal(MGoal.java:379)
	at org.compiere.model.MGoal.getUserGoals(MGoal.java:84)
	at org.adempiere.webui.apps.graph.WPAPanel.get(WPAPanel.java:28)
	at org.adempiere.webui.dashboard.DPPerformance.<init>(DPPerformance.java:34)

===========> DB.getSQLValueBD: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) [49]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp with time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Where: PL/pgSQL function paymenttermduedate(numeric,timestamp with time zone) line 41 at assignment; State=42883; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
	at org.compiere.util.DB.getSQLValueBDEx(DB.java:1457)
	at org.compiere.util.DB.getSQLValueBD(DB.java:1501)
	at org.compiere.model.MMeasure.updateCalculatedGoals(MMeasure.java:473)
	at org.compiere.model.MMeasure.updateGoals(MMeasure.java:360)
	at org.compiere.model.MGoal.updateGoal(MGoal.java:379)
	at org.compiere.model.MGoal.getUserGoals(MGoal.java:84)
	at org.adempiere.webui.apps.graph.WPAPanel.get(WPAPanel.java:28)
	at org.adempiere.webui.dashboard.DPPerformance.<init>(DPPerformance.java:34)
</prer>

**Comment by e-Evolution** [comment]
Hi @nsarlabos , @yamelsenih 

The problem is that in some moment the seed for ADempiere 391 remove the operators 

To solve this issue apply this script https://github.com/adempiere/adempiere/blob/develop/db/ddlutils/postgresql/operators.sql

> --DROP OPERATOR + (timestamptz, NUMERIC);
CREATE OPERATOR + ( PROCEDURE = adddays,
LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
COMMUTATOR = +);

>--DROP OPERATOR - (timestamptz, NUMERIC);
CREATE OPERATOR - ( PROCEDURE = subtractdays,
LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
COMMUTATOR = -);

**Comment by mckayERP** [comment]
@e-Evolution 

Hi Victor, why did this get reverted?  The error exists with new release 3.9.2.

Mike

**Comment by ppenalo** [comment]
Buenos dias, soy un amante de Adempiere, estoy realizando realizando pruebas para la nueva version, pero he encontrado un pequeño error en la instalación, puede ayudarme, he realiza las pruebas que recomienda pero aun persiste:
===========> MMeasure.getGraphColumnList: SELECT COALESCE(SUM(currencyBase(invoiceOpen(C_Invoice_ID, C_InvoicePaySchedule_ID),C_Currency_ID, DateAcct, AD_Client_ID, AD_Org_ID)),0)
,TRUNC(DateInvoiced,'MM') FROM C_Invoice_v C_Invoice WHERE IsSOTrx='Y' AND Processed='Y' AND C_Invoice.AD_Client_ID IN(0,11) AND C_Invoice.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) GROUP BY TRUNC(DateInvoiced,'MM')  ORDER BY TRUNC(DateInvoiced,'MM')  [1]
org.postgresql.util.PSQLException: ERROR: el operador no existe: timestamp with time zone + numeric
  Hint: Ning·n operador coincide con el nombre y el tipo de los argumentos. Puede ser necesario agregar conversiones explÝcitas de tipos.
  Where: funci¾n PL/pgSQL paymenttermduedate(numeric,timestamp with time zone) en la lÝnea 41 en asignaci¾n; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)

**RECOMENDACIONES  A EJECUTAR.
--DROP OPERATOR + (timestamptz, NUMERIC);
CREATE OPERATOR + ( PROCEDURE = adempiere.adddays,
LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
COMMUTATOR = +);

--DROP OPERATOR - (timestamptz, NUMERIC);
CREATE OPERATOR - ( PROCEDURE = adempiere.subtractdays,
LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
COMMUTATOR = -);**

**Comment by ppenalo** [comment]
> Hola @nsarlabos , @yamelsenih
> 
> El problema es que en algún momento la semilla para ADempiere 391 elimina los operadores
> 
> Para resolver este problema, aplique este script https://github.com/adempiere/adempiere/blob/develop/db/ddlutils/postgresql/operators.sql
> 
> > --DROP OPERATOR + (marca de tiempo, NUMÉRICA); 
> > CREAR OPERADOR + (PROCEDIMIENTO = adddays, 
> > LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC, 
> > COMMUTATOR = +);
> 
> > --DROP OPERATOR - (marca de tiempo, NUMÉRICA); 
> > CREAR OPERADOR - (PROCEDIMIENTO = 
> > días restados, IZQUIERDA = TIEMPO 
> > AMARTO , DERECHA = NÚMERO , COMUNICADOR = -);

Ejecute las recomendaciones y lo que dice 
ERROR:  no existe la función adddays(timestamp with time zone, numeric)
SQL state: 42883

**Comment by ppenalo** [comment]
SOLUCION QUE ENCONTRE 

It is observed that after migrating to 391 there are problems when executing certain reports or functionalities of the system.

This is due to an error when executing the function 'paymenttermduedate (numeric, timestamp with time zone)', which throws the following Postgres message:

"ERROR: the operator does not exist: timestamp with time zone + numeric
LINE 1: SELECT TRUNC (DocDate) + p.NetDays
                                ^
TIP: No operator matches the given name and argument types. You might need to add explicit type casts.
INQUIRY: SELECT TRUNC (DocDate) + p.NetDays
CONTEXT: PL / pgSQL function paymenttermduedate (numeric, timestamp with time zone) on line 41 in assignment "

Our solution would be to modify the aforementioned function, in the ELSE part, as follows:

**"DueDate: = (TRUNC (DocDate) + (p.NetDays || 'days') :: interval) :: timestamp without time zone;"**

**Comment by e-Evolution** [comment]
Hi @ppenalo! 

This problem is due to the fact that the system requires the postgres administrator password, in a standard installation it is required that when uploading the dump from the adempiere database, the operator can be created within the database but this can only be done create if the user has all the permissions in the database.

kind regards
