### ISSUE TITLE
 DB.executeUpdate: DELETE FROM C_AcctProcessorLog WHERE C_AcctProcessor_ID=100 AND (Created+7) < CURRENT_TIMESTAMP [null] [24]

### ISSUE THREAD

**Issue by ChrisHird** [adempiere/adempiere#2328]
Just installed fresh copy of Adempiere,PostgreSQL,Java JDK1.8.0_202. I try to start the server and I get the following. Server ends and I cannot run. I did install the sample data as per the installation instructions in the Wiki.
 
===========> Env.getContextAsDate: No value for: #Date [19]
===========> Env.getContextAsDate: No value for: #Date [19]
===========> DB.executeUpdate: DELETE FROM C_AcctProcessorLog WHERE C_AcctProcessor_ID=100 AND (Created+7) < CURRENT_TIMESTAMP [null] [24]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 73; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.model.MAcctProcessor.deleteLog(MAcctProcessor.java:150)
        at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:82)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> DB.executeUpdate: DELETE FROM C_AcctProcessorLog WHERE C_AcctProcessor_ID=100 AND (Created+7) < CURRENT_TIMESTAMP [null] [24]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 73; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.model.MAcctProcessor.deleteLog(MAcctProcessor.java:150)
        at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:82)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 73 [24]
===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 73 [24]
===========> RequestProcessor.processStatus: SELECT * FROM R_Request r WHERE EXISTS (SELECT * FROM R_Status s WHERE r.R_Status_ID=s.R_Status_ID AND s.TimeoutDays > 0 AND s.Next_Status_ID > 0 AND r.DateLastAction+s.TimeoutDays < SysDate) ORDER BY R_Status_ID [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 167; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
        at org.compiere.server.RequestProcessor.processStatus(RequestProcessor.java:438)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:75)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> RequestProcessor.processRequests: SELECT * FROM R_Request r WHERE r.DueType='5' AND r.Processed='N' AND AD_Client_ID=? AND EXISTS (SELECT * FROM R_RequestType rt WHERE r.R_RequestType_ID=rt.R_RequestType_ID AND (r.DateNextAction+rt.DueDateTolerance) < SysDate) [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + numeric
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 196; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
        at org.compiere.server.RequestProcessor.processRequests(RequestProcessor.java:167)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:76)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> RequestProcessor.processRequests: SELECT * FROM R_Request WHERE Processed='N' AND AD_Client_ID=? AND (DateNextAction+2) < SysDate AND (DateLastAlert IS NULL OR (DateLastAlert+1) < SysDate) [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 84; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
        at org.compiere.server.RequestProcessor.processRequests(RequestProcessor.java:226)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:76)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> RequestProcessor.processRequests: SELECT * FROM R_Request WHERE Processed='N' AND AD_Client_ID=? AND IsEscalated='N' AND (DateNextAction+3) < SysDate [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 104; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
        at org.compiere.server.RequestProcessor.processRequests(RequestProcessor.java:281)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:76)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> RequestProcessor.processRequests: SELECT * FROM R_Request WHERE Processed='N' AND AD_Client_ID=? AND (Updated+1) < SysDate AND (DateLastAlert IS NULL OR (DateLastAlert+1) < SysDate) [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 77; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeQuery(Unknown Source)
        at org.compiere.server.RequestProcessor.processRequests(RequestProcessor.java:325)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:76)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> DB.executeUpdate: DELETE FROM R_RequestProcessorLog WHERE R_RequestProcessor_ID=100 AND (Created+7) < CURRENT_TIMESTAMP [null] [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 79; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.model.MRequestProcessor.deleteLog(MRequestProcessor.java:234)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:79)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> DB.executeUpdate: DELETE FROM R_RequestProcessorLog WHERE R_RequestProcessor_ID=100 AND (Created+7) < CURRENT_TIMESTAMP [null] [25]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 79; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.model.MRequestProcessor.deleteLog(MRequestProcessor.java:234)
        at org.compiere.server.RequestProcessor.doWork(RequestProcessor.java:79)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)

===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 79 [25]
===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 79 [25]
===========> DB.executeUpdate: DELETE FROM AD_Note WHERE AD_Client_ID=0 AND (Created+7) < CURRENT_TIMESTAMP [Scheduler_cbf441fe-cdf6-4a96-afd8-76fab0f5b1ff] [28]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 54; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.process.NoteDelete.doIt(NoteDelete.java:75)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.compiere.model.MProcess.startClass(MProcess.java:453)
        at org.compiere.model.MProcess.processIt(MProcess.java:373)
        at org.compiere.model.MProcess.processIt(MProcess.java:342)
        at org.compiere.server.Scheduler.runProcess(Scheduler.java:175)
        at org.compiere.server.Scheduler.doWork(Scheduler.java:121)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)
        at org.compiere.server.Scheduler.run(Scheduler.java:434)

===========> DB.executeUpdate: DELETE FROM AD_Note WHERE AD_Client_ID=0 AND (Created+7) < CURRENT_TIMESTAMP [Scheduler_cbf441fe-cdf6-4a96-afd8-76fab0f5b1ff] [28]
org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 54; State=42883; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdate(DB.java:1046)
        at org.compiere.util.DB.executeUpdate(DB.java:908)
        at org.compiere.util.DB.executeUpdate(DB.java:895)
        at org.compiere.process.NoteDelete.doIt(NoteDelete.java:75)
        at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
        at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
        at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
        at org.compiere.model.MProcess.startClass(MProcess.java:453)
        at org.compiere.model.MProcess.processIt(MProcess.java:373)
        at org.compiere.model.MProcess.processIt(MProcess.java:342)
        at org.compiere.server.Scheduler.runProcess(Scheduler.java:175)
        at org.compiere.server.Scheduler.doWork(Scheduler.java:121)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)
        at org.compiere.server.Scheduler.run(Scheduler.java:434)

===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 54 [28]
===========> DB.saveError: DBExecuteError - ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 54 [28]
-----------> MClient.createEMail: No To address: MUser[0,Name=null,EMailUserID=null] [28]
-----------> MClient.createEMail: No To address: MUser[0,Name=null,EMailUserID=null] [28]
Exception in thread "Delete Old Notes" org.adempiere.exceptions.DBException: org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 67
        at org.compiere.util.DB.executeUpdateEx(DB.java:1129)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1180)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1171)
        at org.compiere.model.MScheduler.deleteLog(MScheduler.java:152)
        at org.compiere.server.Scheduler.doWork(Scheduler.java:141)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)
        at org.compiere.server.Scheduler.run(Scheduler.java:434)
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 67
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
        at org.compiere.util.DB.executeUpdateEx(DB.java:1120)
        ... 6 more

**Comment by e-Evolution** [comment]
@ChrisHird how you install Adempiere , I testing https://github.com/adempiere/adempiere-docker/tree/release/2.0.0 , and https://github.com/adempiere/adempiere/releases/download/3.9.1/Adempiere_391LTS.tar.gz

I can not replicate the issue.

This issue is cause because the operator timestamp + and - no was created.

please see #2306 ##2251

**Comment by ChrisHird** [comment]
I followed the instructions on the Wiki to install on Windows 10 with PostgreSQL. I am using the SDK from Oracle which is JDK1.8.0_202 (jdk after this have no tools.jar which gave first problem with the install).

It appears to complain about this 'CURRENT_TIMESTAMP [null] [25]' Any idea where I need to set the CURRENT_TIMESTAMP for the DB?

**Comment by e-Evolution** [comment]
@ChrisHird the problema are the operator 

To solve this issue apply this script https://github.com/adempiere/adempiere/blob/develop/db/ddlutils/postgresql/operators.sql

> --DROP OPERATOR + (timestamptz, NUMERIC);
> CREATE OPERATOR + ( PROCEDURE = adddays,
> LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
> COMMUTATOR = +);

> --DROP OPERATOR - (timestamptz, NUMERIC);
> CREATE OPERATOR - ( PROCEDURE = subtractdays,
> LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
> COMMUTATOR = -);

I made a fresh install to try replicate the problem and have not this problem. I not understand because not is created while execute RUN_ImportADempiere, please download again the binary distribution and try.

**Comment by ChrisHird** [comment]
OK That is probably the problem? I though as this was a totally new install the RUN_ImportADempiere stage was only required if you already had the DB installed and wanted to import to latest version?

I will try to run that script to see if it clears up the error.

**Comment by ChrisHird** [comment]
Nope still same problem after running that script? I checked the functions that are available and the 2 you mention above are there?

**Comment by e-Evolution** [comment]
@ChrisHird if the operator are load , then you can executed 

SELECT CURRENT_TIMESTAMP +  1 ;

Or

SELECT NOW () +  1 ;

**Comment by ChrisHird** [comment]
Still gives the same error?

ERROR:  operator does not exist: timestamp with time zone + integer
LINE 1: SELECT CURRENT_TIMESTAMP + 1 ;
                                 ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

********** Error **********

ERROR: operator does not exist: timestamp with time zone + integer
SQL state: 42883
Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
Character: 26

Here are the functions I found.

-- Function: adempiere.adddays(interval, numeric)

-- DROP FUNCTION adempiere.adddays(interval, numeric);

CREATE OR REPLACE FUNCTION adempiere.adddays(
    inter interval,
    days numeric)
  RETURNS integer AS
$BODY$
BEGIN
RETURN ( EXTRACT( EPOCH FROM ( inter ) ) / 86400 ) + days;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION adempiere.adddays(interval, numeric)
  OWNER TO adempiere;

-- Function: adempiere.subtractdays(timestamp with time zone, numeric)

-- DROP FUNCTION adempiere.subtractdays(timestamp with time zone, numeric);

CREATE OR REPLACE FUNCTION adempiere.subtractdays(
    day timestamp with time zone,
    days numeric)
  RETURNS date AS
$BODY$
BEGIN
    RETURN addDays(day,(days * -1));
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION adempiere.subtractdays(timestamp with time zone, numeric)
  OWNER TO adempiere;

**Comment by e-Evolution** [comment]
@ChrisHird , the problem not is the function you need create the operator into the postgresql schema

so execute this script https://github.com/adempiere/adempiere/blob/develop/db/ddlutils/postgresql/operators.sql

**Comment by ChrisHird** [comment]
Same error as before.

ERROR:  function adddays(timestamp with time zone, numeric) does not exist

********** Error **********

ERROR: function adddays(timestamp with time zone, numeric) does not exist
SQL state: 42883

Not an SQL expert so not sure why??

**Comment by mckayERP** [comment]
When you run the sql, you need to set the search path;

    SET SEARCH_PATH TO adempiere;

    --DROP OPERATOR + (timestamptz, NUMERIC);
    CREATE OPERATOR + ( PROCEDURE = adddays,
    LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
    COMMUTATOR = +);

    --DROP OPERATOR - (timestamptz, NUMERIC);
    CREATE OPERATOR - ( PROCEDURE = subtractdays,
    LEFTARG = TIMESTAMPTZ, RIGHTARG = NUMERIC,
    COMMUTATOR = -);
