### ISSUE TITLE
WPayment has error in query

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2347]
===========> WPayment.dynInit: SELECT a.C_BP_BankAccount_ID, NVL(b.Name, ' ')||'_'||NVL(a.AccountNo, ' ') AS Acct FROM C_BP_BankAccount a LEFT OUTER JOIN C_Bank b ON (a.C_Bank_ID=b.C_Bank_ID) WHERE C_BPartner_ID=?AND a.IsActive='Y' AND a.IsACH='Y' [31]
org.postgresql.util.PSQLException: ERROR: column reference "c_bpartner_id" is ambiguous
  Position: 178; State=42702; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.adempiere.webui.apps.form.WPayment.dynInit(WPayment.java:754)
	at org.adempiere.webui.apps.form.WPayment.<init>(WPayment.java:143)

**Comment by mckayERP** [comment]
Together with VPayment, these two forms are mostly duplicated code and complicated code at that.  I'm going to, at the suggestion of Victor, create a controller class for these forms and consolidate the common code in one place.  I'll also change the cash payment to use the new C_Payment document.
