### ISSUE TITLE
Error on process Generating PO from Requisition

### ISSUE THREAD

**Issue by Ganzt90** [adempiere/adempiere#2375]
When I try to use the Create PO from Requisition process, ADempiere generates this error

![create-po-from-requisition](https://user-images.githubusercontent.com/37981079/53197579-df857780-35f0-11e9-8972-cdfea0ea6209.png)

log File:

> ===========> RequisitionPOCreate.process: java.lang.NullPointerException [54]
java.lang.NullPointerException
	at org.compiere.process.RequisitionPOCreate.doIt(RequisitionPOCreate.java:83)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:687)
	at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

**Comment by marcalwestf** [comment]
Error reproduced.
It came with commit https://github.com/adempiere/adempiere/commit/c14db67595c36e3d8706d8ad5e936bc936b1bb63 , which supposes the process can only be called by Smart Browser.

I think usiing the Smart Browser is better, but an NPE is a bug.

The reason is because _getSelectionKeys() == null_ when calling it as @Ganzt90  did, which causes the NPE:
![20180227_po_from_req_05](https://user-images.githubusercontent.com/1789408/53539926-19ff8080-3ad9-11e9-92b9-0b885442149f.png)

The solution: catching if _getSelectionKeys() == null_ :
![20180227_po_from_req_06](https://user-images.githubusercontent.com/1789408/53539963-3f8c8a00-3ad9-11e9-950d-d693a4c23396.png)

Once done that, it works smoothly:
![20180227_po_from_req_07](https://user-images.githubusercontent.com/1789408/53540011-6ba80b00-3ad9-11e9-8a89-a1bf7b70f19b.png)
![20180227_po_from_req_08](https://user-images.githubusercontent.com/1789408/53540019-6e0a6500-3ad9-11e9-8042-4b0ff919a8a8.png)
