### ISSUE TITLE
swing-client: IndexOutOfBoundsException in addTab Method

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#2424]
observed on big tables (more then 10k recs):

```
10:53:07.232 MChangeLog.fillChangeLog: #73 [29]
===========> GridTab.verifyRow: Table not open MTable[C_Bank,WindowNo=2,Tab=0] targetRow:-1 [29]
10:53:07.254 GridTable.dataRefresh: Row=-1 [29]
10:53:07.259   MIssue.create: Table not open MTable[C_Bank,WindowNo=2,Tab=0] targetRow:-1 [29]
10:53:07.260   GridField.loadLookup: (SystemStatus) [29]
===========> GridTab.verifyRow: Table not open MTable[C_Bank,WindowNo=2,Tab=0] targetRow:-1 [29]
...
10:53:08.371 APanel.dataStatusChanged:  1/8000->16642 [30]
===========> AMenuStartItem.run: ID=171 [29]
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at javax.swing.JTabbedPane.setDisabledIconAt(JTabbedPane.java:1401)
	at org.compiere.grid.VTabbedPane.addTab(VTabbedPane.java:108)
	at org.compiere.apps.APanel.initPanel(APanel.java:879)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:129)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:115)
	at org.compiere.apps.AMenuStartItem.startWindow(AMenuStartItem.java:237)
	at org.compiere.apps.AMenuStartItem.startOption(AMenuStartItem.java:178)
	at org.compiere.apps.AMenuStartItem.run(AMenuStartItem.java:138)
```
this was reported in #1955 - but not completle solved as you can see.

**Comment by homebeaver** [comment]
I think a try - catch around line 108 (VTabbedPane.addTab Method) will solve the problem:

```java
// 108:
		setDisabledIconAt(index, s_disabledIcon);
```
I'll check and prepare a PR
