### ISSUE TITLE
PDF libraries are missing in Eclipse Deployment Assembly

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#2430]
Get the following error when trying to print a financial report:

===========> zkoss.handleError:1130: >>java.lang.NoClassDefFoundError: io/konik/harness/FileExtractor
>>java.lang.ClassNotFoundException: io.konik.harness.FileExtractor
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
>>	at java.lang.ClassLoader.defineClass1(Native Method)
>>	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>>	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>>	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2854)
>>	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1159)
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1647)
>>	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)

The reference to the this library and a bunch of others is missing in the Eclipse Deployment Assembly for the project.  This only affects debugging of the webui in Eclipse.

**Comment by marcalwestf** [comment]
@mckayERP a question Mike, just trying to reproduce it: does this happen after you have displayed the preview and select "Print"?

And an additional question: do other printings work?

**Comment by yamelsenih** [comment]
Hi, any update with it? I don't have this error
