### ISSUE TITLE
Smart Browse get the hidden parameters

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#251]
If a column into a Smart Browse is checked like **Query Criteria** and it has a **Display Logic**, then if it parameter is hidden also is included in the where clause

**Comment by e-Evolution** [comment]
Now I got this error that I not had before 

12:51:01.035         Env.setContext: Context(17,0) Weight==null [17]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Require Context
	at org.compiere.util.Env.getContext(Env.java:498)
	at org.compiere.model.GridField.get_ValueAsString(GridField.java:815)
	at org.compiere.model.GridField.backupValue(GridField.java:1736)
	at org.compiere.model.GridField.updateContext(GridField.java:1383)
	at org.compiere.model.GridField.setValue(GridField.java:1329)
	at org.eevolution.form.VBrowser.getPanelParameters(VBrowser.java:890)
	at org.eevolution.form.Browser.evaluateMandatoryFilter(Browser.java:608)
	at org.eevolution.form.VBrowser.executeQuery(VBrowser.java:278)
	at org.eevolution.form.VBrowser.cmd_Search(VBrowser.java:627)
	at org.eevolution.form.VBrowser.actionPerformed(VBrowser.java:833)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
12:51:55.877     DB_PostgreSQL.convertStatement: PostgreSQL =>SELECT COUNT(1) FROM R_Request WHERE (SalesRep_ID=? OR AD_Role_ID=?) AND Processed='N' AND (DateNextAction IS NULL OR TRUNC(DateNextAction, 'DD') <= TRUNC(CURRENT_TIMESTAMP, 'DD')) AND (R_Status_ID IS NULL OR R_Status_ID IN (SELECT R_Status_ID FROM R_Status WHERE IsClosed='N')) AND AD_Client_ID=1000000 AND AD_Org_ID IN(1000003,1000025,1000004,1000026,1000005,1000027,1000006,1000028,1000021,1000000,1000022,1000001,1000002,1000024,
