### ISSUE TITLE
Class javax/jms/MessageListener not found when testing ActiveMQ

### ISSUE THREAD

**Issue by bilalperyani** [adempiere/adempiere#2558]
Exception in thread "Human Readable name for - JMS Topic Import Processor" java.
lang.NoClassDefFoundError: javax/jms/MessageListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.adempiere.server.rpl.imp.TopicImportProcessor.process(TopicImport
Processor.java:111)
        at org.compiere.server.ReplicationProcessor.doWork(ReplicationProcessor.
java:119)
        at org.compiere.server.AdempiereServer.run(AdempiereServer.java:231)
Caused by: java.lang.ClassNotFoundException: javax.jms.MessageListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

**Comment by marcalwestf** [comment]
hi @bilalperyani  , this issue was already addressed by #2464 .
I'd recommend to add your comments on #2464 and close this issue, to avoid having twice the same.

**Comment by bilalperyani** [comment]
Duplicate Issue as per discussion with Mario similar issue was already reported #2464
