### ISSUE TITLE
NPE When try create new filed into the window

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2569]
Try create a new field into any tab in some moment got

2019-05-21 11:11:48.099 java[43371:7245547] -[AWTView javaRole]: unrecognized selector sent to instance 0x7f8715100300
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.model.GridTabVO.createFields(GridTabVO.java:230)
	at org.compiere.model.GridTabVO.getFields(GridTabVO.java:340)
	at org.compiere.model.GridTab.loadFields(GridTab.java:370)
	at org.compiere.model.GridTab.loadTab(GridTab.java:313)
	at org.compiere.model.GridTab.initTab(GridTab.java:304)
	at org.compiere.model.GridWindow.initTab(GridWindow.java:195)
	at org.compiere.apps.APanel.initPanel(APanel.java:757)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:129)
	at org.compiere.grid.ed.VLookup.actionZoom(VLookup.java:1663)
	at org.compiere.grid.ed.VLookup.actionPerformed(VLookup.java:866)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by yamelsenih** [comment]
Hi @e-Evolution please add a Step by step

**Comment by yamelsenih** [comment]
I find a Step by Step for it:
1. Login into ADempiere as System
1. Go to any window
1. Press search button (This is ok)
1. Go to tab and field
1. Remove any field
1. Go to window tab and press search button (NPE)
