### ISSUE TITLE
Error Create PO from Requisition, NullPointerException

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#2673]
Hi Team ADempiere

The process Create PO from Requisition not is functional, when executing fails...

The message is java.lang.NullPointerException... 

#### Steps to reproduce

1. Create Requisition (DocStatus CO)
2. Access a process Create PO from Requisition
3. Excecute process

####
The requisition...

<img width="1096" alt="Captura de pantalla 2019-07-09 a la(s) 4 19 38 p  m" src="https://user-images.githubusercontent.com/20327157/60926162-41c2da00-a26b-11e9-8a39-a10c4c33afe7.png">

Excecute process..

<img width="1092" alt="Captura de pantalla 2019-07-09 a la(s) 4 20 13 p  m" src="https://user-images.githubusercontent.com/20327157/60926195-61f29900-a26b-11e9-97e9-2a4bf1da6288.png">

The Error...

<img width="1096" alt="Captura de pantalla 2019-07-09 a la(s) 4 20 39 p  m" src="https://user-images.githubusercontent.com/20327157/60926208-6e76f180-a26b-11e9-8206-c4eb2c749cdd.png">

The Log is the following...

===========> RequisitionPOCreate.process: java.lang.NullPointerException [70]
java.lang.NullPointerException
	at org.compiere.process.RequisitionPOCreate.doIt(RequisitionPOCreate.java:83)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:748)

#### Expected behavior
The process must create the PO :-)

#### Other relevant information
- Your OS: MacOs, Windows, Linux
- Java version: 1.8.0_151
- ADempiere version: 390a - 391
- Browser: Chrome, safari, firefox
- DB Provider: PostgreSQL
- DB version: 9.6 and 11

#### Additional context
Regards

**Comment by e-Evolution** [comment]
bugfix solve in 3.9.2 with #2375
