### ISSUE TITLE
install server error: key store password (no key store)

### ISSUE THREAD

**Issue by linsoner** [adempiere/adempiere#2703]
error msg :  install server error: key store password (no key store)
how to fix it ?

#### Expected behavior
run-setup --> adempiere sserver setting --> test --> error

#### Other relevant information
- Your OS: windows 10 pro 1709 cn
- Java version: 1.7
- ADempiere version: 3.9.2
- Browser [e.g. chrome, safari] chrome
- Browser Version [e.g. 22]
- DB Provider: postgresql
- DB version: 9.6

**Comment by linsoner** [comment]
> install server error: key store password (no key store)
> how to fix it ?
> 
> #### Expected behavior
> run-setup --> adempiere server setting --> test --> error

13:49:03.753 KeyStoreMgt.<init>: G:\software\iDemmpiere\Adempiere_392LTS\Adempiere\keystore\myKeystore [34]
13:49:03.769 KeyStoreMgt.createCertificate:  [34]
13:49:14.813 KeyStoreMgt.keytool: keytool -genkey -keyalg rsa -alias adempiere -dname "CN=DC-MI, OU=Administrator, O=AdempiereUser, L=MyTown, C=CN" -keypass myPassword -validity 999 -keystore G:\software\iDemmpiere\Adempiere_392LTS\Adempiere\keystore\myKeystore -storepass myPassword [34]
===========> KeyStoreMgt.createCertificate: certificate [34]
java.lang.NullPointerException
        at org.compiere.install.KeyStoreMgt.keytool(KeyStoreMgt.java:468)
        at org.compiere.install.KeyStoreMgt.genkey(KeyStoreMgt.java:399)
        at org.compiere.install.KeyStoreMgt.createCertificate(KeyStoreMgt.java:237)
        at org.compiere.install.KeyStoreMgt.verify(KeyStoreMgt.java:106)
        at org.compiere.install.ConfigurationData.testAdempiere(ConfigurationData.java:465)
        at org.compiere.install.ConfigurationData.test(ConfigurationData.java:382)
        at org.compiere.install.ConfigurationPanel.test(ConfigurationPanel.java:666)
        at org.compiere.install.ConfigurationPanel.access$400(ConfigurationPanel.java:62)
        at org.compiere.install.ConfigurationPanel$1.construct(ConfigurationPanel.java:625)
        at org.compiere.apps.SwingWorker$2.run(SwingWorker.java:68)
        at java.base/java.lang.Thread.run(Thread.java:834)


> 
> #### Other relevant information
> * Your OS: windows 10 pro 1709 cn
> * Java version: 1.7
> * ADempiere version: 3.9.2
> * Browser [e.g. chrome, safari] chrome
> * Browser Version [e.g. 22]
> * DB Provider: postgresql
> * DB version: 9.6

**Comment by kmfiter** [comment]
我在Debain10系统上安装时，也遇到过这样的问题，最后是手动运行Keystore生成证书后，就可以了。你的是Win10系统，我不知道能不能像Debain一样使用这个方法。不过可以作为一个思路试一下。
在CMD命令中运行 keytool -genkey - keyalg rsa -alias adempiere -dname“CN = DC-MI，OU = Administrator，O = AdempiereUser，L = MyTown，C = CN”-keypass myPassword -validity 999 -keystore G：\ software \ iDemmpiere \ Adempiere_392LTS \ Adempiere \ keystore \ myKeystore -storepass myPassword
