### ISSUE TITLE
Product Info shows no data in ZK web interface

### ISSUE THREAD

**Issue by mrojasaquino** [adempiere/adempiere#31]
In the `InfoProductPanel` on line 449 there is an error that makes that the Product Info window shows no data.

Instead of:

    new ColumnInfo(Msg.translate(Env.getCtx(), "Warehouse"), "Warehouse", String.class),

It should be :

    new ColumnInfo(Msg.translate(Env.getCtx(), "WarehouseName"), "WarehouseName", String.class),

Same applies to lines 461 - 462 : 

    m_sqlWarehouse += " Group By M_Warehouse_ID, Warehouse ";`
    m_sqlWarehouse += " Order By sum(QtyOnHand) DESC, Warehouse ";

Should be :

    m_sqlWarehouse += " Group By M_Warehouse_ID, WarehouseName ";
    m_sqlWarehouse += " Order By sum(QtyOnHand) DESC, WarehouseName ";	

I was getting the following stack trace :

```
-----------> InfoProductPanel.refresh: SELECT M_Warehouse_ID, Warehouse, sum(QtyAvailable), sum(QtyOnHand), sum(QtyReserved), sum(QtyOrdered) FROM  M_PRODUCT_STOCK_V  WHERE (QtyOnHand <> 0 OR QtyAvailable <> 0 OR QtyReserved <> 0 OR QtyOrdered <> 0) AND M_Product_ID = ? AND M_PRODUCT_STOCK_V.AD_Client_ID IN(0,1000001) AND M_PRODUCT_STOCK_V.AD_Org_ID IN(0,1000001,1000002) Group By M_Warehouse_ID, Warehouse  Order By sum(QtyOnHand) DESC, Warehouse  [59]
org.postgresql.util.PSQLException: ERROR: column "warehouse" does not exist
  Position: 24; State=42703; ErrorCode=0
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
        at com.sun.proxy.$Proxy68.executeQuery(Unknown Source)
        at org.adempiere.webui.panel.InfoProductPanel.refresh(InfoProductPanel.java:702)
        at org.adempiere.webui.panel.InfoProductPanel.recordSelected(InfoProductPanel.java:2075)
        at org.adempiere.webui.panel.InfoPanel.reselectRecord(InfoPanel.java:1752)
        at org.adempiere.webui.panel.InfoPanel.onQueryCallback(InfoPanel.java:1702)

```

Diff :

```
---
 zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java b/zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java
index dabb0df..0ba5884 100644
--- a/zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java
+++ b/zkwebui/WEB-INF/src/org/adempiere/webui/panel/InfoProductPanel.java
@@ -446,7 +446,7 @@ public class InfoProductPanel extends InfoPanel implements EventListener, ValueC
 		//
         ColumnInfo[] s_layoutWarehouse = new ColumnInfo[]{
         		new ColumnInfo(" ", "M_Warehouse_ID", IDColumn.class),
-        		new ColumnInfo(Msg.translate(Env.getCtx(), "Warehouse"), "Warehouse", String.class),
+        		new ColumnInfo(Msg.translate(Env.getCtx(), "WarehouseName"), "WarehouseName", String.class),
         		new ColumnInfo(Msg.translate(Env.getCtx(), "QtyAvailable"), "sum(QtyAvailable)", Double.class, true, true, null),
         		new ColumnInfo(Msg.translate(Env.getCtx(), "QtyOnHand"), "sum(QtyOnHand)", Double.class),
            		new ColumnInfo(Msg.translate(Env.getCtx(), "QtyReserved"), "sum(QtyReserved)", Double.class),
@@ -458,8 +458,8 @@ public class InfoProductPanel extends InfoPanel implements EventListener, ValueC
         String s_sqlWhere = "(QtyOnHand <> 0 OR QtyAvailable <> 0 OR QtyReserved <> 0 OR QtyOrdered <> 0) AND M_Product_ID = ?";
 //      String s_sqlWhere = "M_Product_ID = ?";
         m_sqlWarehouse = warehouseTbl.prepareTable(s_layoutWarehouse, s_sqlFrom, s_sqlWhere, false, "M_PRODUCT_STOCK_V");
-		m_sqlWarehouse += " Group By M_Warehouse_ID, Warehouse ";
-		m_sqlWarehouse += " Order By sum(QtyOnHand) DESC, Warehouse ";		
+		m_sqlWarehouse += " Group By M_Warehouse_ID, WarehouseName ";
+		m_sqlWarehouse += " Order By sum(QtyOnHand) DESC, WarehouseName ";		
 		warehouseTbl.setMultiSelection(false);
         warehouseTbl.autoSize();
         warehouseTbl.setShowTotals(true);
-- 
```

**Comment by yamelsenih** [comment]
Hi @e-Evolution 
It is solved?

**Comment by yamelsenih** [comment]
It is test and ok.
![issue171](https://cloud.githubusercontent.com/assets/2333092/15411339/085a7318-1de9-11e6-9d91-51f03b84d450.png)
