### ISSUE TITLE
Bug: StringIndexOutOfBoundsException in Class Restriction for virtual Columns

### ISSUE THREAD

**Issue by homebeaver** [adempiere/adempiere#3183]
## Bug report

When a virtual column contains more then one sql function, then we get this exception.
Example for BP define a column with `ColumnSQL` = `COALESCE(Name,' ') || ' ' ||COALESCE(Name2, ' ')` - this is good for postgres DB.

Motivation for this column: the **full name of a BP** is Name+Name2 and we want to search/select both parts.

#### Steps to reproduce

1. define a virtual column for `C_BPartner` 
![grafik](https://user-images.githubusercontent.com/3493126/88796039-538e5c80-d1a1-11ea-8bd0-ef917c550cb4.png)

2. define the new field in Window to look like this for GW-client:
![grafik](https://user-images.githubusercontent.com/3493126/88796708-648b9d80-d1a2-11ea-9099-5ca90686455d.png)

3. Now try to lookup
![grafik](https://user-images.githubusercontent.com/3493126/88796971-dfed4f00-d1a2-11ea-9915-87a0d4dd5d92.png)

In the log you can find

```
13:52:47.861 Find.actionPerformed: Ok [17]
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: -20
	at java.lang.String.substring(String.java:1967)
	at org.compiere.model.Restriction.getSQL(MQuery.java:1215)
	at org.compiere.model.MQuery.getWhereClause(MQuery.java:703)
	at org.compiere.model.MQuery.toString(MQuery.java:951)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.compiere.apps.search.Find.getNoOfRecords(Find.java:1947)
	at org.compiere.apps.search.Find.cmd_ok_Simple(Find.java:1460)
	at org.compiere.apps.search.Find.actionPerformed(Find.java:1085)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
```

#### Expected behavior
No exeption should happen, because this is a valid virtual column (for postgres)

#### Other relevant information
- Your OS: win 10
- Java version: 8
- ADempiere version: 3.9.3
- Browser Version [e.g. 22]
- DB Provider: postgres
- DB version: 12

#### Additional context
Bug is in class `Restriction`, in file `base\src\org\compiere\model\MQuery.java`:

```java
class Restriction  implements Serializable
...
    public String getSQL (String tableName)
...
            //    Assumes - REPLACE(INITCAP(variable),'s','X') or UPPER(variable)
            int pos = ColumnName.lastIndexOf('(')+1;    //    including (
            int end = ColumnName.indexOf(')');
            // Column name is already qualified
            if (ColumnName.contains(tableName + "."))
                sb.append(ColumnName);
            //    We have a Function in the ColumnName
            else if (pos != -1 && end != -1)
                sb.append(ColumnName.substring(0, pos))
                    .append(tableName).append(".").append(ColumnName.substring(pos, end))
                    .append(ColumnName.substring(end));
            else
                sb.append(tableName).append(".").append(ColumnName);
...
```

Tho calculation of `pos` and `end` works only for simple experssions!
In debug you can find out that
```
UPPER(COALESCE(Name,' ') || ' ' ||COALESCE(Name2, ' '))
                       ^end=23            ^pos=43
                       indexOf(')')       lastIndexOf('(')
```
this leads to **String index out of range: -20**

regards EUGen

**Comment by homebeaver** [comment]
Hi @e-Evolution , @marcalwestf , @yamelsenih 

studying the code there is a workaround. For full qualified column names in `ColumnSQL` expression the wrong `pos` and `end` are not used. so with `COALESCE(C_BPartner.Name,' ') || ' ' ||COALESCE(C_BPartner.Name2, ' ')` we can avoid the exception.

**This is a workaround, not the resolution.**
