### ISSUE TITLE
Error in calculating quantity ordered or reserved for manufacturing order and distribution order

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3266]
## Bug report

The ordered and reserved quantity are duplicate when prepare it or complete a manufacturing order.

#### Steps to reproduce

1.- Create an Manufacturing Order 
2.- Change the Document status from Draft to In process, here create a first reserved and ordered.
3.- Change the Document status from  In process to complete, here create a second reserved and ordered.

#### Expected behavior
The ordered and reserved should be calculate rightly 

#### Other relevant information
- Your OS: MacOS
- Java version: 1.8
- ADempiere version: 3.9.3
- Browser safari
- DB Provider: PostgreSQL
- DB version: 12.3

**Comment by yamelsenih** [comment]
Hi @e-Evolution this change add a new bug:

Step for reproduce:
- Create a Sales Order
- Add a new Line: Only with a Charge
- Complete it

The follow error is throwed:
```Java
java.lang.NullPointerException
	at org.compiere.model.MOrder.reserveStock(MOrder.java:1558)
	at org.compiere.model.MOrder.prepareIt(MOrder.java:1311)
	at org.compiere.process.DocumentEngine.prepareIt(DocumentEngine.java:411)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:280)
	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:258)
	at org.compiere.model.MOrder.processIt(MOrder.java:1169)
	at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:861)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:781)
	at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:341)
	at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:256)
	at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:284)
	at org.compiere.wf.MWFActivity.run(MWFActivity.java:784)
	at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:471)
	at org.compiere.wf.MWorkflow.start(MWorkflow.java:731)
	at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:787)
```
