### ISSUE TITLE
[Bug Report] Error when try apply script migration 07650_Add_Order_Line_Reference_for_Financial_Transaction.xml

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3372]
## Bug report
Error when try apply the script 07650_Add_Order_Line_Reference_for_Financial_Transaction.xml

Big introducing #3359

18:18:14.273 MigrationFromXML.lambda$loadFile$0: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D)  ---> Migration exists but has to be rolled back. [1]
18:18:14.273 MigrationFromXML.lambda$loadFile$0: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D)  ---> Migration exists but has to be rolled back. [1]
-----------> MField.load: NO Data found for AD_Field_ID=99685 [1]
-----------> MField.load: NO Data found for AD_Field_ID=99685 [1]
-----------> MMigrationStep.bailout: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD.  Step 130, Record 99685 was not found in table Field (107). [1]
-----------> MMigrationStep.bailout: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD.  Step 130, Record 99685 was not found in table Field (107). [1]
-----------> MMigrationStep.bailout: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
-----------> MMigrationStep.bailout: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD.  Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
-----------> MMigration.apply: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
-----------> MMigration.apply: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
18:18:16.570 MigrationApply.addLog: 0 - null - null - Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
18:18:16.570 MigrationApply.addLog: 0 - null - null - Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
===========> MigrationApply.process: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigration.apply(MMigration.java:178)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:221)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:50)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:302)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:299)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:160)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
caused by: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:275)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:627)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:232)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
caused by: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:277)
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:251)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:522)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:232)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)

===========> MigrationApply.process: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107). [1]
org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigration.apply(MMigration.java:178)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:221)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:50)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:302)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:299)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:160)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
caused by: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:275)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:627)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:232)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
caused by: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:277)
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:251)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:522)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:232)
	at org.compiere.model.MMigration.apply(MMigration.java:155)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)

18:18:16.873 Trx.rollback: **** TrxRun_2f266bcd-da4b-4801-a5ed-84f9ca4152a6 [1]
18:18:16.873 Trx.rollback: **** TrxRun_2f266bcd-da4b-4801-a5ed-84f9ca4152a6 [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /opt/Adempiere/migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:167)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:310)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:160)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)

===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /opt/Adempiere/migration/393lts-394lts/07650_Add_Order_Line_Reference_for_Financial_Transaction.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:167)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:107)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:358)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:199)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 7650 - Add Order Line Reference for Financial Transaction - 3.9.4 (D) ; Step: 130; Type: AD. Step 130, Record 99685 was not found in table Field (107).
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:310)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:183)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:160)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:109)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:50)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:177)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:130)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:162)

org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Loading Migration from XML failed.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:274)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:96)

*** 2021-02-25 18:18:17.016 Adempiere Log (CLogConsole) ***

**Comment by e-Evolution** [comment]
Script error when is apply 

![image](https://user-images.githubusercontent.com/786968/110697189-9ab9e280-81b1-11eb-97a1-9a8c337a59ee.png)

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/786968/110697181-97265b80-81b1-11eb-95b8-aade0ce7e26a.png">
