### ISSUE TITLE
[Bug Report] Error when try to Start the Accounting processor and try posting fact account using two company

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3535]
## Bug report
Error when try to Start the Accounting processor and try posting fact account using two company

#### Steps to reproduce
1.- Build from develop branch
2.- Setup Adempiere
3.- Using Swing UI Create a new Company (Client)
4.- Starting RUN_Server2.sh

#### Screenshot or Gif

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/786968/125704542-d26f9bcf-c4ca-413e-aba6-e62c8fa61398.png">

-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [26]
-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [26]
-----------> EMail.addTo: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [26]
-----------> EMail.addTo: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [26]
-----------> EMail.isValid: From is invalid=null [26]
-----------> EMail.isValid: From is invalid=null [26]
-----------> EMail.isValid: From is invalid=null [26]
-----------> EMail.isValid: From is invalid=null [26]
-----------> MClient.sendEMail: Could NOT Send Email: Server started: ? to you @ company.org: Invalid Data (System) [26]
-----------> MClient.sendEMail: Could NOT Send Email: Server started: ? to you @ company.org: Invalid Data (System) [26]
===========> Env.getContextAsDate: No value for: #Date [26]
===========> Env.getContextAsDate: No value for: #Date [26]
===========> DB.executeUpdate: UPDATE AD_Session SET Updated=TO_TIMESTAMP('2021-07-14 17:52:54','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Session_ID=1000066 [POSave_3338624d-3a50-441f-a9d5-ac47d7d96216] [32]
org.postgresql.util.PSQLException: This statement has been closed.; State=55000; ErrorCode=0
	at org.postgresql.jdbc.PgStatement.checkClosed(PgStatement.java:705)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:907)
	at org.compiere.util.DB.executeUpdate(DB.java:894)
	at org.compiere.model.PO.saveUpdate(PO.java:2684)
	at org.compiere.model.PO.save(PO.java:2250)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.model.MSession.keepAlive(MSession.java:268)
	at org.compiere.model.MSession.get(MSession.java:97)
	at org.compiere.model.PO.saveNew(PO.java:2789)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.server.AcctProcessor.updateLog(AcctProcessor.java:119)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:129)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:261)

===========> DB.executeUpdate: UPDATE AD_Session SET Updated=TO_TIMESTAMP('2021-07-14 17:52:54','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Session_ID=1000066 [POSave_3338624d-3a50-441f-a9d5-ac47d7d96216] [32]
org.postgresql.util.PSQLException: This statement has been closed.; State=55000; ErrorCode=0
	at org.postgresql.jdbc.PgStatement.checkClosed(PgStatement.java:705)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy4.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:907)
	at org.compiere.util.DB.executeUpdate(DB.java:894)
	at org.compiere.model.PO.saveUpdate(PO.java:2684)
	at org.compiere.model.PO.save(PO.java:2250)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.model.MSession.keepAlive(MSession.java:268)
	at org.compiere.model.MSession.get(MSession.java:97)
	at org.compiere.model.PO.saveNew(PO.java:2789)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.server.AcctProcessor.updateLog(AcctProcessor.java:119)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:129)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:261)

===========> DB.saveError: DBExecuteError - This statement has been closed. [32]
===========> DB.saveError: DBExecuteError - This statement has been closed. [32]
-----------> MSession.saveUpdate: #-1 - AD_Session.AD_Session_ID=1000066 [32]
-----------> MSession.saveUpdate: #-1 - AD_Session.AD_Session_ID=1000066 [32]
java.lang.Exception: Illegal to getConnection for Trx that is not register.
	at org.compiere.util.Trx.getConnection(Trx.java:154)
	at org.compiere.util.Trx.releaseSavepoint(Trx.java:445)
	at org.compiere.model.PO.save(PO.java:2292)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.model.MSession.keepAlive(MSession.java:268)
	at org.compiere.model.MSession.get(MSession.java:97)
	at org.compiere.model.PO.saveNew(PO.java:2789)
	at org.compiere.model.PO.save(PO.java:2231)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.compiere.server.AcctProcessor.updateLog(AcctProcessor.java:119)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:129)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:261)
===========> MAcctProcessorLog.saveError: Error - This statement has been closed. [32]
===========> MAcctProcessorLog.saveError: Error - This statement has been closed. [32]
Exception in thread "GardenWorld Accounting Processor" org.adempiere.exceptions.AdempiereException: This statement has been closed.
	at org.compiere.model.PO.saveEx(PO.java:2317)
	at org.compiere.server.AcctProcessor.updateLog(AcctProcessor.java:119)
	at org.compiere.server.AcctProcessor.doWork(AcctProcessor.java:129)
	at org.compiere.server.AdempiereServer.run(AdempiereServer.java:261)
-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [34]
-----------> EMail.setFrom: you @ company.org: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``you @ company.org'' [34]
-----------> EMail.addTo: admin @ gardenworld.com: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``admin @ gardenworld.com'' [34]
-----------> EMail.addTo: admin @ gardenworld.com: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``admin @ gardenworld.com'' [34]
-----------> EMail.isValid: From is invalid=null [34]
-----------> EMail.isValid: From is invalid=null [34]
-----------> EMail.isValid: From is invalid=null [34]
-----------> EMail.isValid: From is invalid=null [34]
-----------> X_AD_UserMail.set_ValueNoCheck: MessageID - Value too long - truncated to length=10 [34]
-----------> X_AD_UserMail.set_ValueNoCheck: MessageID - Value too long - truncated to length=10 [34]
-----------> MClient.sendEmailNow: Could NOT Send Email: Request 10000002 - Due to admin @ gardenworld.com: Invalid Data (GardenWorld) [34]
-----------> MClient.sendEmailNow: Could NOT Send Email: Request 10000002 - Due to admin @ gardenworld.com: Invalid Data (GardenWorld) [34]
-----------> MClient.createEMail: No To address: MUser[0,Name=null,EMailUserID=null] [37]
-----------> MClient.createEMail: No To address: MUser[0,Name=null,EMailUserID=null] [37]

#### Expected behavior
the error was introducing when re factory the Accounting Server Processor

#### Other relevant information
- Your OS: MacOS
- Java version: 1.8
- ADempiere version: last build from develop branch
- Browser Safari
- DB Provider: PG 
- DB version:13

**Comment by Migueloc66** [comment]
Buenas Tardes, Compañeros tengo un pregunta, estoy importando la ultima localizacion de venezuela siguiendo las instrucciones de la pagina https://github.com/adempiere/LVE pero cuando estoy importando los XML salen errores ya que hay tablas que comienzan por WH_ que no existen en los XML de migracion como por ejemplo, WH_SETTING, WH_WITHHOLDING, LVE_WINTHOLDINGLINE,WH_WITHHOLDINGRENTARATE entre otros, me pueden decir de donde puedo descargar la localizacion de venezuela correcta.

**Comment by EdwinBetanc0urt** [comment]
Saludos @Migueloc66, las tablas faltantes hacen referencia  a `Withholding` (WH), el proyecto `LVE` requiere el proyecto `Withholding`, por favor mirar https://github.com/erpcya/Withholding

> Buenas Tardes, Compañeros tengo un pregunta, estoy importando la ultima localizacion de venezuela siguiendo las instrucciones de la pagina https://github.com/adempiere/LVE pero cuando estoy importando los XML salen errores ya que hay tablas que comienzan por WH_ que no existen en los XML de migracion como por ejemplo, WH_SETTING, WH_WITHHOLDING, LVE_WINTHOLDINGLINE,WH_WITHHOLDINGRENTARATE entre otros, me pueden decir de donde puedo descargar la localizacion de venezuela correcta.
