### ISSUE TITLE
[Bug Report] Missing jar commons-collections-3.2.2.jar dependency for JasperReport

### ISSUE THREAD

**Issue by rcapecce** [adempiere/adempiere#3622]
## Bug report - Missing class in JasperReport

When I run a JasperReport in this instance, I get this message.
I test this issue in an ZK instance and in the debug with swing, and get the same error.

This is the tracer error
```
java.lang.NoClassDefFoundError: org/apache/commons/collections/map/ReferenceMap
	at net.sf.jasperreports.engine.design.JRAbstractJavaCompiler.<clinit>(JRAbstractJavaCompiler.java:83)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at net.sf.jasperreports.engine.JasperCompileManager.getCompiler(JasperCompileManager.java:823)
	at net.sf.jasperreports.engine.JasperCompileManager.getEvaluator(JasperCompileManager.java:380)
	at net.sf.jasperreports.engine.fill.JRFillDataset.createCalculator(JRFillDataset.java:487)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:168)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:273)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:79)
	at net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(JRFiller.java:251)
	at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:272)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:114)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:482)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:885)
	at org.compiere.report.ReportStarter.startProcess(ReportStarter.java:618)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:168)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:113)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:392)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

#### Screenshot or Gif

![Peek 15-09-2021 16-25](https://user-images.githubusercontent.com/14218144/133496985-e22f5e68-149f-4057-abd4-4ecd6596a1c8.gif)

#### Other relevant information
- Your OS: Kubuntu 20.04
- Java version: 11
- ADempiere version: develop
- Browser [e.g. chrome, safari] Chrome
- Browser Version 71.0
- DB Provider: PostgreSQL
- DB version: 9.6

#### Additional information
- We load the JasperReport source file (jrxml) in the "Report & Process", we don't use the compiled Jasper.
- JasperSoft Studio 6.16
- This source (jrxml) is working in other previous instace with Java 8

**Comment by e-Evolution** [comment]
@e-Evolution Hi Raul , this problem can be cause by incompatibility the Jaspersoft Studio , Adempiere currently support  6.11.0 , if you use other more recent version check the back compatibility.

![image](https://user-images.githubusercontent.com/786968/133501062-3066bc93-1233-41a5-8efe-858573471620.png)

kind regards
Victor

**Comment by rcapecce** [comment]
I add new information
jasper compiled, compiler version 6.11
```
===========> MLookupFactory.getLookupInfo: Column Not Found - AD_Column_ID=0 [461]
===========> MLookupFactory.getLookupInfo: Column Not Found - AD_Column_ID=0 [295]
===========> zkoss.handleError:1130: >>java.lang.NoClassDefFoundError: Could not initialize class net.sf.jasperreports.extensions.ExtensionsEnvironment
>>      at net.sf.jasperreports.engine.DefaultJasperReportsContext.getExtensions(DefaultJasperReportsContext.java:277)
>>      at net.sf.jasperreports.engine.util.MessageUtil.getMessageProvider(MessageUtil.java:70)
>>      at net.sf.jasperreports.engine.JRException.resolveMessage(JRException.java:167)
>>      at net.sf.jasperreports.engine.JRException.getMessage(JRException.java:148)
>>      at net.sf.jasperreports.engine.JRException.getMessage(JRException.java:139)
>>      at org.compiere.report.ReportStarter.processReport(ReportStarter.java:986)
>>... [32]
```
---
