### ISSUE TITLE
[Bug Report] Error when try print Component Check 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3840]
## Bug report
When try get the report Component Check   got an error and the UI not respond 

#### Steps to reproduce
1.- Try get the Component Check to 8000 Manufacturing Order

![image](https://user-images.githubusercontent.com/786968/167278906-f2f660e4-32bf-43c2-aa50-70f7e1a90f02.png)

2.- The error is show 

![image](https://user-images.githubusercontent.com/786968/167278924-8860d201-71a7-4df0-8822-3ad12969ad13.png)

#### Link to minimal reproduction

The last build 394 nightly 

The bug was introducing in 5c51177330781fcf0868f9fe5db47b47c441b1d2

#### Expected behavior
A report should be show 

#### Other relevant information
- Your OS: macos
- Java version: 11
- ADempiere version: last develop 
- Browser  safari
- DB Provider: PG 
- DB version: 11

**Comment by e-Evolution** [comment]
@marcalwestf Can you fix this issue

here shoe the trace log:

```----------->Msg.getMsg: NOT found: Load New Report Definition [40]
-----------> Msg.getMsg: NOT found: Load New Report Definition [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
-----------> Msg.getMsg: NOT found: QuickEntry [40]
===========> zkoss.handleError:1130: >>java.lang.NullPointerException: Cannot invoke "org.compiere.model.MQuery.setWindowNo(int)" because "query" is null
>>      at org.compiere.print.ReportEngine.get(ReportEngine.java:909)
>>      at org.compiere.print.ReportCtl.startStandardReport(ReportCtl.java:225)
>>      at org.compiere.print.ReportCtl.start(ReportCtl.java:171)
>>      at org.compiere.print.ReportCtl.start(ReportCtl.java:105)
>>      at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:401)
>>      at org.adempiere.webui.apps.ProcessPanel.runProcess(ProcessPanel.java:688)
>>... [26]
```

**Comment by e-Evolution** [comment]
@marcalwestf I think you added this line without validating if query was not a null reference

https://github.com/adempiere/adempiere/blob/1b48b1f8fd74e425661f2e3dcb3906eb912ed7c5/base/src/org/compiere/print/ReportEngine.java#L909
