### ISSUE TITLE
[Bug Report] Class not found java.lang.NoClassDefFoundError when use  adempiereMonitor

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3896]
## Bug report
Class not found java.lang.NoClassDefFoundError when use  adempiereMonitor

#### Steps to reproduce
1.- Build the Adempiere binary from current develop 

#### Screenshot or Gif

![image](https://user-images.githubusercontent.com/786968/171242459-20728f9f-c7e2-40b5-9c56-055335b19730.png)

```java.lang.NoClassDefFoundError: Could not initialize class org.adempiere.legacy.apache.ecs.ECSDefaults
	at org.adempiere.legacy.apache.ecs.GenericElement.<init>(GenericElement.java:62)
	at org.adempiere.legacy.apache.ecs.ElementAttributes.<init>(ElementAttributes.java:40)
	at org.adempiere.legacy.apache.ecs.ConcreteElement.<init>(ConcreteElement.java:58)
	at org.adempiere.legacy.apache.ecs.MultiPartElement.<init>(MultiPartElement.java:38)
	at org.adempiere.legacy.apache.ecs.xhtml.html.<init>(html.java:41)
	at org.compiere.util.WebDoc.<init>(WebDoc.java:141)
	at org.compiere.util.WebDoc.create(WebDoc.java:60)
	at org.compiere.util.WebDoc.create(WebDoc.java:127)
	at org.compiere.web.AdempiereMonitor.createSummaryPage(AdempiereMonitor.java:494)
	at org.compiere.web.AdempiereMonitor.doGet(AdempiereMonitor.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624)
	at org.compiere.web.AdempiereMonitorFilter.doFilter(AdempiereMonitorFilter.java:108)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:711)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:418)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:675)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:410)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

#### Expected behavior
Adempiere Monitor should work smoothly as before

#### Other relevant information
- Your OS: macOS 
- Java version:  11
- ADempiere version: last develop 394
- Browser: safari
- DB Provider: PG
- DB version: 13

#### Additional context

Bug introduced by refactoy Rename packages of apache wrapper to legacy #3870

**Comment by e-Evolution** [comment]
@yamelsenih I found other error when link in:

Adempiere mobile 
Web Store , Request
ADempiere Server Management

here the error :

![image](https://user-images.githubusercontent.com/786968/171255079-045840be-79ce-4d16-8369-89aa0d9a2af0.png)

![image](https://user-images.githubusercontent.com/786968/171255137-5d75ea64-b7e8-4af4-a492-7b0c7ba13194.png)

![image](https://user-images.githubusercontent.com/786968/171255171-3689bc92-77af-4ba4-b632-e4824ba84181.png)
