### ISSUE TITLE
ZK Tomcat-Debug in Eclipse not Possible

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#4016]
## Bug report
It is not possible to run a Tomcat Server from Eclipse.
This was possible some time ago.
I haven't found the specific commit that disrupted the launching of a Tomcat Server from Eclipse.

#### Steps to reproduce
- Create a Tomcat v9.0 Server on Eclipse.
- Set ports and timeouts so there are no conflicts 
- In launch configuration/VM Arguments add entry for ADEMPIERE_HOME and PropertyFile
- In launch configuration/Classpath, add libraries (JasperReportsTools, tools/lib, zkwebui/WEB-INF/lib)
- In launch configuration/Environment, set ADEMPIERE_APPS_TYPE to tomcat
- Create a run configuration referencing the Tomcat server
- Run the run configuration

#### Screenshot or Gif
Server configuration:
![imagen](https://user-images.githubusercontent.com/1789408/200409564-380a5e9e-f98f-471e-99cf-437a3ea580ec.png)

Launch configuration/VM Arguments:
![imagen](https://user-images.githubusercontent.com/1789408/200409844-d17baa62-85c2-4328-a72b-5b17b4b5434c.png)

Launch configuration/Classpath:
![imagen](https://user-images.githubusercontent.com/1789408/200410224-48283a32-d04e-416b-90f8-8b28010130ef.png)

Launch configuration/Environment:
![imagen](https://user-images.githubusercontent.com/1789408/200410123-a1e0ecbb-e60a-47d8-812d-db01759b999d.png)

Error on Eclipse console:
![imagen](https://user-images.githubusercontent.com/1789408/200409680-ace59005-d7f4-4f3c-95a5-05c295a26ab8.png)

```
INFORMACIÓN: Starting Servlet engine: [Apache Tomcat/9.0.50]
nov. 07, 2022 2:41:44 P. M. org.apache.tomcat.util.scan.StandardJarScanner processURLs
ADVERTENCIA: Fallo al escanear  [file:/home/westfalia/Adempiere/westfaliaRepository_2022-06/adempiere/tools/lib/icepdf-core.jar] desde la herarquia classloader hierarchy
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:383)
	at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:318)
	at org.apache.tomcat.util.scan.StandardJarScanner.doScanClassPath(StandardJarScanner.java:282)
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:233)
	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:2136)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1289)

```

#### Other relevant information
- Your OS: Ubuntu 18.04
- Java version: OpenJDK 11
- ADempiere version: 393
- Tomcat version: 9.0
- Eclipse version: Version: 2022-06 (4.24.0), Build id: 20220609-1112

**Comment by e-Evolution** [comment]
@marcalwestf , Mario you do not need to add that library since it is inside the Adempiere/tomcat/lib directory, so for your service to start you must include it in your classpath inside Eclipse and should work.

**Comment by e-Evolution** [comment]
My setup for Eclipse and Tomcat 9:

![image](https://user-images.githubusercontent.com/786968/200437496-796ea76d-e67a-4b12-bb96-bddf873456df.png)

Define mi Tomcat with CATALINA_HOME

![image](https://user-images.githubusercontent.com/786968/200437615-e33735ca-e7b3-4134-9f64-591b79037cc3.png)

![image](https://user-images.githubusercontent.com/786968/200437693-4f521cbf-ea35-4962-bc8c-356fe831566e.png)

Change my CATALINA_BASE:

![image](https://user-images.githubusercontent.com/786968/200438267-f2ddefec-0e99-448c-bd19-fb75f664dfea.png)

Change my deployment Directory

![image](https://user-images.githubusercontent.com/786968/200438501-ca0b7ff6-b9e3-4bab-a486-5da4bf9d4948.png)

Adding my Adempiere.properties setting 

![image](https://user-images.githubusercontent.com/786968/200438964-f01b7ccd-aca8-43e4-b1e7-65dc7a32cbdc.png)

Adding ADEMPIERE_APPS_TYPE as an environment variable:

![image](https://user-images.githubusercontent.com/786968/200439296-985dde00-71ec-46df-865d-07537e9563df.png)

![image](https://user-images.githubusercontent.com/786968/200439330-4f136e6c-93a0-467a-b840-5cbbba083a8a.png)

Execute the Tomcat Server in Debug Mode :

![image](https://user-images.githubusercontent.com/786968/200440290-700ed2ee-61a7-4fae-b51d-4a6ad0f11cc2.png)


ADempiere Tomcat Server Start Log  working perfectly 

![image](https://user-images.githubusercontent.com/786968/200440250-e79c5149-4a44-48f4-ac6a-d1b847ae9a38.png)

![image](https://user-images.githubusercontent.com/786968/200441385-33d0bdfb-1179-419a-932d-1b3aaf9a908f.png)


So configuring Eclipse to deploy Webui is very simple configuring everything correctly.

kind regards

@e-Evolution , Victor

**Comment by marcalwestf** [comment]
thank you very much Victor, I will try out and let you know!!!
