### ISSUE TITLE
[Bug Report] Error when try print any Jasper Report from Swing client

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#4056]
## Bug report
Error when try print any Jasper Report from Swing client
introducing by @yamelsenih and @marcalwestf  with #4026

#### Steps to reproduce
1.- Try print any jasper report with is Print Preview Yes

15:05:03.865 ADialog.error: null - ProcessError null [19]
===========> ProcessUtil.startJavaProcess: org.compiere.jr.report.ReportStarter [75]
java.lang.NullPointerException
	at org.compiere.jr.report.ReportStarter.startProcess(ReportStarter.java:666)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:171)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:116)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:610)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:392)
	at java.base/java.lang.Thread.run(Thread.java:829)

#### Link to minimal reproduction

Last 394 release

#### Expected behavior
the jasper report should work as before.

#### Other relevant information
- Your OS: macOS
- Java version: 11
- ADempiere version: 3.9.4
- DB Provider: PG
- DB version: 15.1

#### Additional context
Testing Swing Client

**Comment by marcalwestf** [comment]
Tested on Swing with the same configuration as #4026.
Result:
![imagen](https://user-images.githubusercontent.com/1789408/215620394-b89325c8-8e55-4680-a2d5-4278e57f4598.png)

**Comment by marcalwestf** [comment]
The problem: in Swing _ReportStarter.startProcess()_ line 664 `getReportViewerProvider()` returns **null**:
![imagen](https://user-images.githubusercontent.com/1789408/215621962-2a9ff58d-a870-4919-a0fa-ebf7e1f34ba5.png)
..if ReportStarter.startProcess() is changed in line 664 to
`JRViewerProvider viewerLauncher = getReportViewerProvider()==null? new SwingJRViewerProvider():getReportViewerProvider();`

..then the Jasper Report is displayed in Swing:
![imagen](https://user-images.githubusercontent.com/1789408/215622718-9ac92c3f-dd15-4aac-a82f-aebd558f1980.png)

![imagen](https://user-images.githubusercontent.com/1789408/215622642-390f31e9-49aa-43ce-af70-bc888ca25ff3.png)

I still have to test with Tomcat, before issuing a pull request.

**Comment by marcalwestf** [comment]
Running Tomcat with these changes, the Jasper Report is displayed on ZK:
![imagen](https://user-images.githubusercontent.com/1789408/215805494-6fa978c5-4e13-41c9-a66b-01b17a9e0f0f.png)

I wonder if there is another, more basic way of solving this by differentiating Swing or ZK from the start.
Anyway, this would fix the error.
