### ISSUE TITLE
[Bug Report] Error when try Import Business Partner, the problem is that PG 15 is more strict with SQL statement

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#4113]
## Bug report
Error when try Import Business Partner, the problem is that PG 15 is more strict with SQL statement

#### Steps to reproduce
1.- Steps to reproduce
2.- Create two Import Import Business Partner lines
3.- Try processing the lines
4.- The error SQL syntax is throw

===========> Query.list: SELECT IsPayrollAccount,IsACH,Created,Updated,IsActive,A_Name,A_Zip,A_State,A_Street,A_City,CreditCardType,A_EMail,A_Country,BankAccountType,CreditCardNumber,AccountNo,A_Ident_DL,CreditCardVV,RoutingNo,R_AvsZip,R_AvsAddr,A_Ident_SSN,BPBankAcctUse,AD_Org_ID,C_BP_BankAccount_ID,CreatedBy,C_BPartner_ID,CreditCardExpMM,C_Bank_ID,AD_User_ID,UpdatedBy,CreditCardExpYY,UUID,IBAN,AD_Client_ID FROM C_BP_BankAccount WHERE (C_BPartner_ID=? AND IsACH = 'Y' AND EXISTS (SELECT 1 FROM I_BPartner i WHERE i.I_BPartner_ID = 1000438AND i.A_Name = C_BP_BankAccount.A_Name)) AND IsActive=? [10325]
org.postgresql.util.PSQLException: ERROR: trailing junk after numeric literal at or near "1000438A"
  Position: 513; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at jdk.proxy2/jdk.proxy2.$Proxy6.executeQuery(Unknown Source)
	at org.compiere.model.Query.createResultSet(Query.java:781)
	at org.compiere.model.Query.list(Query.java:275)
	at org.compiere.model.Query.list(Query.java:256)
	at org.compiere.model.MBPBankAccount.getByPartner(MBPBankAccount.java:65)
	at org.compiere.process.ImportBPartner.doIt(ImportBPartner.java:739)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)

#### Screenshot or Gif
<img width="1728" alt="image" src="https://github.com/e-Evolution/adeos/assets/786968/71272c3a-ed1a-4067-a033-eeb33b1e1817">

#### Expected behavior
The process should can import

#### Other relevant information
- Your OS: macos 
- Java version: 11
- ADempiere version: 3.9.4
- Browser safari
- DB Provider: PostgreSQL
- DB version: 15

**Comment by EdwinBetanc0urt** [comment]
Greetings @e-Evolution, the error is in the line https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/process/ImportBPartner.java#L733

![imagen](https://github.com/adempiere/adempiere/assets/20288327/99eeb4e5-5fb9-40d1-8366-b968d8e1bc04)

As can be seen, the id of the business partner is being concatenated, but no space is left before the `AND` within the text value. So that line should be as follows:


```java
whereClause = "IsACH = 'Y' AND EXISTS (SELECT 1 FROM I_BPartner i WHERE i.I_BPartner_ID = " + importPartner.getI_BPartner_ID() + " AND i.A_Name = C_BP_BankAccount.A_Name";
```

Something similar to what happened to me at https://github.com/adempiere/adempiere/pull/4098.
