### ISSUE TITLE
Accounting FactLine updateReverseLine SQLException for InventoryMove

### ISSUE THREAD

**Issue by bpali** [adempiere/adempiere#416]
Say you have a completed and posted Inventory Move document.

If you void it and try to post the reversed document it will fail with "Posting Error (Original Inventory Move not posted yet)"

This happens to any reversed Inventory Move document because of the following SQL Exception
```java
===========> FactLine.updateReverseLine: SELECT * FROM Fact_Acct WHERE C_AcctSchema_ID=? AND AD_Table_ID=? AND Record_ID=? AND Line_ID=? AND Account_ID=? AND Qty=? AND M_Locator_ID=? [17]
org.postgresql.util.PSQLException: No value specified for parameter 7.; State=22023; ErrorCode=0
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:223)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:244)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy0.executeQuery(Unknown Source)
	at org.compiere.acct.FactLine.updateReverseLine(FactLine.java:1079)
	at org.compiere.acct.Doc_Movement.createFacts(Doc_Movement.java:167)
	at org.compiere.acct.Doc.postLogic(Doc.java:759)
	at org.compiere.acct.Doc.post(Doc.java:643)
	at org.compiere.acct.Doc.postImmediate(Doc.java:351)
	at org.compiere.session.ServerBean.postImmediate(ServerBean.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

The SQL Exception strikes beause parameter 7 was not set.

Inside method org.compiere.acct.FactLine.updateReverseLine parameter set expressions

```java
pstmt.setInt(5, m_acct.getAccount_ID());
pstmt.setBigDecimal(6, quantity.negate());
// MZ Goodwill
// for Inventory Move
if (MMovement.Table_ID == AD_Table_ID)
    pstmt.setInt(6, getM_Locator_ID());
// end MZ
```

should be like this

```java
pstmt.setInt(5, m_acct.getAccount_ID());
pstmt.setBigDecimal(6, quantity.negate());
// MZ Goodwill
// for Inventory Move
if (MMovement.Table_ID == AD_Table_ID)
    pstmt.setInt(7, getM_Locator_ID());
// end MZ
```

This bug was introduced in the following changeset
Commit: 09a0aa21164ebeaab1b488af87dcd7f08a7cc61b [09a0aa2]
Parents: ebe2eb93cb
Author: eEvolution author Victor Perez <victor.perez@e-evolution.com>
Date: Saturday, 08 November, 2014 9:26:30 PM
Solve issue with revert document, now to find of original fact act is necessary quantity transaction

when this line was modified `+ " AND Line_ID=? AND Account_ID=? AND Qty=?";` 
and this line added `pstmt.setBigDecimal(6, quantity.negate());`

**Comment by bpali** [comment]
Bugfix pull request was merged.

Issue solved

**Comment by marcalwestf** [comment]
thanks Bogdan. weĺl test it.
