### ISSUE TITLE
Table ad_reportview_trl with wrong primary key

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#425]
After generation of seed and checking the primary key definition of all translation tables ( the ones ending with _trl), it can be observed that table ad_reportview_trl has a wrong primary key defined.
Instead of being composed of (ad_reportview_id, ad_language), ot is only composed of (ad_reportview_id).

This leads during the execution of the Migration process to an error which disables setting vallues to all transaction tables.

**Comment by e-Evolution** [comment]
Hi @yamelsenih , this commit introducing new error, before this script work without some issue, now throw this error

MMigrationStep.apply: Applying migration step: Migration 143 - Special Tables are with hardcode instead use attribute #390 - 3.8.0#002 (D) ; Step: 90; Type: AD.  [1]
-----------> POInfo.loadAdditionalAttributes: Table [AD_Table] - Attribute [IsIgnoreMigration] Not found [1]
-----------> POInfo.loadAdditionalAttributes: Table [AD_Table] - Attribute [IsIgnoreMigration] Not found [1]
===========> MTable.load: AD_Table_ID=717, SQL=SELECT ACTriggerLength,AD_Client_ID,AD_Org_ID,AD_Table_ID,AD_Val_Rule_ID,AD_Window_ID,AccessLevel,CopyColumnsFromTable,Created,CreatedBy,Description,EntityType,Help,ImportTable,IsActive,IsCentrallyMaintained,IsChangeLog,IsDeleteable,IsDocument,IsHighVolume,IsIgnoreMigration,IsSecurityEnabled,IsView,LoadSeq,Name,PO_Window_ID,ReplicationType,TableName,Updated,UpdatedBy FROM AD_Table WHERE AD_Table_ID=? [1]
org.postgresql.util.PSQLException: ERROR: column "isignoremigration" does not exist
  Position: 258; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by yamelsenih** [comment]
Hi @e-Evolution this error alredy resolved.

Please test it.

Best Regard
