### ISSUE TITLE
Error when try auto generate print format based on report view with multiples companies

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#436]
The problem is that print format name is build based on original print format , this is ok when work a single company but when try create same report in second company this fails because detect violation constraints.

===========> DB.executeUpdate: INSERT INTO AD_PrintFormat (AD_Client_ID,AD_Org_ID,AD_PrintColor_ID,AD_PrintFont_ID,AD_PrintFormat_ID,AD_PrintPaper_ID,AD_ReportView_ID,AD_Table_ID,Created,CreatedBy,FooterMargin,HeaderMargin,IsActive,IsDefault,IsForm,IsStandardHeaderFooter,IsSummary,IsTableBased,Name,Updated,UpdatedBy) VALUES (1000007,1000015,100,130,1000360,100,117,413,TO_TIMESTAMP('2016-06-17 13:13:04','YYYY-MM-DD HH24:MI:SS'),1024714,0,0,'Y','N','N','Y','N','Y','Saldos Abiertos',TO_TIMESTAMP('2016-06-17 13:13:04','YYYY-MM-DD HH24:MI:SS'),1024714) [POSave_2e9c5de6-88a3-4ded-b83e-23d2a2178462] [271]
org.postgresql.util.PSQLException: ERROR: llave duplicada viola restricción de unicidad «ad_printformat_name»
Detail: Ya existe la llave (ad_client_id, ad_table_id, name)=(1000007, 413, Saldos Abiertos).; State=23505; ErrorCode=0
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
at com.sun.proxy.$Proxy69.executeUpdate(Unknown Source)
at org.compiere.util.DB.executeUpdate(DB.java:1032)
at org.compiere.util.DB.executeUpdate(DB.java:894)
at org.compiere.util.DB.executeUpdate(DB.java:881)
at org.compiere.model.PO.saveNew(PO.java:2820)
at org.compiere.model.PO.save(PO.java:2157)
at org.compiere.print.MPrintFormat.createFromReportView(MPrintFormat.java:575)
at org.compiere.print.ReportEngine.get(ReportEngine.java:1227)
at org.compiere.print.ReportCtl.startStandardReport(ReportCtl.java:207)
at org.compiere.print.ReportCtl.start(ReportCtl.java:158)
at org.compiere.print.ReportCtl.start(ReportCtl.java:104)
at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:468)
at org.compiere.apps.ProcessCtl.process(ProcessCtl.java:217)

**Comment by e-Evolution** [comment]
Commit 8eb6e39
