### ISSUE TITLE
Translation tables does not support rollback in Migration

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#440]
If a field is created, automatically it create a translation record but if the field is deleted it remove automatically, then when the migration process try remove the translation record, it does not exists and throw a exception like show the follow:
<pre>
===========> MigrationStepApply.process: Migration 153 - Mail setup is hardcoded #402 - 3.8.0#002 (D) ; Step: 1360; Type: AD. Application failed: org.adempiere.exceptions.AdempiereException: Migration 153 - Mail setup is hardcoded #402 - 3.8.0#002 (D) ; Step: 1360; Type: AD. Step 1360, Record 5887 was not found in table Field Trl (127). [85]
org.adempiere.exceptions.AdempiereException: Migration 153 - Mail setup is hardcoded #402 - 3.8.0#002 (D) ; Step: 1360; Type: AD. Step 1360, Record 5887 was not found in table Field Trl (127).
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:266)
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:240)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:497)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:221)
	at org.compiere.process.MigrationStepApply.doIt(MigrationStepApply.java:65)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:679)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:420)
</pre>

**Comment by yamelsenih** [comment]
When a step have **Delete Action** and it already applied, if you try rollback then it should be re-created but the rollback process does not re-create it.
