### ISSUE TITLE
java.sql.SQLSyntaxErrorException: ORA-00904: "WAREHOUSE": invalid identifier

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#459]
Hi,

When try to open the lookup window for BOM components in product creation window i get the following exception.

```
-----------> InfoProductPanel.refresh: SELECT M_Warehouse_ID, Warehouse, sum(QtyAvailable), sum(QtyOnHand), sum(QtyReserved), sum(QtyOrdered) FROM  M_PRODUCT_STOCK_V  WHERE (QtyOnHand <> 0 OR QtyAvailable <> 0 OR QtyReserved <> 0 OR QtyOrdered <> 0) AND M_Product_ID = ? AND M_PRODUCT_STOCK_V.AD_Client_ID IN(0,1000000) AND M_PRODUCT_STOCK_V.AD_Org_ID IN(0,1000000) Group By M_Warehouse_ID, Warehouse  Order By sum(QtyOnHand) DESC, Warehouse  [35]
java.sql.SQLSyntaxErrorException: ORA-00904: "WAREHOUSE": invalid identifier
; State=42000; ErrorCode=904
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy3.executeQuery(Unknown Source)
	at org.adempiere.webui.panel.InfoProductPanel.refresh(InfoProductPanel.java:702)
	at org.adempiere.webui.panel.InfoProductPanel.recordSelected(InfoProductPanel.java:2075)
```

I think the statInit() has the problem with the Warehouse, in InfoProductPanel.java.
I looked for Warehouse in M_PRODUCT_STOCK_V but I found only WAREHOUSENAME, M_WAREHOUSE_ID in the responsible view.

AD v 3.8.0

**Comment by e-Evolution** [comment]
Issue was solved with  c8be9aedce273d9de1e4d280644c265dd1c9d97a
