### ISSUE TITLE
The mandatory parameter new logic not working 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#463]
The business case to replicate.

1.- Create a new Inventory Import 
2.-Execute of process to import inventory
3.- Fill process parameter list
4.-Execute of process 

The system show warehouse is mandatory , this not should be show so that the information was filled 

![Uploading Captura de pantalla 2016-07-27 a las 10.37.43 a.m..png…]()

bug introducing in #325

**Comment by yamelsenih** [comment]
Hi @e-Evolution after it i find a error
![issue226](https://cloud.githubusercontent.com/assets/2333092/17199790/a22235b8-544d-11e6-993a-bc80840e657f.png)

<pre>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.grid.ed.VLocator.setValue(VLocator.java:317)
	at org.compiere.grid.ed.VLocator.setValue(VLocator.java:293)
	at org.compiere.grid.ed.VLocator.setDefault_Locator_ID(VLocator.java:633)
	at org.compiere.grid.ed.VLocator.<init>(VLocator.java:176)
	at org.compiere.grid.ed.VEditorFactory.getEditor(VEditorFactory.java:213)
	at org.compiere.grid.GridController.init(GridController.java:425)
	at org.compiere.grid.GridController.activate(GridController.java:641)
	at org.compiere.apps.APanel.stateChanged(APanel.java:1475)
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
	at org.compiere.grid.VTabbedPane.setSelectedIndex(VTabbedPane.java:314)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6532)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>
