### ISSUE TITLE
Process to reverse sales transaction does not work(POS)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#498]
Trying to reverse a sales transaction generates the following error: "QueryMoreThanOneRecordsFound"
![image](https://cloud.githubusercontent.com/assets/9578152/17713470/18b5cc3c-63c9-11e6-8372-66196c71e310.png)

<pre>
ReverseTheSalesTransaction.process: QueryMoreThanOneRecordsFound [69]
org.adempiere.exceptions.DBException: QueryMoreThanOneRecordsFound
    at org.compiere.model.Query.firstId(Query.java:409)
    at org.compiere.model.Query.firstIdOnly(Query.java:380)
    at org.adempiere.pos.process.ReverseTheSalesTransaction.getRMATypeId(Unknown Source)
    at org.adempiere.pos.process.ReverseTheSalesTransaction.cancelShipments(Unknown Source)
    at org.adempiere.pos.process.ReverseTheSalesTransaction.doIt(Unknown Source)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
    at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:679)
    at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:420)
    at org.compiere.apps.ProcessCtl.process(ProcessCtl.java:217)
    at org.adempiere.webui.apps.ProcessDialog.runProcess(ProcessDialog.java:389)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:209)
    at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
    at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
    at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
</pre>

**Comment by yamelsenih** [comment]
This was fixed
