### ISSUE TITLE
Error in  process to Generate invoices from shipments

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#514]
not generate invoice by filling the parameter when entering organization to organization *, the process establishes the organization context in the invoice generated.
![image](https://cloud.githubusercontent.com/assets/9578152/17758494/e49dac08-64bd-11e6-8b02-9460714d4bbf.png)

**Comment by yamelsenih** [comment]
Hi @wdtz please tell me what is the problem

**Comment by yamelsenih** [comment]
Hi @wdtz it will should fix adding a **Org Trx** optional to process.

**Comment by yamelsenih** [comment]
Hi @wdtz it has been resolved, see the follow:

- Now you can set the organization for transaction, see the pic:
![arbol_49](https://cloud.githubusercontent.com/assets/2333092/26707972/93cd8cee-4716-11e7-8f4b-1a15c822ef09.png)
- Also you can choice if is added a line for reference to shipment on invoice or not
The result is:
![arbol_50](https://cloud.githubusercontent.com/assets/2333092/26707988/b60ae6c6-4716-11e7-9a11-59b62bc41b4b.png)
- Also if you select a shipment the organization is not a filter for shipment

Please test it and if exists a bug just reopen issue for resolve

**Comment by e-Evolution** [comment]
Error when try apply migration script 

16:18:54.832 MigrationApply.addLog: 0 - null - null - Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
16:18:54.832 MigrationApply.addLog: 0 - null - null - Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
===========> MigrationApply.process: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
org.adempiere.exceptions.AdempiereException: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: ""
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: ""
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:272)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:618)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.compiere.model.MMigrationStep.stringToObject(MMigrationStep.java:429)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:578)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

16:18:54.835   MIssue.create: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
16:18:54.835   MIssue.create: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
16:18:54.835   GridField.loadLookup: (SystemStatus) [1]
16:18:54.835   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: "" [1]
org.adempiere.exceptions.AdempiereException: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: ""
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: ""
	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:272)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:618)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.compiere.model.MMigrationStep.stringToObject(MMigrationStep.java:429)
	at org.compiere.model.MMigrationStep.applyPO(MMigrationStep.java:578)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:229)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

16:18:59.894 Trx.rollback: **** TrxRun_e76296f3-c93c-4873-a04a-e8a94252339a [1]
16:18:59.894 Trx.rollback: **** TrxRun_e76296f3-c93c-4873-a04a-e8a94252339a [1]
16:18:59.897 Msg.initMsg: Records=1455 - en_US [1]
16:18:59.897 Msg.initMsg: Records=1455 - en_US [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/390/install/build/Adempiere/migration/380lts-release/02630_514_FixedOrgTrx_GenerateInvoiceFromInOut.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 2630 - Error in process to Generate invoices from shipments #514 - 3.9.0 (D) ; Step: 130; Type: AD. Application failed: java.lang.NumberFormatException: For input string: ""
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:294)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

16:18:59.898   MIssue.create: Loading Migration from XML failed. [1]
16:18:59.898   MIssue.create: Loading Migration from XML failed. [1]
16:18:59.898   GridField.loadLookup: (SystemStatus) [1]
16:18:59.898   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]

**Comment by yamelsenih** [comment]
Hi, it is worked?

**Comment by yamelsenih** [comment]
it is solved in https://github.com/adempiere/adempiere/commit/5ce88bd7bef5d3e2eca79630db7d9a1b2dfcfdf0
