### ISSUE TITLE
ASP_Browse does not exist

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#569]
If a client is checked like **Is ASP** the i get the follow error when login into ADempiere, also the option menu is not showed.

![issue2014](https://cloud.githubusercontent.com/assets/2333092/18028839/2b190c50-6c56-11e6-92d2-ce11e9cc2a4a.png)

<pre>
===========> MRole.getBrowseAccess: SELECT AD_Browse_ID, IsReadWrite FROM AD_Browse_Access WHERE AD_Role_ID=? AND IsActive='Y'   AND (   AD_Browse_ID IN (               SELECT b.AD_Browse_ID                 FROM ASP_Browse b, ASP_Level l, ASP_ClientLevel cl                WHERE b.ASP_Level_ID = l.ASP_Level_ID                  AND cl.AD_Client_ID = 11                 AND cl.ASP_Level_ID = l.ASP_Level_ID                  AND b.IsActive = 'Y'                  AND l.IsActive = 'Y'                  AND cl.IsActive = 'Y'                  AND b.ASP_Status = 'S')         OR AD_Browse_ID IN (               SELECT AD_Browse_ID                 FROM ASP_ClientException ce                WHERE ce.AD_Client_ID = 11                 AND ce.IsActive = 'Y'                  AND ce.AD_Browse_ID IS NOT NULL                  AND ce.ASP_Status = 'S')        )    AND AD_Browse_ID NOT IN (           SELECT AD_Browse_ID             FROM ASP_ClientException ce            WHERE ce.AD_Client_ID = 11             AND ce.IsActive = 'Y'              AND ce.AD_Browse_ID IS NOT NULL              AND ce.ASP_Status = 'H') [14]
org.postgresql.util.PSQLException: ERROR: relation "asp_browse" does not exist
  Position: 144; State=42P01; ErrorCode=0
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
    at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
    at org.compiere.model.MRole.getBrowseAccess(MRole.java:1826)
    at org.compiere.model.MTree.getNodeDetail(MTree.java:541)
    at org.compiere.model.MTree.addToTree(MTree.java:315)
    at org.compiere.model.MTree.loadNodes(MTree.java:241)
    at org.compiere.model.MTree.<init>(MTree.java:120)
    at org.compiere.model.MTree.<init>(MTree.java:101)
    at org.compiere.grid.tree.VTreePanel.initTree(VTreePanel.java:252)
    at org.compiere.apps.AMenu.<init>(AMenu.java:164)
    at org.compiere.apps.AEnv.logout(AEnv.java:749)
    at org.compiere.apps.AMenu.logout(AMenu.java:543)
    at org.compiere.apps.AEnv.actionPerformed(AEnv.java:393)
    at org.compiere.apps.AMenu.actionPerformed(AMenu.java:611)
</pre>

**Comment by testiranje1234** [comment]
![asp_browseaaa](https://cloud.githubusercontent.com/assets/26572325/25312536/41425d4c-281c-11e7-8517-3bf7dcadf72c.png)

last build from 19042017 I was download, install and test dont have asp_browse table on oracle too

**Comment by yamelsenih** [comment]
Hi @testiranje1234 the application dictionary changes is on **migration/380lts-release/02380_569_Add_ASP_Support_To_SB.xml** you should apply it XML for make working it.

Best Regard
