### ISSUE TITLE
The Generate Outbound Order based on Demands and Sales Orders not work

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#584]

**Comment by e-Evolution** [comment]
16:17:08.368           Trx.close: POSave_8384cdd2-429a-4722-88a5-558aa5755716 [103]
===========> VBrowser.run: SELECT DISTINCT ol.C_OrderLine_ID AS C_OrderLine_C_OrderLine_ID, bpl.Name AS C_BPartner_Location_Name, p.Value AS M_Product_Value, pc.Name AS M_Product_Category_Name, ol.C_Order_ID AS C_OrderLine_C_Order_ID, p.Name AS M_Product_Name, ol.LineNetAmt AS C_OrderLine_LineNetAmt, o.DatePromised AS C_Order_DatePromised, o.DateOrdered AS C_Order_DateOrdered, o.M_Warehouse_ID AS C_Order_M_Warehouse_ID, p.M_Locator_ID AS M_Product_M_Locator_ID, ol.M_Product_ID AS C_OrderLine_M_Product_ID, p.C_UOM_ID AS M_Product_C_UOM_ID, p.M_Product_Category_ID AS M_Product_M_Product_Category_ID, p.M_Product_Group_ID AS P_M_Product_Group_ID, p.M_Product_Class_ID AS P_M_Product_Class_ID, p.M_Product_Classification_ID AS P_M_Product_Classification_ID, ol.QtyOrdered AS C_OrderLine_QtyOrdered, COALESCE(ol.Qty * p.weight, 0.0) AS C_Order_Weight, COALESCE(ol.QtyOrdered * p.volume, 0.0) AS C_Order_Volume, o.C_Order_ID AS C_Order_C_Order_ID, o.DocumentNo AS C_Order_DocumentNo, o.POReference AS C_Order_POReference, o.PriorityRule AS C_Order_PriorityRule, o.C_Campaign_ID AS C_Order_C_Campaign_ID, o.C_Project_ID AS C_Order_C_Project_ID, o.C_DocType_ID AS C_Order_C_DocType_ID, o.SalesRep_ID AS C_Order_SalesRep_ID, o.C_BPartner_ID AS C_Order_C_BPartner_ID, bpl.C_SalesRegion_ID AS C_BPartner_Location_C_SalesRegion_ID, o.InvoiceRule AS C_Order_InvoiceRule, o.PaymentRule AS C_Order_PaymentRule, o.DeliveryRule AS C_Order_DeliveryRule, o.DeliveryViaRule AS C_Order_DeliveryViaRule, o.M_Shipper_ID AS C_Order_M_Shipper_ID, o.FreightCostRule AS C_Order_FreightCostRule, o.M_FreightCategory_ID AS C_Order_M_FreightCategory_ID, o.IsDropShip AS C_Order_IsDropShip, l.C_Country_ID AS C_Location_C_Country_ID, l.Postal AS C_Location_Postal, l.C_Region_ID AS C_Location_C_Region_ID, l.RegionName AS C_Location_RegionName, l.C_City_ID AS C_Location_C_City_ID, l.City AS C_Location_City, bp.Name AS C_BPartner_Name, bp.SOCreditStatus AS C_BPartner_SOCreditStatus, bp.SO_CreditLimit AS C_BPartner_SO_CreditLimit, bp.SO_CreditUsed AS C_BPartner_SO_CreditUsed, ol.Line AS C_OrderLine_Line FROM  C_Order o INNER JOIN C_OrderLine ol ON (ol.C_Order_ID=o.C_Order_ID) INNER JOIN C_BPartner bp ON (bp.C_BPartner_ID=o.C_BPartner_ID) INNER JOIN C_BPartner_Location bpl ON (bpl.C_BPartner_Location_ID=o.C_BPartner_Location_ID) INNER JOIN C_Location l ON (l.C_Location_ID=bpl.C_Location_ID) INNER JOIN M_Product p ON (p.M_Product_ID=ol.M_Product_ID) INNER JOIN M_Product_Category pc ON (pc.M_Product_Category_ID=p.M_Product_Category_ID)  WHERE IsSOTrx='Y' AND DocStatus='CO' AND NOT EXISTS (SELECT 1 FROM WM_InOutBoundLine WHERE WM_InOutBoundLine.C_OrderLine_ID = ol.C_OrderLine_ID) AND o.DatePromised >= ?  AND o.AD_Client_ID IN(0,11) AND o.AD_Org_ID IN(0,11,12,50000,50002,50001,50004,50006,50005,50007) AND (o.C_Order_ID IS NULL OR o.C_Order_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 259 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (ol.C_OrderLine_ID IS NULL OR ol.C_OrderLine_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 260 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (bp.C_BPartner_ID IS NULL OR bp.C_BPartner_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 291 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (bpl.C_BPartner_Location_ID IS NULL OR bpl.C_BPartner_Location_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 293 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (l.C_Location_ID IS NULL OR l.C_Location_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 162 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (p.M_Product_ID IS NULL OR p.M_Product_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 208 AND AD_User_ID <> 100 AND IsActive = 'Y' )) AND (pc.M_Product_Category_ID IS NULL OR pc.M_Product_Category_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 209 AND AD_User_ID <> 100 AND IsActive = 'Y' )) ORDER BY 8,24 [103]
org.postgresql.util.PSQLException: ERROR: column ol.qty does not exist
  Position: 785; State=42703; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:616)
