### ISSUE TITLE
NPE when trying to display a Work Order in Material Transactions View

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#596]
How to reproduce:
Log 
1. in as User Admin
2. Create a new project "Make a Robot" and set it as Work order
3. Goto project phase tab and enter a planned material of rake-metal on line 10.
4. Add up some inventory of rake-metal in order to have enough QOH
5. Go to issue to project process and select the project "Make a Robot", also a project line for rake-metal product and a locator.
6. Open Material Transactions View and select transaction with Work Order

Result: NPE
![20161006_material_transactions](https://cloud.githubusercontent.com/assets/1789408/19123669/c25b148c-8aec-11e6-855f-664a5e6bd86f.png)

**Comment by marcalwestf** [comment]
Related to https://github.com/adempiere/adempiere/issues/443

**Comment by yamelsenih** [comment]
Hi @marcalwestf , i have a similar bug when i try zoon a record and it don't hava access, see the log:
<pre>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.model.GridWindowVO.create(GridWindowVO.java:167)
	at org.compiere.apps.AEnv.getMWindowVO(AEnv.java:910)
	at org.compiere.apps.APanel.initPanel(APanel.java:718)
	at org.compiere.apps.AWindow.initWindow(AWindow.java:102)
	at org.compiere.grid.ed.VLookup.actionZoom(VLookup.java:1661)
	at org.compiere.grid.ed.VLookup.actionPerformed(VLookup.java:864)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>
