### ISSUE TITLE
Error in SmallViewController 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#602]
Error introducing in pull request https://github.com/adempiere/adempiere/pull/582

This process not are work.

![captura de pantalla 2016-10-12 a la s 17 33 58](https://cloud.githubusercontent.com/assets/786968/19330503/6d2e8b3e-90a4-11e6-8c8b-43d6e35981af.png)

Not Show rightly of parameters and fail the mandatory parameters 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.compiere.apps.ProcessPanel.setComponentVisibility(ProcessPanel.java:381)
at org.adempiere.controller.SmallViewController.dynamicDisplay(SmallViewController.java:549)
at org.compiere.apps.ProcessPanel.dynamicDisplay(ProcessPanel.java:360)
at org.adempiere.controller.SmallViewController.processNewValue(SmallViewController.java:802)
at org.adempiere.controller.SmallViewController.fieldChange(SmallViewController.java:631)
at org.adempiere.controller.SmallViewController.propertyChange(SmallViewController.java:835)
at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
at org.compiere.model.GridField.setValue(GridField.java:1364)
at org.adempiere.controller.SmallViewController.vetoableChange(SmallViewController.java:527)
at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
at org.compiere.grid.ed.VCheckBox.actionPerformed(VCheckBox.java:235)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.Component.processMouseEvent(Component.java:6535)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6300)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.compiere.apps.ProcessPanel.setComponentVisibility(ProcessPanel.java:381)
at org.adempiere.controller.SmallViewController.dynamicDisplay(SmallViewController.java:549)
at org.compiere.apps.ProcessPanel.dynamicDisplay(ProcessPanel.java:360)
at org.adempiere.controller.SmallViewController.processNewValue(SmallViewController.java:802)
at org.adempiere.controller.SmallViewController.fieldChange(SmallViewController.java:631)
at org.adempiere.controller.SmallViewController.propertyChange(SmallViewController.java:835)
at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
at org.compiere.model.GridField.setValue(GridField.java:1364)
at org.adempiere.controller.SmallViewController.vetoableChange(SmallViewController.java:527)
at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:375)
at java.beans.VetoableChangeSupport.fireVetoableChange(VetoableChangeSupport.java:271)
at javax.swing.JComponent.fireVetoableChange(JComponent.java:4534)
at org.compiere.grid.ed.VCheckBox.actionPerformed(VCheckBox.java:235)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
at java.awt.Component.processMouseEvent(Component.java:6535)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6300)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by marcalwestf** [comment]
I have the following weird behavior when calling the process _InventoryCountCreate_: when I call the process with the parameters _Locator_ and _Product Category_ empty (see image), the process gets nonetheless values for them in the _InventoryCountCreate.prepare()_ method, which is an error. 
This way, the process runs on wrong parameters.
It maybe point to the same error and can help finding the cause.
![201610015_wrong_process_parameters](https://cloud.githubusercontent.com/assets/1789408/19414559/b65e5418-930d-11e6-9d7f-23064f6dbbb0.png)

**Comment by yamelsenih** [comment]
Hi Víctor, please test it.
Best regards

**Comment by marcalwestf** [comment]
hi @yamelsenih , I downloaded https://github.com/adempiere/adempiere/commit/28248922057ce30958b3b2c8e1aa55fc1ab8437f and tested the case I stated before. The result remains the same: even if not filled in the parameter dialog, in the process some parameters are set with values.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i test it just now with https://github.com/adempiere/adempiere/commit/28248922057ce30958b3b2c8e1aa55fc1ab8437f and it is working, note that the **Simulation** flag is like **false** and **Create Payment** flag is **true**, see the image:
![issue52](https://cloud.githubusercontent.com/assets/2333092/19443269/3864e6fa-945a-11e6-8ccb-4372c6ab74d9.png)
