### ISSUE TITLE
Multiple select and delete window does not appear when there is no identifier selected in a created table

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#768]
When there is no identifier selected in a table and tries to delete records by pressing "Delete Selected Records" button, there is an exception and no pop-up dialog is appear.

Exception is as follows: 

===========> MLookupFactory.getLookup_TableDirEmbed: No Identifier records found: Primary_ID [38]
===========> MLookupFactory.getLookup_TableDirEmbed: No Identifier records found: Primary_ID  [38]
===========> CWindowToolbar.doOnClick: Could not invoke Toolbar listener method: onDeleteSelection() [38]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:383)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:347)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
caused by: java.lang.IllegalArgumentException: No SQL
	at org.compiere.util.DB.prepareStatement(DB.java:765)
	at org.compiere.util.DB.prepareStatement(DB.java:736)
	at org.compiere.util.DB.getSQLValueStringEx(DB.java:1355)
	at org.adempiere.controller.DeleteSelectionController.getValue(DeleteSelectionController.java:201)
	at org.adempiere.controller.DeleteSelectionController.getData(DeleteSelectionController.java:156)
	at org.adempiere.webui.window.WDeleteSelection.initComponents(WDeleteSelection.java:77)
	at org.adempiere.webui.window.WDeleteSelection.showDialog(WDeleteSelection.java:125)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onDeleteSelection(AbstractADWindowPanel.java:1644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:383)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:347)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

===========> CWindowToolbar.doOnClick: Could not invoke Toolbar listener method: onDeleteSelection() [38]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:383)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:347)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)
caused by: java.lang.IllegalArgumentException: No SQL
	at org.compiere.util.DB.prepareStatement(DB.java:765)
	at org.compiere.util.DB.prepareStatement(DB.java:736)
	at org.compiere.util.DB.getSQLValueStringEx(DB.java:1355)
	at org.adempiere.controller.DeleteSelectionController.getValue(DeleteSelectionController.java:201)
	at org.adempiere.controller.DeleteSelectionController.getData(DeleteSelectionController.java:156)
	at org.adempiere.webui.window.WDeleteSelection.initComponents(WDeleteSelection.java:77)
	at org.adempiere.webui.window.WDeleteSelection.showDialog(WDeleteSelection.java:125)
	at org.adempiere.webui.panel.AbstractADWindowPanel.onDeleteSelection(AbstractADWindowPanel.java:1644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.adempiere.webui.component.CWindowToolbar.doOnClick(CWindowToolbar.java:383)
	at org.adempiere.webui.component.CWindowToolbar.onEvent(CWindowToolbar.java:347)
	at org.zkoss.zk.ui.impl.EventProcessor.process0(EventProcessor.java:197)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:141)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:519)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:446)

**NOTE:** I have edited the line:
_===========> MLookupFactory.getLookup_TableDirEmbed: No Identifier records found: Primary_ID [38]_
with replacing the actual column name with **Primary_ID**.

**Comment by e-Evolution** [comment]
@ishanuda what is table that have not identifiers ?

We can adding to solve this issue

**Comment by yamelsenih** [comment]
it don't have a reply from user.
