### ISSUE TITLE
Oracle Error Migration 72 - Migration resize SQLStatement - 3.9.0 (D)  java.sql.SQLException: ORA-22859: invalid modification of columns

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#822]
12:37:12.000 MigrationApply.addLog: 0 - null - null - Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
12:37:12.000 MigrationApply.addLog: 0 - null - null - Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
===========> MigrationApply.process: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:270)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:682)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.util.DB.executeUpdateEx(DB.java:1128)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1179)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1170)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:795)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:677)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: java.sql.SQLException: ORA-22859: invalid modification of columns
; State=99999; ErrorCode=22859
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1119)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1179)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1170)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:795)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:677)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

12:37:12.005   MIssue.create: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
12:37:12.005   MIssue.create: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
-----------> POInfo.loadAdditionalAttributes: Table [AD_Issue] - Attribute [IsIgnoreMigration] Not found [1]
-----------> POInfo.loadAdditionalAttributes: Table [AD_Issue] - Attribute [IsIgnoreMigration] Not found [1]
12:37:12.011   GridField.loadLookup: (SystemStatus) [1]
12:37:12.011   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.model.MMigrationStep.bailout(MMigrationStep.java:270)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:682)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.util.DB.executeUpdateEx(DB.java:1128)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1179)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1170)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:795)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:677)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: java.sql.SQLException: ORA-22859: invalid modification of columns
; State=99999; ErrorCode=22859
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1119)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1179)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1170)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:795)
	at org.compiere.model.MMigrationStep.rollbackPO(MMigrationStep.java:677)
	at org.compiere.model.MMigrationStep.rollback(MMigrationStep.java:295)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:202)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

12:37:17.100 Trx.rollback: **** TrxRun_379062d4-e12d-470a-82dc-d711237ee951 [1]
12:37:17.100 Trx.rollback: **** TrxRun_379062d4-e12d-470a-82dc-d711237ee951 [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00072_MigrationResizeSQLStatement.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:289)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

12:37:17.101   MIssue.create: Loading Migration from XML failed. [1]
12:37:17.101   MIssue.create: Loading Migration from XML failed. [1]
12:37:17.101   GridField.loadLookup: (SystemStatus) [1]
12:37:17.101   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed. [1]
org.adempiere.exceptions.AdempiereException: Loading migration from /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00072_MigrationResizeSQLStatement.xml failed.
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 20; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:289)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

org.adempiere.exceptions.AdempiereException: Process failed during execution Error:  Loading Migration from XML failed.
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:261)
	at org.adempiere.process.MigrationLoader.main(MigrationLoader.java:63)

**Comment by yamelsenih** [comment]
Hi @e-Evolution it return a error for postgreSQL, see the log:

<pre>
Application failed. org.postgresql.util.PSQLException: ERROR: cannot ALTER TABLE "ad_migrationstep" because it has pending trigger events java.sql.BatchUpdateException: Batch entry 7 ALTER TABLE AD_MigrationStep DROP COLUMN RollbackStatement was aborted: ERROR: cannot ALTER TABLE "ad_migrationstep" because it has pending trigger events  Call getNextException to see other errors in the batch.
</pre>
![issue10](https://cloud.githubusercontent.com/assets/2333092/24133527/fa071420-0dd3-11e7-874f-7f46717471f3.png)

**Comment by e-Evolution** [comment]
Hi @yamelsenih your last commit launch  an error for Oracle again.

10:57:56.964   MMigrationStep.rollbackPO: Synchronizing column: MColumn[57874-SQLStatement] in table: MTable[53218-AD_MigrationStep] [1]
-----------> MMigrationStep.bailout: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
-----------> MMigrationStep.bailout: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD.  Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
-----------> MMigration.apply: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
-----------> MMigration.apply: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
10:57:57.166   MMigration.updateStatus: Migration 72 - Migration resize SQLStatement - 3.9.0 (D)  ---> Partially Applied (P) [1]
10:57:57.166   MMigration.updateStatus: Migration 72 - Migration resize SQLStatement - 3.9.0 (D)  ---> Partially Applied (P) [1]
10:57:57.171   MMigration.updateStatus: Migration 72 - Migration resize SQLStatement - 3.9.0 (D)  ---> Partially Applied (P) [1]
10:57:57.171   MMigration.updateStatus: Migration 72 - Migration resize SQLStatement - 3.9.0 (D)  ---> Partially Applied (P) [1]
10:57:57.171 MigrationApply.addLog: 0 - null - null - Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
10:57:57.171 MigrationApply.addLog: 0 - null - null - Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
===========> MigrationApply.process: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns
 [1]
org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 72 - Migration resize SQLStatement - 3.9.0 (D) ; Step: 60; Type: AD. Rollback failed. org.adempiere.exceptions.DBException: java.sql.SQLException: ORA-22859: invalid modification of columns

	at org.compiere.
