### ISSUE TITLE
Migration 137 Oracle Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#824]
17:05:32.257   MMigration.syncColumn: Synchronizing column: MColumn[66648-M_Warehouse_ID] in table: MTable[771-M_Cost] [1]
===========> MMigrationStep.applySQL: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:32.299   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:32.299   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:32.299   GridField.loadLookup: (SystemStatus) [1]
17:05:32.299   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
-----------> MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
-----------> MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:37.457   MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 40; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:05:37.457   MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 40; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:05:37.476   MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:05:37.476   MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:05:37.496   MMigrationStep.apply: Applying migration step: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
17:05:37.496   MMigrationStep.apply: Applying migration step: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:37.502   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:37.502   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:37.523   GridField.loadLookup: (SystemStatus) [1]
17:05:37.523   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
-----------> MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
-----------> MMigration.apply: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:42.574   MMigration.updateStatus: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D)  ---> Partially Applied (P) [1]
17:05:42.574   MMigration.updateStatus: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D)  ---> Partially Applied (P) [1]
17:05:42.580   MMigration.updateStatus: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D)  ---> Partially Applied (P) [1]
17:05:42.580   MMigration.updateStatus: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D)  ---> Partially Applied (P) [1]
17:05:42.580 MigrationApply.addLog: 0 - null - null - Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:42.580 MigrationApply.addLog: 0 - null - null - Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
===========> MigrationApply.process: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
org.adempiere.exceptions.AdempiereException: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint

	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:389)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:225)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
; State=null; ErrorCode=17081
	at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4615)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeBatch(NewProxyStatement.java:743)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:354)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:225)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:05:42.581   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:42.581   MIssue.create: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
17:05:42.582   GridField.loadLookup: (SystemStatus) [1]
17:05:42.582   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint
 [1]
org.adempiere.exceptions.AdempiereException: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.BatchUpdateException: se ha producido un error durante el procesamiento por lotes: ORA-02443: Cannot drop constraint  - nonexistent constraint

**Comment by e-Evolution** [comment]
02:23:58.080   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00137_320_BugFixWarehouseInCostDimension.xml [1]
02:23:58.082   MigrationFromXML.lambda$loadFile$0: Migration 137 - Bugfix for warehouse in cost dimension #320 - 3.9.0 (D)  ---> Migration already applied - skipping. [1]
