### ISSUE TITLE
Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#827]
19:44:08.236   MMigrationStep.apply: Applying migration step: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  [1]
19:44:08.236   MMigrationStep.apply: Applying migration step: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:08.249   MIssue.create: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:08.249   MIssue.create: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:08.256   GridField.loadLookup: (SystemStatus) [1]
19:44:08.256   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
-----------> MMigration.apply: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
-----------> MMigration.apply: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:13.413   MMigrationStep.apply: Applying migration step: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  [1]
19:44:13.413   MMigrationStep.apply: Applying migration step: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:13.417   MIssue.create: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:13.417   MIssue.create: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:13.417   GridField.loadLookup: (SystemStatus) [1]
19:44:13.417   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
-----------> MMigration.apply: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
-----------> MMigration.apply: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:18.450   MMigration.updateStatus: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D)  ---> Unapplied (U) [1]
19:44:18.450   MMigration.updateStatus: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D)  ---> Unapplied (U) [1]
19:44:18.455   MMigration.updateStatus: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D)  ---> Unapplied (U) [1]
19:44:18.455   MMigration.updateStatus: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D)  ---> Unapplied (U) [1]
19:44:18.465 MigrationApply.addLog: 0 - null - null - Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
19:44:18.465 MigrationApply.addLog: 0 - null - null - Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
===========> MigrationApply.process: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
 [1]
org.adempiere.exceptions.AdempiereException: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D) ; Step: 0; Type: SQL.  Application failed. 
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

**Comment by e-Evolution** [comment]
02:23:58.516   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00254_482_DropBadConstraint.xml [1]
02:23:58.519   MigrationFromXML.lambda$loadFile$0: Migration 254 - Drop Bad constraint for table #482 - 3.9.0 (D)  ---> Migration already applied - skipping. [1]
