### ISSUE TITLE
Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#828]
19:52:54.695 MigrationApply.addLog: 0 - null - null - Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
19:52:54.695 MigrationApply.addLog: 0 - null - null - Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
===========> MigrationApply.process: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
org.adempiere.exceptions.AdempiereException: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state

	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:389)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:225)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
; State=65000; ErrorCode=6575
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:64)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:357)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:225)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

19:52:54.696   MIssue.create: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
19:52:54.696   MIssue.create: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
19:52:54.696   GridField.loadLookup: (SystemStatus) [1]
19:52:54.696   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state
 [1]
org.adempiere.exceptions.AdempiereException: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
java.sql.SQLException: ORA-06575: Package or function CHANGESBCONTEXTVALUE is in an invalid state

**Comment by e-Evolution** [comment]
02:23:58.526   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/00264_340_Fixed_SB_Context.xml [1]
02:23:58.529   MigrationFromXML.lambda$loadFile$0: Migration 264 - Smart Browse context is changed from table #340 - 3.9.0 (D)  ---> Migration already applied - skipping. [1]
