### ISSUE TITLE
Oracle Migration 1540 - Increase Script size to AD_Rule #705 - 3.9.0 (D)  ---> Unapplied (U) [1]

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#831]
01:33:26.105   MMigration.updateStatus: Migration 1540 - Increase Script size to AD_Rule #705 - 3.9.0 (D)  ---> Unapplied (U) [1]
01:33:26.105 MigrationApply.addLog: 0 - null - null - java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype
 [1]
01:33:26.105 MigrationApply.addLog: 0 - null - null - java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype
 [1]
===========> MigrationApply.process: java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype
 [1]
org.adempiere.exceptions.AdempiereException: java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype

	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:208)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:281)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:278)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.DBException: java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype

	at org.compiere.util.DB.executeUpdateEx(DB.java:1128)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1179)
	at org.compiere.util.DB.executeUpdateEx(DB.java:1170)
	at org.compiere.model.MColumn.syncDatabase(MColumn.java:795)
	at org.compiere.model.MMigration.syncColumn(MMigration.java:459)
	at org.compiere.model.MMigration.apply(MMigration.java:159)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.SQLSyntaxErrorException: ORA-00910: specified length too long for its datatype
; State=42000; ErrorCode=910

**Comment by e-Evolution** [comment]
02:23:59.215   MigrationFromXML.loadFile: Loading file: /Users/e-Evolution/Develop/ADempiere/adempiere/install/build/Adempiere/migration/380lts-release/01540_705_IncreaseScriptSizeToAD_Rule.xml [1]
02:23:59.219   MigrationFromXML.lambda$loadFile$0: Migration 1540 - Increase Script size to AD_Rule #705 - 3.9.0 (D)  ---> Migration already applied - skipping. [1]
