### ISSUE TITLE
Error when try Synchronizing Report View with Table the column not exits AD_LANGUAGE  for AD_ReportView_v

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#842]
15:57:48.596 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
15:57:48.596 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
===========> DB.executeUpdate:  UPDATE AD_ReportView rvt SET PrintName = COALESCE(rvt.Description, (SELECT COALESCE(e.PrintName, t.Name) 				FROM AD_Table t				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = t.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID))WHERE EXISTS (SELECT 1  				FROM AD_Table tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID  				AND tt.Name <> COALESCE(rvt.PrintName, '')				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
java.sql.SQLException: ORA-12704: character set mismatch
; State=72000; ErrorCode=12704
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:947)
	at org.compiere.util.DB.executeUpdate(DB.java:933)
	at org.compiere.process.SynchronizeTerminology.doIt(SynchronizeTerminology.java:886)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

15:57:48.808   MIssue.create:  UPDATE AD_ReportView rvt SET PrintName = COALESCE(rvt.Description, (SELECT COALESCE(e.PrintName, t.Name) 				FROM AD_Table t				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = t.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID))WHERE EXISTS (SELECT 1  				FROM AD_Table tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID  				AND tt.Name <> COALESCE(rvt.PrintName, '')				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
15:57:48.808   MIssue.create:  UPDATE AD_ReportView rvt SET PrintName = COALESCE(rvt.Description, (SELECT COALESCE(e.PrintName, t.Name) 				FROM AD_Table t				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = t.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID))WHERE EXISTS (SELECT 1  				FROM AD_Table tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID  				AND tt.Name <> COALESCE(rvt.PrintName, '')				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
15:57:48.809   GridField.loadLookup: (SystemStatus) [1]
15:57:48.809   GridField.loadLookup: (SystemStatus) [1]
===========> DB.executeUpdate:  UPDATE AD_ReportView rvt SET PrintName = COALESCE(rvt.Description, (SELECT COALESCE(e.PrintName, t.Name) 				FROM AD_Table t				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = t.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID))WHERE EXISTS (SELECT 1  				FROM AD_Table tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID  				AND tt.Name <> COALESCE(rvt.PrintName, '')				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
java.sql.SQLException: ORA-12704: character set mismatch
; State=72000; ErrorCode=12704
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:947)
	at org.compiere.util.DB.executeUpdate(DB.java:933)
	at org.compiere.process.SynchronizeTerminology.doIt(SynchronizeTerminology.java:886)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

===========> DB.saveError: DBExecuteError - ORA-12704: character set mismatch
 [1]
===========> DB.saveError: DBExecuteError - ORA-12704: character set mismatch
 [1]
15:57:54.396 SynchronizeTerminology.doIt:   trl rows updated: -1 [1]
15:57:54.396 SynchronizeTerminology.doIt:   trl rows updated: -1 [1]
15:57:54.397 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
15:57:54.397 SynchronizeTerminology.doIt: Synchronizing Report View with Table [1]
===========> DB.executeUpdate:  UPDATE AD_ReportView_Trl rvt SET Name = (SELECT tt.Name 				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID 				AND tt.AD_Language = rvt.AD_Language), PrintName = (SELECT COALESCE(et.PrintName, et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)	LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language), Description = (SELECT COALESCE(et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)		LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language)WHERE EXISTS (SELECT 1  				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID AND tt.AD_Language = rvt.AD_Language  				AND tt.Name<>rvt.Name				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
java.sql.SQLSyntaxErrorException: ORA-00904: "RVT"."AD_LANGUAGE": invalid identifier
; State=42000; ErrorCode=904
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:947)
	at org.compiere.util.DB.executeUpdate(DB.java:933)
	at org.compiere.process.SynchronizeTerminology.doIt(SynchronizeTerminology.java:922)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

15:57:54.564   MIssue.create:  UPDATE AD_ReportView_Trl rvt SET Name = (SELECT tt.Name 				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID 				AND tt.AD_Language = rvt.AD_Language), PrintName = (SELECT COALESCE(et.PrintName, et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)		LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language), Description = (SELECT COALESCE(et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)		LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language)WHERE EXISTS (SELECT 1  				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID AND tt.AD_Language = rvt.AD_Language  				AND tt.Name<>rvt.Name				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
15:57:54.564   MIssue.create:  UPDATE AD_ReportView_Trl rvt SET Name = (SELECT tt.Name 				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID 				AND tt.AD_Language = rvt.AD_Language), PrintName = (SELECT COALESCE(et.PrintName, et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)		LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language), Description = (SELECT COALESCE(et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)		LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language)WHERE EXISTS (SELECT 1  				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID AND tt.AD_Language = rvt.AD_Language  				AND tt.Name<>rvt.Name				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
15:57:54.566   GridField.loadLookup: (SystemStatus) [1]
15:57:54.566   GridField.loadLookup: (SystemStatus) [1]
===========> DB.executeUpdate:  UPDATE AD_ReportView_Trl rvt SET Name = (SELECT tt.Name 				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID 				AND tt.AD_Language = rvt.AD_Language), PrintName = (SELECT COALESCE(et.PrintName, et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)				LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)	LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language), Description = (SELECT COALESCE(et.Name, tt.Name) 				FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)		LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language)WHERE EXISTS (SELECT 1  				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID AND tt.AD_Language = rvt.AD_Language  				AND tt.Name<>rvt.Name				AND rv.IsCentrallyMaintained = 'Y')  [TrxRun_55354acf-4eb0-4e7d-aa69-59bd0c423967] [1]
java.sql.SQLSyntaxErrorException: ORA-00904: "RVT"."AD_LANGUAGE": invalid identifier
; State=42000; ErrorCode=904
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1046)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4709)
	at oracle.jdbc.driver.OraclePreparedStatement.doScrollPstmtExecuteUpdate(OraclePreparedStatement.java:10613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3611)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3694)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1354)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1045)
	at org.compiere.util.DB.executeUpdate(DB.java:947)
	at org.compiere.util.DB.executeUpdate(DB.java:933)
	at org.compiere.process.SynchronizeTerminology.doIt(SynchronizeTerminology.java:922)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)

===========> DB.saveError: DBExecuteError - ORA-00904: "RVT"."AD_LANGUAGE": invalid identifier
 [1]
===========> DB.saveError: DBExecuteError - ORA-00904: "RVT"."AD_LANGUAGE": invalid identifier
 [1]
15:57:59.602 SynchronizeTerminology.doIt:   trl rows updated: -1 [1]

**Comment by e-Evolution** [comment]
Error introducing in #237

**Comment by e-Evolution** [comment]
@yamelsenih this query not work in oracle :-(

UPDATE AD_ReportView_Trl rvt SET 
Name = 
(SELECT tt.Name 				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 				
WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID 				AND tt.AD_Language = rvt.AD_Language), PrintName = (SELECT COALESCE(et.PrintName, et.Name, tt.Name) 				
FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)				
LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)	
LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)		
WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language), Description = (SELECT COALESCE(et.Name, tt.Name) 				
FROM AD_Table t				INNER JOIN AD_Table_Trl tt ON(tt.AD_Table_ID = t.AD_Table_ID)				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID)		
LEFT JOIN AD_Element e ON(SUBSTR(t.TableName, 1, LENGTH(t.TableName) - 4) || '_ID' = e.ColumnName)				
LEFT JOIN AD_Element_Trl et ON(et.AD_Element_ID = e.AD_Element_ID AND et.AD_Language = rvt.AD_Language)				
WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID				AND tt.AD_Language = rvt.AD_Language) WHERE 
EXISTS (SELECT 1  				FROM AD_Table_Trl tt 				INNER JOIN AD_ReportView rv ON(rv.AD_Table_ID = tt.AD_Table_ID) 			
WHERE rv.AD_ReportView_ID = rvt.AD_ReportView_ID AND tt.AD_Language = rvt.AD_Language  				AND tt.Name<>rvt.Name				AND rv.IsCentrallyMaintained = 'Y');

**Comment by e-Evolution** [comment]
@yamelsenih can please validate this change.
