### ISSUE TITLE
New pay selection not work get an invalid query  

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#844]
@yamelsenih your new pay selection functionality not work got next error

I see that are try replace of currency context but this should show as a criterial but never is show in smart browser header.

![captura de pantalla 2017-03-17 a la s 23 04 51](https://cloud.githubusercontent.com/assets/786968/24069137/3ba8d938-0b66-11e7-9135-4e417ad842d8.png)

VBrowser.run: SELECT DISTINCT inv.C_Invoice_ID AS INV_C_Invoice_ID, invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID) AS INV_AmtSource, inv.C_BPartner_ID AS INV_C_BPartner_ID, inv.DateInvoiced AS INV_DateInvoiced, inv.DueDate AS INV_DueDate, daysBetween(getDate(), inv.DueDate) AS INV_DaysDue, inv.DocumentNo AS INV_DocumentNo, (COALESCE((SELECT COUNT(cips.C_PaySchedule_ID)  		FROM C_InvoicePaySchedule cips  		WHERE cips.C_Invoice_ID = inv.C_Invoice_ID  		AND cips.DueDate <= inv.DueDate 		GROUP BY cips.C_Invoice_ID), 1) || '/' ||  COALESCE((SELECT COUNT(cips.C_InvoicePaySchedule_ID) MaxPayNo  	FROM C_InvoicePaySchedule cips  	WHERE cips.C_Invoice_ID = inv.C_Invoice_ID 	GROUP BY cips.C_Invoice_ID), 1)) AS INV_PaymentNumber, inv.C_Currency_ID AS INV_C_Currency_ID, inv.GrandTotal AS INV_GrandTotal, currencyConvert(inv.GrandTotal, inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID,inv.AD_Client_ID, inv.AD_Org_ID) AS INV_ConvertedAmt, currencyConvert(paymentTermDiscount(inv.GrandTotal, inv.C_Currency_ID, inv.C_PaymentTerm_ID, inv.DateInvoiced, TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD')), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_DiscountAmt, currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_OpenAmt, currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_PayAmt, inv.C_ConversionType_ID AS INV_C_ConversionType_ID, inv.C_DocType_ID AS INV_C_DocType_ID, inv.IsInDispute AS INV_IsInDispute, inv.PaymentRule AS INV_PaymentRule, inv.C_PaymentTerm_ID AS INV_C_PaymentTerm_ID, inv.C_InvoicePaySchedule_ID AS INV_C_InvoicePaySchedule_ID, inv.IsSOTrx AS IsSOTrx, inv.Description AS INV_Description, CASE WHEN '' = 'Y' THEN bp.PaymentRule ELSE bp.PaymentRulePO END AS BP_PaymentRule, bp.SOCreditStatus AS BP_SOCreditStatus, bp.TotalOpenBalance AS BP_TotalOpenBalance FROM  C_Invoice_v inv INNER JOIN C_BPartner bp ON(bp.C_BPartner_ID = inv.C_BPartner_ID)  WHERE inv.DocStatus IN('CO', 'CL') AND inv.IsPaid = 'N' AND inv.IsSOTrx = 'N'
AND NOT EXISTS(SELECT 1 FROM C_PaySelectionLine psl WHERE psl.C_PaySelection_ID = 1000002 AND psl.C_Invoice_ID = inv.C_Invoice_ID)
AND NOT EXISTS(SELECT 1 FROM C_PaySelection ps INNER JOIN C_PaySelectionLine psl ON(psl.C_PaySelection_ID = ps.C_PaySelection_ID) 
		WHERE ps.DocStatus IN('CO', 'CL') AND psl.C_Invoice_ID = inv.C_Invoice_ID) AND CASE WHEN 'N' = 'N' THEN 'N' ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchPO m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' AND (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchInv m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'B'  ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchPO m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'P' ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchInv m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'R'  ELSE 'N' END END END END=?  AND daysBetween(getDate(), inv.DueDate) >= ?  AND daysBetween(getDate(), inv.DueDate) <= ?  AND inv.AD_Client_ID IN(0,1000002) AND inv.AD_Org_ID IN(1000003,1000025,1000004,1000026,1000005,1000027,1000006,1000028,1000021,1000022,1000023,1000002,1000024,1000007,1000029,1000008,1000009,1000040,1000041,1000020,1000014,1000036,1000015,1000037,1000016,1000038,1000017,1000039,1000010,1000032,1000011,1000033,1000012,1000034,1000013,1000035,1000018,1000019,0,1000030,1000031) AND (bp.C_BPartner_ID IS NULL OR bp.C_BPartner_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 291 AND AD_User_ID <> 100 AND IsActive = 'Y' )) ORDER BY 4,5 [220]
===========> VBrowser.run: SELECT DISTINCT inv.C_Invoice_ID AS INV_C_Invoice_ID, invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID) AS INV_AmtSource, inv.C_BPartner_ID AS INV_C_BPartner_ID, inv.DateInvoiced AS INV_DateInvoiced, inv.DueDate AS INV_DueDate, daysBetween(getDate(), inv.DueDate) AS INV_DaysDue, inv.DocumentNo AS INV_DocumentNo, (COALESCE((SELECT COUNT(cips.C_PaySchedule_ID)  		FROM C_InvoicePaySchedule cips  		WHERE cips.C_Invoice_ID = inv.C_Invoice_ID  		AND cips.DueDate <= inv.DueDate 		GROUP BY cips.C_Invoice_ID), 1) || '/' ||  COALESCE((SELECT COUNT(cips.C_InvoicePaySchedule_ID) MaxPayNo  	FROM C_InvoicePaySchedule cips  	WHERE cips.C_Invoice_ID = inv.C_Invoice_ID 	GROUP BY cips.C_Invoice_ID), 1)) AS INV_PaymentNumber, inv.C_Currency_ID AS INV_C_Currency_ID, inv.GrandTotal AS INV_GrandTotal, currencyConvert(inv.GrandTotal, inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID,inv.AD_Client_ID, inv.AD_Org_ID) AS INV_ConvertedAmt, currencyConvert(paymentTermDiscount(inv.GrandTotal, inv.C_Currency_ID, inv.C_PaymentTerm_ID, inv.DateInvoiced, TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD')), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_DiscountAmt, currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_OpenAmt, currencyConvert(invoiceOpen(inv.C_Invoice_ID, inv.C_InvoicePaySchedule_ID), inv.C_Currency_ID, , TO_DATE('2017-03-17 00:00:00','YYYY-MM-DD'), inv.C_ConversionType_ID, inv.AD_Client_ID, inv.AD_Org_ID) AS INV_PayAmt, inv.C_ConversionType_ID AS INV_C_ConversionType_ID, inv.C_DocType_ID AS INV_C_DocType_ID, inv.IsInDispute AS INV_IsInDispute, inv.PaymentRule AS INV_PaymentRule, inv.C_PaymentTerm_ID AS INV_C_PaymentTerm_ID, inv.C_InvoicePaySchedule_ID AS INV_C_InvoicePaySchedule_ID, inv.IsSOTrx AS IsSOTrx, inv.Description AS INV_Description, CASE WHEN '' = 'Y' THEN bp.PaymentRule ELSE bp.PaymentRulePO END AS BP_PaymentRule, bp.SOCreditStatus AS BP_SOCreditStatus, bp.TotalOpenBalance AS BP_TotalOpenBalance FROM  C_Invoice_v inv INNER JOIN C_BPartner bp ON(bp.C_BPartner_ID = inv.C_BPartner_ID)  WHERE inv.DocStatus IN('CO', 'CL') AND inv.IsPaid = 'N' AND inv.IsSOTrx = 'N'
AND NOT EXISTS(SELECT 1 FROM C_PaySelectionLine psl WHERE psl.C_PaySelection_ID = 1000002 AND psl.C_Invoice_ID = inv.C_Invoice_ID)
AND NOT EXISTS(SELECT 1 FROM C_PaySelection ps INNER JOIN C_PaySelectionLine psl ON(psl.C_PaySelection_ID = ps.C_PaySelection_ID) 
		WHERE ps.DocStatus IN('CO', 'CL') AND psl.C_Invoice_ID = inv.C_Invoice_ID) AND CASE WHEN 'N' = 'N' THEN 'N' ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchPO m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' AND (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchInv m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'B'  ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchPO m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'P' ELSE  CASE WHEN (CASE WHEN (EXISTS(SELECT 1 FROM C_InvoiceLine il INNER JOIN M_MatchInv m ON(il.C_InvoiceLine_ID = m.C_InvoiceLine_ID) WHERE inv.C_Invoice_ID = il.C_Invoice_ID GROUP BY il.C_Invoice_ID HAVING sum(il.QtyInvoiced) = sum(m.Qty))) THEN 'Y' ELSE 'N' END) = 'Y' THEN 'R'  ELSE 'N' END END END END=?  AND daysBetween(getDate(), inv.DueDate) >= ?  AND daysBetween(getDate(), inv.DueDate) <= ?  AND inv.AD_Client_ID IN(0,1000002) AND inv.AD_Org_ID IN(1000003,1000025,1000004,1000026,1000005,1000027,1000006,1000028,1000021,1000022,1000023,1000002,1000024,1000007,1000029,1000008,1000009,1000040,1000041,1000020,1000014,1000036,1000015,1000037,1000016,1000038,1000017,1000039,1000010,1000032,1000011,1000033,1000012,1000034,1000013,1000035,1000018,1000019,0,1000030,1000031) AND (bp.C_BPartner_ID IS NULL OR bp.C_BPartner_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 291 AND AD_User_ID <> 100 AND IsActive = 'Y' )) ORDER BY 4,5 [220]
org.postgresql.util.PSQLException: ERROR: syntax error at or near ","
  Position: 843
  Location: File: scan.l, Routine: scanner_yyerror, Line: 1086
  SQLState del servidor: 42601.; State=42601; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.eevolution.form.VBrowser$Worker.run(VBrowser.java:616)

**Comment by e-Evolution** [comment]
@Yamel I think that problem is exist 2 smart browser with similar functionality , but the right never was update in process that called from C_PaymentSelection

kind regards
