### ISSUE TITLE
Ambidexter General Ledger Reconciliation

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#889]
Can you please elaborate ?

**Comment by adaxa-steven** [comment]
need more info .. no idea!

**Comment by adaxa-steven** [comment]
sorry - no idea.

**Comment by e-Evolution** [comment]
Hi @adaxa-steven I have 137_Ambidexter_GL_Rec #955(Adaxa) information script

**Comment by adaxa-steven** [comment]
https://idempiere.atlassian.net/browse/IDEMPIERE-137
"because of the old VFactReconcile class contains code for retrieving data and generating form. so we have to refactor and divide between generating form and retrieving data. we submitted this project on bitbucket repository so you can pull this project and testing by yourself. we have generated the migration script to repair the constraint and primary key in Fact_Reconciliation table.
the repository url is https://bitbucket.org/uthadehikaru/ambidexter-gl-reconciliation
note :
because of the difference between Client and WebUI. so we removed a column 'accounting amt' to make a same data table between client and webui, because we couldn't find how to hide the 'accounting amt' on webui as same as on client.
best regards
zuhri utama"

**Comment by yamelsenih** [comment]
I test it and throw a error:

<pre>
===========> DB.executeUpdate: INSERT INTO Fact_Reconciliation (Fact_Acct_ID,MatchCode,UpdatedBy,CreatedBy,Fact_Reconciliation_ID,AD_Client_ID,AD_Org_ID,Created,IsActive,Updated) VALUES (1000038,'Manual: SuperUser 2017-06-18 11:57:48.490',100,100,0,11,50001,TO_TIMESTAMP('2017-06-18 11:57:48','YYYY-MM-DD HH24:MI:SS'),'Y',TO_TIMESTAMP('2017-06-18 11:57:48','YYYY-MM-DD HH24:MI:SS')) [POSave_0b1af945-24f5-4483-9fea-edf129cd1bde] [14]
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "fact_reconciliation_key"
  Detail: Key (fact_reconciliation_id)=(0) already exists.; State=23505; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1046)
	at org.compiere.util.DB.executeUpdate(DB.java:908)
	at org.compiere.util.DB.executeUpdate(DB.java:895)
	at org.compiere.model.PO.saveNew(PO.java:2855)
	at org.compiere.model.PO.save(PO.java:2192)
	at org.compiere.model.PO.saveEx(PO.java:2276)
	at org.compiere.apps.form.VFactReconcile.generateReconciliation(VFactReconcile.java:641)
	at org.compiere.apps.form.VFactReconcile.actionPerformed(VFactReconcile.java:474)

===========> DB.saveError: DBExecuteError - ERROR: duplicate key value violates unique constraint "fact_reconciliation_key"
  Detail: Key (fact_reconciliation_id)=(0) already exists. [14]
-----------> MFactReconciliation.saveNew: [POSave_0b1af945-24f5-4483-9fea-edf129cd1bde]Not inserted - Fact_Reconciliation [14]
Exception in thread "AWT-EventQueue-0" org.adempiere.exceptions.AdempiereException: ERROR: duplicate key value violates unique constraint "fact_reconciliation_key"
  Detail: Key (fact_reconciliation_id)=(0) already exists.
	at org.compiere.model.PO.saveEx(PO.java:2283)
	at org.compiere.apps.form.VFactReconcile.generateReconciliation(VFactReconcile.java:641)
	at org.compiere.apps.form.VFactReconcile.actionPerformed(VFactReconcile.java:474)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

I will to test it and fixed for close it issue

**Comment by yamelsenih** [comment]
Also is added a Fact_Reconciliation_ID and the old data don't have ID reference, i propose:

- Create a table Fact_Reconciliation_TMP as SELECT * FROM Fact_Reconciliation
- TRUNCATE TABLE Fact_Reconciliation
- Apply constraints
- INSERT INTO Fact_Reconciliation FROM Fact_Reconciliation_TMP with generated ID
- DROP TABLE Fact_Reconciliation_TMP

**Comment by yamelsenih** [comment]
I will to fixed it.

**Comment by yamelsenih** [comment]
It is worked.

If exist a problem will be reopen
