### ISSUE TITLE
The invoice that contain both fixed asset and normal products fail

### ISSUE THREAD

**Issue by erprafaelrodriguez** [adempiere/adempiere#916]
# ****# Hi Team Adempiere:

Somebody have problem similar?

Required created a AP Invoice whit two lines Mixed, Asset Fixed and normal Product ... The mesage in the log is:**** 

Regards Team!

-------------------------------
===========> ModelValidationEngine.fireDocValidate: No new bills that contain both fixed and normal products [73]
org.compiere.FA.exceptions.AssetInvoiceWithMixedLines_LRO: No new bills that contain both fixed and normal products
                at org.compiere.FA.model.ModelValidator.validateFixedAssetsInvoice_LRO(Unknown Source)
                at org.compiere.FA.model.ModelValidator.docValidate(Unknown Source)
                at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:547)
                at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:480)
                at org.compiere.model.MInvoice.prepareIt(MInvoice.java:1379)
                at org.compiere.process.DocumentEngine.prepareIt(DocumentEngine.java:409)
                at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:278)
                at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:256)
                at org.compiere.model.MInvoice.processIt(MInvoice.java:1275)
                at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:897)
                at org.compiere.wf.MWFActivity.run(MWFActivity.java:789)
                at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:370)
                at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:280)
                at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:278)
                at org.compiere.wf.MWFActivity.run(MWFActivity.java:806)
                at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:502)
                at org.compiere.wf.MWorkflow.start(MWorkflow.java:727)
                at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:796)
 
-------------------------------
===========> ModelValidationEngine.fireDocValidate: No new bills that contain both fixed and normal products [163]
org.compiere.FA.exceptions.AssetInvoiceWithMixedLines_LRO: No new bills that contain both fixed and normal products
                at org.compiere.FA.model.ModelValidator.validateFixedAssetsInvoice_LRO(Unknown Source)
                at org.compiere.FA.model.ModelValidator.docValidate(Unknown Source)
                at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:547)
                at org.compiere.model.ModelValidationEngine.fireDocValidate(ModelValidationEngine.java:480)
                at org.compiere.model.MInvoice.prepareIt(MInvoice.java:1379)
                at org.compiere.process.DocumentEngine.prepareIt(DocumentEngine.java:409)
                at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:278)
                at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:256)
                at org.compiere.model.MInvoice.processIt(MInvoice.java:1275)
                at org.compiere.wf.MWFActivity.performWork(MWFActivity.java:897)
                at org.compiere.wf.MWFActivity.run(MWFActivity.java:789)
                at org.compiere.wf.MWFProcess.startNext(MWFProcess.java:370)
                at org.compiere.wf.MWFProcess.checkActivities(MWFProcess.java:280)
                at org.compiere.wf.MWFActivity.setWFState(MWFActivity.java:278)
                at org.compiere.wf.MWFActivity.run(MWFActivity.java:806)
                at org.compiere.wf.MWFProcess.startWork(MWFProcess.java:502)
                at org.compiere.wf.MWorkflow.start(MWorkflow.java:727)
                at org.compiere.wf.MWorkflow.startWait(MWorkflow.java:796)

**Comment by mckayERP** [comment]
I agree with this issue.  There is no reason to impose this limit on
invoices.  Any invoice line should be able to add or reduce assets.

Mike

**Comment by e-Evolution** [comment]
Hi I review of source code and this is comment

MProduct product = MProduct.get(line.getCtx(), line.getM_Product_ID());
					if (product.isItem())
					{
						// Only items are forbiden for FA invoices because in Romania these should use
						// V_Liability vendor account and not V_Liability_FixedAssets vendor account
						hasNormalLines = true;
					}

So the unique consideration is that system will use  V_Liability_FixedAssets vs V_Liability of business partners
